// <auto-generated />
// This file was generated by a T4 template. Do not modify directly.

using CSLModsCommon.Manager;

namespace CSLModsCommon.Localization;

public static class SharedTranslations {
    /// <summary>
    /// Advanced
    /// </summary>
    public static string Advanced => LocalizationManager.Localize("Advanced");

    /// <summary>
    /// Alternative mod
    /// </summary>
    public static string AlternativeMod => LocalizationManager.Localize("AlternativeMod");

    /// <summary>
    /// Hold Alt to change all values
    /// </summary>
    public static string AltToChangeAll => LocalizationManager.Localize("AltToChangeAll");

    /// <summary>
    /// BETA
    /// </summary>
    public static string BETA => LocalizationManager.Localize("BETA");

    /// <summary>
    /// Both
    /// </summary>
    public static string Both => LocalizationManager.Localize("Both");

    /// <summary>
    /// Built In Function
    /// </summary>
    public static string BuiltInFunction => LocalizationManager.Localize("BuiltInFunction");

    /// <summary>
    /// Cancel
    /// </summary>
    public static string Cancel => LocalizationManager.Localize("Cancel");

    /// <summary>
    /// Changelog
    /// </summary>
    public static string Changelog => LocalizationManager.Localize("Changelog");

    /// <summary>
    /// Mod changelog
    /// </summary>
    public static string ChangelogHeader => LocalizationManager.Localize("ChangelogHeader");

    /// <summary>
    /// Check
    /// </summary>
    public static string Check => LocalizationManager.Localize("Check");

    /// <summary>
    /// Close
    /// </summary>
    public static string Close => LocalizationManager.Localize("Close");

    /// <summary>
    /// Compatibility Check
    /// </summary>
    public static string CompatibilityCheck => LocalizationManager.Localize("CompatibilityCheck");

    /// <summary>
    /// This function only detects compatibility issues for this mod. For all mods, use the Skyve mod.
    /// </summary>
    public static string CompatibilityCheckDescription => LocalizationManager.Localize("CompatibilityCheckDescription");

    /// <summary>
    /// Mod compatibility check
    /// </summary>
    public static string CompatibilityCheckHeader => LocalizationManager.Localize("CompatibilityCheckHeader");

    /// <summary>
    /// Incompatible mods detected. To ensure proper functionality, disable, unsubscribe from, or remove the following mods:
    /// </summary>
    public static string CompatibilityWarning => LocalizationManager.Localize("CompatibilityWarning");

    /// <summary>
    /// Compatible with the current game version
    /// </summary>
    public static string CompatibleCurrentGameVersion => LocalizationManager.Localize("CompatibleCurrentGameVersion");

    /// <summary>
    /// Compatible game versions
    /// </summary>
    public static string CompatibleGameVersions => LocalizationManager.Localize("CompatibleGameVersions");

    /// <summary>
    /// Logs copied to Desktop successfully.
    /// </summary>
    public static string CopiedLogsSucceeded => LocalizationManager.Localize("CopiedLogsSucceeded");

    /// <summary>
    /// Copy
    /// </summary>
    public static string Copy => LocalizationManager.Localize("Copy");

    /// <summary>
    /// Copy logs to desktop
    /// </summary>
    public static string CopyLogsToDesktop => LocalizationManager.Localize("CopyLogsToDesktop");

    /// <summary>
    /// Debug
    /// </summary>
    public static string Debug => LocalizationManager.Localize("Debug");

    /// <summary>
    /// Dependencies
    /// </summary>
    public static string Dependencies => LocalizationManager.Localize("Dependencies");

    /// <summary>
    /// Disabled
    /// </summary>
    public static string Disabled => LocalizationManager.Localize("Disabled");

    /// <summary>
    /// Discord get help
    /// </summary>
    public static string DiscordGetHelp => LocalizationManager.Localize("DiscordGetHelp");

    /// <summary>
    /// Functionality already included.
    /// </summary>
    public static string DuplicateFunctionality => LocalizationManager.Localize("DuplicateFunctionality");

    /// <summary>
    /// Enabling is not allowed
    /// </summary>
    public static string EnableNotAllowed => LocalizationManager.Localize("EnableNotAllowed");

    /// <summary>
    /// Error
    /// </summary>
    public static string Error => LocalizationManager.Localize("Error");

    /// <summary>
    /// Fatal
    /// </summary>
    public static string Fatal => LocalizationManager.Localize("Fatal");

    /// <summary>
    /// General
    /// </summary>
    public static string General => LocalizationManager.Localize("General");

    /// <summary>
    /// Handle Incompatible Mods
    /// </summary>
    public static string HandleIncompatibleMods => LocalizationManager.Localize("HandleIncompatibleMods");

    /// <summary>
    /// Improve mod shared translation
    /// </summary>
    public static string ImproveModSharedTranslation => LocalizationManager.Localize("ImproveModSharedTranslation");

    /// <summary>
    /// Improve mod translation
    /// </summary>
    public static string ImproveModTranslation => LocalizationManager.Localize("ImproveModTranslation");

    /// <summary>
    /// Incompatible Mods
    /// </summary>
    public static string IncompatibleMods => LocalizationManager.Localize("IncompatibleMods");

    /// <summary>
    /// Incompatible with this mod.
    /// </summary>
    public static string IncompatibleWithMod => LocalizationManager.Localize("IncompatibleWithMod");

    /// <summary>
    /// Info
    /// </summary>
    public static string Info => LocalizationManager.Localize("Info");

    /// <summary>
    /// Key Binding
    /// </summary>
    public static string KeyBinding => LocalizationManager.Localize("KeyBinding");

    /// <summary>
    /// Language
    /// </summary>
    public static string Language => LocalizationManager.Localize("Language");

    /// <summary>
    /// Arabic
    /// </summary>
    public static string Language_ar_SA => LocalizationManager.Localize("Language_ar_SA");

    /// <summary>
    /// Czech
    /// </summary>
    public static string Language_cs_CZ => LocalizationManager.Localize("Language_cs_CZ");

    /// <summary>
    /// German
    /// </summary>
    public static string Language_de_DE => LocalizationManager.Localize("Language_de_DE");

    /// <summary>
    /// English
    /// </summary>
    public static string Language_en_US => LocalizationManager.Localize("Language_en_US");

    /// <summary>
    /// Spanish
    /// </summary>
    public static string Language_es_ES => LocalizationManager.Localize("Language_es_ES");

    /// <summary>
    /// French
    /// </summary>
    public static string Language_fr_FR => LocalizationManager.Localize("Language_fr_FR");

    /// <summary>
    /// Italian
    /// </summary>
    public static string Language_it_IT => LocalizationManager.Localize("Language_it_IT");

    /// <summary>
    /// Japanese
    /// </summary>
    public static string Language_ja_JP => LocalizationManager.Localize("Language_ja_JP");

    /// <summary>
    /// Korean
    /// </summary>
    public static string Language_ko_KR => LocalizationManager.Localize("Language_ko_KR");

    /// <summary>
    /// Dutch
    /// </summary>
    public static string Language_nl_NL => LocalizationManager.Localize("Language_nl_NL");

    /// <summary>
    /// Polish
    /// </summary>
    public static string Language_pl_PL => LocalizationManager.Localize("Language_pl_PL");

    /// <summary>
    /// Portuguese-Brazil
    /// </summary>
    public static string Language_pt_BR => LocalizationManager.Localize("Language_pt_BR");

    /// <summary>
    /// Portuguese
    /// </summary>
    public static string Language_pt_PT => LocalizationManager.Localize("Language_pt_PT");

    /// <summary>
    /// Russian
    /// </summary>
    public static string Language_ru_RU => LocalizationManager.Localize("Language_ru_RU");

    /// <summary>
    /// Slovak
    /// </summary>
    public static string Language_sk_SK => LocalizationManager.Localize("Language_sk_SK");

    /// <summary>
    /// Thai
    /// </summary>
    public static string Language_th_TH => LocalizationManager.Localize("Language_th_TH");

    /// <summary>
    /// Turkish
    /// </summary>
    public static string Language_tr_TR => LocalizationManager.Localize("Language_tr_TR");

    /// <summary>
    /// Simplified Chinese
    /// </summary>
    public static string Language_zh_CN => LocalizationManager.Localize("Language_zh_CN");

    /// <summary>
    /// Traditional Chinese
    /// </summary>
    public static string Language_zh_TW => LocalizationManager.Localize("Language_zh_TW");

    /// <summary>
    /// Loading is not allowed
    /// </summary>
    public static string LoadNotAllowed => LocalizationManager.Localize("LoadNotAllowed");

    /// <summary>
    /// Log level
    /// </summary>
    public static string LogLevel => LocalizationManager.Localize("LogLevel");

    /// <summary>
    /// It is not recommended to change this option unless you need to adjust the log output level!
    /// </summary>
    public static string LogLevelDescription => LocalizationManager.Localize("LogLevelDescription");

    /// <summary>
    /// Added
    /// </summary>
    public static string LogMessageBox_Added => LocalizationManager.Localize("LogMessageBox_Added");

    /// <summary>
    /// Attention
    /// </summary>
    public static string LogMessageBox_Attention => LocalizationManager.Localize("LogMessageBox_Attention");

    /// <summary>
    /// Fixed
    /// </summary>
    public static string LogMessageBox_Fixed => LocalizationManager.Localize("LogMessageBox_Fixed");

    /// <summary>
    /// Optimized
    /// </summary>
    public static string LogMessageBox_Optimized => LocalizationManager.Localize("LogMessageBox_Optimized");

    /// <summary>
    /// Removed
    /// </summary>
    public static string LogMessageBox_Removed => LocalizationManager.Localize("LogMessageBox_Removed");

    /// <summary>
    /// Translation
    /// </summary>
    public static string LogMessageBox_Translation => LocalizationManager.Localize("LogMessageBox_Translation");

    /// <summary>
    /// Updated
    /// </summary>
    public static string LogMessageBox_Updated => LocalizationManager.Localize("LogMessageBox_Updated");

    /// <summary>
    /// Game Version Compatibility
    /// </summary>
    public static string MakeForCurrentGameVersion => LocalizationManager.Localize("MakeForCurrentGameVersion");

    /// <summary>
    /// Missing dependencies
    /// </summary>
    public static string MissingDependencies => LocalizationManager.Localize("MissingDependencies");

    /// <summary>
    /// Missing Harmony dependency! This mods will still load, but will not work as expected, please install Harmony dependency before using this mod.
    /// </summary>
    public static string MissingHarmonyDependency => LocalizationManager.Localize("MissingHarmonyDependency");

    /// <summary>
    /// Mod Compatibility
    /// </summary>
    public static string ModCompatibility => LocalizationManager.Localize("ModCompatibility");

    /// <summary>
    /// Mod Information
    /// </summary>
    public static string ModInfo => LocalizationManager.Localize("ModInfo");

    /// <summary>
    /// Mod Release Date
    /// </summary>
    public static string ModReleaseDate => LocalizationManager.Localize("ModReleaseDate");

    /// <summary>
    /// Mod Status
    /// </summary>
    public static string ModStatus => LocalizationManager.Localize("ModStatus");

    /// <summary>
    /// No
    /// </summary>
    public static string No => LocalizationManager.Localize("No");

    /// <summary>
    /// No incompatible mods detected.
    /// </summary>
    public static string NoIncompatibleModsDetected => LocalizationManager.Localize("NoIncompatibleModsDetected");

    /// <summary>
    /// No missing dependencies.
    /// </summary>
    public static string NoMissingDependencies => LocalizationManager.Localize("NoMissingDependencies");

    /// <summary>
    /// None
    /// </summary>
    public static string None => LocalizationManager.Localize("None");

    /// <summary>
    /// Normal
    /// </summary>
    public static string Normal => LocalizationManager.Localize("Normal");

    /// <summary>
    /// Current mod version was not created for the current game version.
    /// </summary>
    public static string NotMakeForCurrentGameVersion => LocalizationManager.Localize("NotMakeForCurrentGameVersion");

    /// <summary>
    /// OK
    /// </summary>
    public static string OK => LocalizationManager.Localize("OK");

    /// <summary>
    /// Only in game
    /// </summary>
    public static string OnlyInGame => LocalizationManager.Localize("OnlyInGame");

    /// <summary>
    /// Only in UUI
    /// </summary>
    public static string OnlyInUUI => LocalizationManager.Localize("OnlyInUUI");

    /// <summary>
    /// Press any key
    /// </summary>
    public static string PressAnyKey => LocalizationManager.Localize("PressAnyKey");

    /// <summary>
    /// Reset
    /// </summary>
    public static string Reset => LocalizationManager.Localize("Reset");

    /// <summary>
    /// Reset mod failed. It is recommended to send the log file to the developer.
    /// </summary>
    public static string ResetModFailed => LocalizationManager.Localize("ResetModFailed");

    /// <summary>
    /// Reset mod config
    /// </summary>
    public static string ResetModMajor => LocalizationManager.Localize("ResetModMajor");

    /// <summary>
    /// Attention! This option will reset all settings of this mod, and this operation is irreversible!
    /// </summary>
    public static string ResetModMinor => LocalizationManager.Localize("ResetModMinor");

    /// <summary>
    /// Reset mod succeeded.
    /// </summary>
    public static string ResetModSucceeded => LocalizationManager.Localize("ResetModSucceeded");

    /// <summary>
    /// Are you sure you want to reset the configuration of the mod?
    /// </summary>
    public static string ResetModWarning => LocalizationManager.Localize("ResetModWarning");

    /// <summary>
    /// Reset Tool Button Position
    /// </summary>
    public static string ResetToolButtonPosition => LocalizationManager.Localize("ResetToolButtonPosition");

    /// <summary>
    /// The incompatible mods has been handled, but the game has not been removed normally, it is recommended to restart the game.
    /// </summary>
    public static string RestartGame => LocalizationManager.Localize("RestartGame");

    /// <summary>
    /// Scroll the wheel to change, Shift X10, Ctrl X0.1
    /// </summary>
    public static string ScrollWheel => LocalizationManager.Localize("ScrollWheel");

    /// <summary>
    /// The game should be restarted.
    /// </summary>
    public static string ShouldRestartGame => LocalizationManager.Localize("ShouldRestartGame");

    /// <summary>
    /// STABLE
    /// </summary>
    public static string STABLE => LocalizationManager.Localize("STABLE");

    /// <summary>
    /// Steam mod page
    /// </summary>
    public static string SteamModPage => LocalizationManager.Localize("SteamModPage");

    /// <summary>
    /// Please subscribe and enable the following dependencies
    /// </summary>
    public static string SubscribeDependencies => LocalizationManager.Localize("SubscribeDependencies");

    /// <summary>
    /// Toggle Control Panel
    /// </summary>
    public static string ToggleControlPanel => LocalizationManager.Localize("ToggleControlPanel");

    /// <summary>
    /// Open or close the control panel.
    /// </summary>
    public static string ToggleControlPanelDescription => LocalizationManager.Localize("ToggleControlPanelDescription");

    /// <summary>
    /// Tool Button
    /// </summary>
    public static string ToolButton => LocalizationManager.Localize("ToolButton");

    /// <summary>
    /// Tool button display
    /// </summary>
    public static string ToolButtonDisplay => LocalizationManager.Localize("ToolButtonDisplay");

    /// <summary>
    /// Tool button position could not be reset. Reset it in-game.
    /// </summary>
    public static string ToolButtonPositionResetFailureMessage => LocalizationManager.Localize("ToolButtonPositionResetFailureMessage");

    /// <summary>
    /// Tool button reset successfully.
    /// </summary>
    public static string ToolButtonPositionResetSuccessMessage => LocalizationManager.Localize("ToolButtonPositionResetSuccessMessage");

    /// <summary>
    /// Translation Progress
    /// </summary>
    public static string TranslationProgress => LocalizationManager.Localize("TranslationProgress");

    /// <summary>
    /// Updated to CSLModsCommon {0}
    /// </summary>
    public static string UpdatedToCSLModsCommon(object arg0) => LocalizationManager.LocalizeFormat("UpdatedToCSLModsCommon", arg0);

    /// <summary>
    /// Updated to support game version {0}
    /// </summary>
    public static string UpdatedToGameVersion(object arg0) => LocalizationManager.LocalizeFormat("UpdatedToGameVersion", arg0);

    /// <summary>
    /// Use Game Language
    /// </summary>
    public static string UseGameLanguage => LocalizationManager.Localize("UseGameLanguage");

    /// <summary>
    /// Verbose
    /// </summary>
    public static string Verbose => LocalizationManager.Localize("Verbose");

    /// <summary>
    /// Version
    /// </summary>
    public static string Version => LocalizationManager.Localize("Version");

    /// <summary>
    /// Warn
    /// </summary>
    public static string Warn => LocalizationManager.Localize("Warn");

    /// <summary>
    /// Warning
    /// </summary>
    public static string Warning => LocalizationManager.Localize("Warning");

    /// <summary>
    /// Website
    /// </summary>
    public static string Website => LocalizationManager.Localize("Website");

    /// <summary>
    /// Yes
    /// </summary>
    public static string Yes => LocalizationManager.Localize("Yes");

}

