# -*- coding: utf-8 -*-
"""Romanian complete UI pack. python -c \"from lang_packs_all import emit; from lang_packs_ro import RO; emit('ro', RO)\""""
from __future__ import print_function

# Full pack generated for IPT4 Options UI
RO = {
"MOD_DESCRIPTION": "Transport public îmbunătățit: control linii, flotă, integrări și altele.",
"CURRENT_WEEK": "Săptămâna curentă",
"LAST_WEEK": "Săptămâna trecută",
"AVERAGE": "Medie",
"AVERAGE_TOOLTIP": "Media ultimelor {0} săptămâni.",
"CITY_SERVICE_PANEL_TITLE_STATION_STOPS": "Opriri stație",
"CITY_SERVICE_PANEL_TITLE_DEPOT_VEHICLES": "Vehicule depou",
"CITYSERVICE_ACCEPTINTERCITYBUSES": "Permite autobuze interurbane",
"CITYSERVICE_ACCEPTINTERCITYBUSES_TOOLTIP": "Permite autobuzelor interurbane să folosească această stație. Dezactivați pentru doar autobuze locale.",
"EXPLANATION_BUDGET_CONTROL": "Control buget: Numărul de vehicule este controlat de buget.",
"EXPLANATION_UNBUNCHING": "Anti-grupare: Jocul încearcă să creeze un spațiu între vehicule.",
"LINE_PANEL_STOPS": "Stații: {0}",
"LINE_PANEL_SPAWNTIMER": "Următorul vehicul în {0} secunde.",
"LINE_PANEL_DEPOT_WARNING": "<color #FF0000>Depoul selectat nu mai are vehicule.</color>",
"LINE_PANEL_BUDGET_CONTROL": "Control buget",
"LINE_PANEL_BUDGET_CONTROL_TOOLTIP": "Activează sau dezactivează controlul bugetului pentru această linie.",
"LINE_PANEL_UNBUNCHING_TOOLTIP": "Activează sau dezactivează anti-gruparea pentru această linie.\nAnti-gruparea este dezactivată dacă agresivitatea este setată la 0.",
"LINE_PANEL_DEPOT": "Depou:",
"LINE_PANEL_NO_DEPOT_FOUND": "Niciun depou găsit.",
"LINE_PANEL_DEPOT_MARKER_TOOLTIP": "Sari la depoul selectat.\nȚine Shift la clic pentru a mări și imaginea.",
"LINE_PANEL_SELECT_TYPES": "Selectează tipuri",
"LINE_PANEL_SELECT_TYPES_TOOLTIP": "Comută panoul „Selectează tipuri”.\nDacă butonul este dezactivat, trebuie să selectezi mai întâi un depou.",
"LINE_PANEL_LINE_STOPS": "Stațiile liniei",
"LINE_PANEL_LINE_VEHICLES": "Vehicule pe această linie",
"LINE_PANEL_ENQUEUED": "Vehicule în coadă",
"LINE_PANEL_TOTAL_WAITING_PEOPLE_TOOLTIP": "{0} pasageri așteaptă pe această linie.",
"LINE_PANEL_ADD_VEHICLE": "Adaugă vehicul",
"LINE_PANEL_ADD_VEHICLE_TOOLTIP": "Adaugă un vehicul nou pe linie.\nDacă butonul este dezactivat, depoul selectat nu mai are vehicule.",
"LINE_PANEL_REMOVE_VEHICLE": "Elimină vehicul",
"STOP_LIST_BOX_ROW_STOP": "Stație #{0}",
"STOP_LIST_BOX_ROW_TOOLTIP": "{0}\nPasageri care așteaptă: {1}\n\nClic dreapta pentru a sări la această stație.\nȚine Shift la clic pentru a mări și imaginea.",
"STOP_PANEL_SUGGESTED_NAMES_TOOLTIP": "Listă de nume de stații sugerate.",
"STOP_PANEL_REUSE_NAME_TOOLTIP": "Aplică acest nume tuturor celorlalte stații de la această stație/poziție.",
"STOP_PANEL_WAITING_PEOPLE": "Pasageri care așteaptă: {0}",
"COMMUTER_DESTINATION_PANEL_TITLE": "Destinație navetiști",
"COMMUTER_DESTINATION_HEADER": "Destinații de top:",
"COMMUTER_DESTINATION_NONE": "Niciun pasager nu așteaptă aici acum.",
"COMMUTER_DESTINATION_LOADING": "Se calculează...",
"COMMUTER_DESTINATION_BUTTON": "Destinații",
"COMMUTER_DESTINATION_BUTTON_TOOLTIP": "Arată unde merg pasagerii care așteaptă la această stație.",
"STOP_PANEL_BORED_TIMER": "Timp până la nerăbdare: <color #{0}>{1}</color>",
"STOP_PANEL_BORED_TIMER_TOOLTIP": "Pasagerii părăsesc stația când numărătoarea ajunge la zero.",
"STOP_PANEL_PASSENGERS_IN": "Pasageri urcați:",
"STOP_PANEL_PASSENGERS_IN_TOOLTIP": "Pasageri care urcă aici.",
"STOP_PANEL_PASSENGERS_OUT": "Pasageri coborâți:",
"STOP_PANEL_PASSENGERS_OUT_TOOLTIP": "Pasageri care coboară aici.",
"STOP_PANEL_PASSENGERS_TOTAL": "Total:",
"STOP_PANEL_PASSENGERS_TOTAL_TOOLTIP": "Total pasageri deserviți aici.",
"STOP_PANEL_UNBUNCHING_TOOLTIP": "Activează sau dezactivează anti-gruparea la această stație.\nAnti-gruparea este dezactivată dacă agresivitatea este setată la 0.",
"STOP_PANEL_UPDATE_CLOSE_STOPS": "Actualizează stațiile apropiate",
"STOP_PANEL_UPDATE_CLOSE_STOPS_TOOLTIP": "Setează starea anti-grupare pentru toate celelalte stații de la această stație/poziție.",
"STOP_PANEL_PREVIOUS": "Stația anterioară",
"STOP_PANEL_PREVIOUS_TOOLTIP": "Sari la stația anterioară.\nȚine Shift la clic pentru a mări și imaginea.",
"STOP_PANEL_DELETE_STOP": "Șterge stația",
"STOP_PANEL_DELETE_STOP_TOOLTIP": "Acest buton este activ în timp ce ții apăsat Alt.\nFolosește pe propria răspundere!!!",
"STOP_PANEL_NEXT": "Stația următoare",
"STOP_PANEL_NEXT_TOOLTIP": "Sari la stația următoare.\nȚine Shift la clic pentru a mări și imaginea.",
"STOP_BUTTON_TOOLTIP": "{0}\n\nClic pentru a sări la această stație.\nȚine Shift la clic pentru a mări și imaginea.\nȚine Alt la clic pentru a preveni deschiderea panoului de info stație.",
"SETTINGS_DELETE": "Șterge",
"SETTINGS_RESET": "Resetează",
"SETTINGS_TAB_GENERAL": "General",
"SETTINGS_ADVANCED_LINKS_GROUP": "Linkuri",
"SETTINGS_GITHUB_REPO": "Cod sursă pe GitHub",
"SETTINGS_TAB_AUTOLINE": "Linie auto",
"SETTINGS_TAB_STOPS": "Stații și gări",
"SETTINGS_TAB_UNBUNCHING": "Anti-grupare",
"SETTINGS_TAB_DELETE": "Șterge linii",
"SETTINGS_TAB_FLEET": "Flotă și programare",
"SETTINGS_TAB_BUDGET": "Buget și prețuri",
"SETTINGS_TAB_LINECOLORS": "Culori linii",
"SETTINGS": "Setări",
"SETTINGS_SPEED": "Afișează viteza în: ",
"SETTINGS_SPEED_TOOLTIP": "Alege unitatea pentru afișarea vitezei în interfață.",
"SETTINGS_GAMEPLAY_PROFILE": "Profil de joc",
"SETTINGS_GAMEPLAY_PROFILE_TOOLTIP": "Aplică un lot de setări dintr-o dată. Sigur (implicit) lasă totul oprit pentru compatibilitate maximă cu alte moduri. Vanilla potrivește jocul de bază. Recomandat activează doar nucleul IPT (control flotă buget, anti-grupare, intercity, file sub-clădiri, unstucker, selecție avansată stații, stații ridicate). Realist activează majoritatea integrărilor. Personalizat nu cascadă niciodată - tu gestionezi fiecare comutator.",
"SETTINGS_GAMEPLAY_PROFILE_CUSTOM": "Personalizat",
"SETTINGS_GAMEPLAY_PROFILE_SAFE": "Sigur (totul oprit)",
"SETTINGS_GAMEPLAY_PROFILE_VANILLA": "Vanilla",
"SETTINGS_GAMEPLAY_PROFILE_RECOMMENDED": "Recomandat (nucleu IPT)",
"SETTINGS_GAMEPLAY_PROFILE_REALISTIC": "Realist",
"SETTINGS_SPEED_KPH": "km/h",
"SETTINGS_SPEED_MPH": "mph",
"SETTINGS_WALKING_SPEED": "Viteză mers/ciclism: ",
"SETTINGS_WALKING_SPEED_TOOLTIP": "Standard: vitezele jocului de bază.\nRealist: reduce viteza de mers la valori realiste pe vârstă.\nRealist reduce și viteza de ciclism cu DLC After Dark.",
"SETTINGS_WALKING_SPEED_MODE_VANILLA": "Standard",
"SETTINGS_WALKING_SPEED_MODE_REALISTIC": "Realist",
"SETTINGS_BBSP": "Poziție mai bună stație de autobuz: ",
"SETTINGS_BBSP_TOOLTIP": "Dezactivat: fără ajustare de poziție.\nActivat: autobuzele opresc în fața stației, nu pe mijloc.",
"SETTINGS_BBSP_MODE_DISABLED": "Dezactivat",
"SETTINGS_BBSP_MODE_ORIGINAL": "Activat",
"SETTINGS_BBSP_MODE_UPDATED": "Folosește logică experimentală",
"SETTINGS_BUDGET": "Buget",
"SETTINGS_ENABLE_BUDGET_CONTROL": "Control buget linie:",
"SETTINGS_BUDGET_CONTROL_DISABLED": "Dezactivat",
"SETTINGS_BUDGET_CONTROL_ENABLED": "Activat",
"SETTINGS_BUDGET_CONTROL_TOOLTIP": "Când este activat, numărul de vehicule pe liniile de transport este controlat de buget; actualizează toate liniile existente și golește vehiculele din coadă.",
"SETTINGS_BUDGET_TICKET_PRICES": "Personalizare preț bilete:",
"SETTINGS_BUDGET_TICKET_PRICES_DISABLED": "Dezactivat",
"SETTINGS_BUDGET_TICKET_PRICES_ENABLED": "Activat",
"SETTINGS_BUDGET_TICKET_PRICES_TOOLTIP": "Când este activat, adaugă o filă nouă în panoul Economie cu glisoare pentru prețurile biletelor pe tip de transport.",
"SETTINGS_AUTO_LINE_BUDGET": "Dimensionare automată flotă:",
"SETTINGS_AUTO_LINE_BUDGET_DISABLED": "Dezactivat",
"SETTINGS_AUTO_LINE_BUDGET_ENABLED": "Activat",
"SETTINGS_AUTO_LINE_BUDGET_TOOLTIP": "Când este activat, liniile în modul Buget își ajustează automat numărul de vehicule după cererea reală de pasageri, nu după glisorul vanilla. Liniile setate pe Manual nu sunt niciodată atinse.",
"SETTINGS_AUTO_LINE": "Linie auto",
"SETTINGS_AUTOSHOW_LINE_INFO": "Deschide automat panoul info linie",
"SETTINGS_AUTOSHOW_LINE_INFO_TOOLTIP": "Afișează automat panoul info linie după ce se creează o linie nouă.",
"AUTOLINECOLOR_STRATEGY_DISABLED": "Dezactivat",
"AUTOLINECOLOR_STRATEGY_RANDOM_HUE": "Nuanță aleatoare",
"AUTOLINECOLOR_STRATEGY_RANDOM_COLOR": "Culoare aleatoare",
"AUTOLINECOLOR_STRATEGY_CATEGORISED": "Categorisită",
"AUTOLINECOLOR_STRATEGY_NAMED": "Culori denumite",
"AUTOLINECOLOR_NAMING_DISABLED": "Dezactivat",
"AUTOLINECOLOR_NAMING_DISTRICTS": "Districte",
"AUTOLINECOLOR_NAMING_LONDON": "Londra",
"AUTOLINECOLOR_NAMING_ROADS": "Străzi",
"AUTOLINECOLOR_NAMING_COLORS": "Culori denumite",
"AUTOLINECOLOR_COLOR_STRATEGY": "Strategie culoare:",
"AUTOLINECOLOR_COLOR_STRATEGY_TOOLTIP": "Cum se alocă culorile liniilor noi:\n'Nuanță aleatoare' = aceeași saturație/luminozitate, nuanțe diferite;\n'Culoare aleatoare' = RGB complet aleator;\n'Categorisită' = culori după tip de vehicul;\n'Culori denumite' = paletă predefinită.",
"AUTOLINECOLOR_NAMING_STRATEGY": "Strategie denumire:",
"AUTOLINECOLOR_NAMING_STRATEGY_TOOLTIP": "Cum se alocă numele liniilor noi:\n'Niciuna' = fără auto-denumire;\n'Districte' = pe baza districtelor deservite;\n'Londra' = rute numerotate (stil London Buses);\n'Străzi' = pe baza numelor de străzi;\n'Culori denumite' = pe baza numelor de culori.",
"AUTOLINECOLOR_MIN_COLOR_DIFF": "Diferență minimă de culoare (%):",
"AUTOLINECOLOR_MIN_COLOR_DIFF_TOOLTIP": "Procentul minim de diferență de culoare la alegerea culorilor aleatoare.",
"AUTOLINECOLOR_MAX_COLOR_PICK": "Încercări maxime:",
"AUTOLINECOLOR_MAX_COLOR_PICK_TOOLTIP": "Numărul maxim de încercări pentru a alege o culoare distinctă.",
"SETTINGS_UI": "Setări UI",
"SETTINGS_VEHICLE_EDITOR_POSITION": "Poziție editor vehicule: ",
"SETTINGS_VEHICLE_EDITOR_POSITION_TOOLTIP": "Alege dacă panoul editorului de vehicule apare jos sau în dreapta ecranului.",
"SETTINGS_VEHICLE_EDITOR_POSITION_BOTTOM": "Jos",
"SETTINGS_VEHICLE_EDITOR_POSITION_RIGHT": "Dreapta",
"SETTINGS_VEHICLE_EDITOR_HIDE": "Ascunde editorul de vehicule",
"SETTINGS_VEHICLE_EDITOR_HIDE_TOOLTIP": "Ascunde editorul de vehicule din panourile de vehicule.",
"SETTINGS_STOPS": "Stații transport public",
"SETTINGS_STOPSANDSTATIONS_DESCRIPTION": "Câți pasageri din fiecare tip de transport pot aștepta la o stație înainte de a fi considerată plină. Valori mai mari reduc plângerile de aglomerație la stațiile aglomerate, cu costul unei cozi mai puțin realiste.",
"SETTINGS_STOPSANDSTATIONS_RESET_TOOLTIP": "Resetează toate plafoanele de pasageri de mai sus la valorile implicite.",
"SETTINGS_ENABLE_STOPS_AND_STATIONS": "Activează stații și gări",
"SETTINGS_ENABLE_STOPS_AND_STATIONS_TOOLTIP": "Ajustează numărul maxim de cetățeni care pot aștepta transportul public la stații și gări. Configurează în fila Stații.",
"SETTINGS_STOPSANDSTATIONS_ENABLE": "Activează stații și gări",
"SETTINGS_STOPSANDSTATIONS_ENABLE_TOOLTIP": "Activează sau dezactivează aplicarea limitelor de pasageri la stații.",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HEADER": "Pasageri maximi care așteaptă la o stație de linie:",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS": "Autobuz de linie",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS_TOOLTIP": "Pasageri maximi care așteaptă la o stație de autobuz de linie",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS": "Troleibuz",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS_TOOLTIP": "Pasageri maximi care așteaptă la o stație de troleibuz",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS": "Autobuz de evacuare",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS_TOOLTIP": "Pasageri maximi care așteaptă la o stație de autobuz de evacuare",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS": "Autobuz turistic",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS_TOOLTIP": "Pasageri maximi care așteaptă la o stație de autobuz turistic",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM": "Tramvai",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM_TOOLTIP": "Pasageri maximi care așteaptă la o stație de tramvai",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO": "Metrou",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO_TOOLTIP": "Pasageri maximi care așteaptă la o stație de metrou",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN": "Tren",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN_TOOLTIP": "Pasageri maximi care așteaptă la o gară",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL": "Monorail",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL_TOOLTIP": "Pasageri maximi care așteaptă la o stație monorail",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP": "Navă",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP_TOOLTIP": "Pasageri maximi care așteaptă la un port de marfă",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY": "Feribot",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY_TOOLTIP": "Pasageri maximi care așteaptă la o stație de feribot",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE": "Avion",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE_TOOLTIP": "Pasageri maximi care așteaptă la un terminal de avion",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR": "Telecabină",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR_TOOLTIP": "Pasageri maximi care așteaptă la o stație de telecabină",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON": "Balon cu aer cald",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON_TOOLTIP": "Pasageri maximi care așteaptă la o stație de balon",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER": "Elicopter",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER_TOOLTIP": "Pasageri maximi care așteaptă la o stație de elicopter",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP": "Dirijabil",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP_TOOLTIP": "Pasageri maximi care așteaptă la o stație de dirijabil",
"SETTINGS_UNBUNCHING": "Anti-grupare",
"SETTINGS_UNBUNCHING_AGGRESSION": "Agresivitate anti-grupare:",
"SETTINGS_UNBUNCHING_AGGRESSION_TOOLTIP": "Cât de puternic trebuie să acționeze anti-gruparea?\nValori posibile: 0–52. Valoarea 0 dezactivează anti-gruparea.\nValorile mai mari afectează puternic traficul și pot face vehiculele să dispară.",
"SETTINGS_VEHICLE_COUNT": "Vehicule pe linii noi:",
"SETTINGS_VEHICLE_COUNT_TOOLTIP": "Numărul de vehicule adăugate automat pe liniile noi când controlul bugetului pe linie este oprit.",
"SETTINGS_SPAWN_TIME_INTERVAL": "Interval de apariție:",
"SETTINGS_SPAWN_TIME_INTERVAL_TOOLTIP": "Timp în secunde între aparițiile de vehicule.",
"SETTINGS_UNBUNCHING_RESET_BUTTON_TOOLTIP": "Resetează toate glisoarele la valorile implicite.",
"UNBUNCHING_ENABLED": "Anti-grupare vehicule",
"UNBUNCHING_DISABLED": "Anti-gruparea este dezactivată.",
"UNBUNCHING_TARGET_GAP": "Spațiu țintă: {0}",
"SETTINGS_EBS_GROUP_BUS": "Servicii autobuz expres",
"SETTINGS_EBS_GROUP_TRAM": "Servicii tramvai expres",
"SETTINGS_EBS_DROPDOWN_UNBUNCHING_MODE": "Autobuz expres: ",
"SETTINGS_EBS_TOOLTIP_UNBUNCHING_MODE": "'Dezactivat' = Autobuzele folosesc setările anti-grupare de mai sus.\n'Prudent' = Oprește scurt, verifică pasagerii, poate pleca gol.\n'Agresiv' = Sare peste stații dacă nu așteaptă nimeni.",
"SETTINGS_EBS_ENABLE_SELFBAL": "Activează auto-echilibrarea serviciului",
"SETTINGS_EBS_DESC_SELFBAL": "Permite serviciului de autobuz expres să redistribuie vehiculele pe linie pentru a favoriza segmentele mai aglomerate și a reduce timpul de așteptare.",
"SETTINGS_EBS_TOOLTIP_SELFBAL": "Analizează segmentele liniei și poate redistribui vehicule pe segmente mai aglomerate sau capete de linie pentru un serviciu mai echilibrat.\nDeciziile sunt probabilistice și depind de numărul de pasageri și șansele de redistribuire.",
"SETTINGS_EBS_ENABLE_SELFBAL_TARGETMID": "Activează auto-echilibrarea la stații de mijloc de linie",
"SETTINGS_EBS_DESC_SELFBAL_TARGETMID": "Permite auto-echilibrării să aleagă o stație aglomerată de pe mijlocul liniei, nu doar un cap de linie, la redistribuire.",
"SETTINGS_EBS_TOOLTIP_SELFBAL_TARGETMID": "Permite auto-echilibratorului să redistribuie vehicule la o stație aglomerată de pe mijlocul liniei (în loc de cap de linie).\nConsiderat doar când cea mai aglomerată stație are peste 30 de pasageri, apoi ales cu ~50% probabilitate și supus șanselor generale de redistribuire.",
"SETTINGS_EBS_ENABLE_MINIBUS": "Activează modul microbuz",
"SETTINGS_EBS_DESC_MINIBUS": "Face ca autobuzele mai mici să plece mai devreme când urcă sau coboară doar câțiva pasageri.",
"SETTINGS_EBS_TOOLTIP_MINIBUS": "Autobuzele cu capacitate ≤20 pot pleca mai devreme când pasagerii care urcă + coboară ≤5.",
"SETTINGS_EBS_DROPDOWN_TRAM_UNBUNCHING_MODE": "Tramvai expres: ",
"SETTINGS_EBS_TOOLTIP_TRAM_UNBUNCHING": "'Dezactivat' = Tramvaiele folosesc setările anti-grupare de mai sus.\n'Light rail' = Oprește la fiecare stație, așteaptă mereu timerul complet (disciplină strictă).\n'Tramvai adevărat' = Oprește doar când pasageri urcă/coboară.",
"SETTINGS_EBS_MODE_NONE": "Dezactivat",
"SETTINGS_EBS_MODE_AGGRESSIVE": "Agresiv",
"SETTINGS_EBS_MODE_PRUDENTIAL": "Prudent",
"SETTINGS_EBS_TRAM_MODE_LIGHT_RAIL": "Mod light rail",
"SETTINGS_EBS_TRAM_MODE_NONE": "Dezactivat",
"SETTINGS_EBS_TRAM_MODE_TRAM": "Mod tramvai adevărat",
"SETTINGS_PTU_GROUP": "Deblocare transport public",
"SETTINGS_PTU_ENABLE": "Elimină pasagerii blocați",
"SETTINGS_PTU_TOOLTIP": "Elimină automat pasagerii blocați la urcare, permițând vehiculului să plece normal și prevenind plecările înghețate.",
"SETTINGS_LINE_DELETION_TOOL": "Instrument ștergere linii",
"SETTINGS_LINE_DELETION_TOOL_DESCRIPTION": "Bifează tipurile de transport de mai jos, apoi apasă Șterge pentru a elimina toate liniile de acele tipuri din orașul curent. Selecția este temporară - începe mereu nebifată și se golește după ștergere; nu se salvează ca setare.",
"SETTINGS_LINE_DELETION_TOOL_BUTTON_TOOLTIP": "Șterge toate liniile tipurilor selectate. Funcționează doar cu orașul încărcat.",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_TITLE": "CONFIRMĂ ȘTERGEREA LINIILOR",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_MSG": "Ești pe cale să ștergi toate liniile.\nDorești să continui?",
"SETTINGS_DELETE_BUS_TOOLTIP": "Șterge toate liniile de autobuz obișnuite.",
"SETTINGS_DELETE_SIGHTSEEING_BUS_LABEL": "Autobuze turistice",
"SETTINGS_DELETE_SIGHTSEEING_BUS_TOOLTIP": "Șterge toate liniile de autobuz turistic.",
"SETTINGS_DELETE_TRAM_TOOLTIP": "Șterge toate liniile de tramvai.",
"SETTINGS_DELETE_TROLLEYBUS_TOOLTIP": "Șterge toate liniile de troleibuz.",
"SETTINGS_DELETE_TRAIN_TOOLTIP": "Șterge toate liniile de tren.",
"SETTINGS_DELETE_METRO_TOOLTIP": "Șterge toate liniile de metrou subteran.",
"SETTINGS_DELETE_MONORAIL_TOOLTIP": "Șterge toate liniile monorail.",
"SETTINGS_DELETE_FERRY_LABEL": "Feriboturi",
"SETTINGS_DELETE_SHIP_TOOLTIP": "Șterge toate liniile de feribot.",
"SETTINGS_DELETE_HELICOPTER_LABEL": "Elicoptere",
"SETTINGS_DELETE_HELICOPTER_TOOLTIP": "Șterge toate liniile de elicopter.",
"SETTINGS_DELETE_BLIMP_LABEL": "Dirijabile",
"SETTINGS_DELETE_BLIMP_TOOLTIP": "Șterge toate liniile de dirijabil.",
"VEHICLE_EDITOR_TITLE": "Editor vehicule",
"VEHICLE_EDITOR_SUB_TITLE": "{0} vehicule",
"VEHICLE_EDITOR_CAPACITY": "Capacitate pasageri",
"VEHICLE_EDITOR_CAPACITY_TAXI": "Capacitate deplasare",
"VEHICLE_EDITOR_CAPACITY_TAXI_TOOLTIP": "Număr de pasageri pe tură de lucru.",
"VEHICLE_EDITOR_MAINTENANCE": "Cost întreținere",
"VEHICLE_EDITOR_MAX_SPEED": "Viteză maximă",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS": "Motor de tren la ambele capete",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS_TOOLTIP": "Activează sau dezactivează motoarele de tren la ambele capete.",
"VEHICLE_EDITOR_APPLY": "Aplică",
"VEHICLE_EDITOR_DEFAULT": "Implicit",
"VEHICLE_LIST_BOX_ROW_TOOLTIP1": "Clic dreapta pentru a urmări acest vehicul.\nȚine Shift la clic pentru a mări și imaginea.",
"VEHICLE_LIST_BOX_ROW_TOOLTIP2": "Shift + clic pentru a pune acest vehicul în coadă.",
"VEHICLE_PANEL_EDIT_TYPE": "Editează tipul de vehicul",
"VEHICLE_PANEL_EDIT_TYPE_TOOLTIP": "Editează acest tip de vehicul cu editorul de vehicule.",
"VEHICLE_PANEL_STATUS_NEXT_STOP": "Următoarea stație:",
"VEHICLE_PANEL_STATUS_UNBUNCHING": "Anti-grupare în curs",
"VEHICLE_PANEL_LAST_STOP_EXCHANGE": "Schimb de pasageri la ultima stație: <color #FF0000>-{0}</color> | <color #00FF00>+{1}</color>",
"VEHICLE_PANEL_PASSENGERS": "Pasageri:",
"VEHICLE_PANEL_EARNINGS": "Venituri:",
"VEHICLE_PANEL_EARNINGS_TOOLTIP": "Rezultatul vânzărilor de bilete minus costul de întreținere al vehiculului.",
"VEHICLE_PANEL_PREVIOUS": "Vehiculul anterior",
"VEHICLE_PANEL_PREVIOUS_TOOLTIP": "Sari la vehiculul anterior.\nȚine Shift la clic pentru a mări și imaginea.",
"VEHICLE_PANEL_REMOVE_VEHICLE": "Elimină vehicul",
"VEHICLE_PANEL_NEXT": "Vehiculul următor",
"VEHICLE_PANEL_NEXT_TOOLTIP": "Sari la vehiculul următor.\nȚine Shift la clic pentru a mări și imaginea.",
"VEHICLE_SELECTION_CAPACITY": "Capacitate",
"VEHICLE_SELECTION_ADD_VEHICLE": "Adaugă acest vehicul pe lista de vehicule permise",
"VEHICLE_SELECTION_ADD_ALL": "Adaugă toate vehiculele eligibile pe lista de vehicule permise",
"VEHICLE_SELECTION_REMOVE_VEHICLE": "Elimină acest vehicul din lista de vehicule permise",
"VEHICLE_SELECTION_REMOVE_ALL": "Elimină toate vehiculele din lista de vehicule permise",
"VEHICLE_SELECTION_AVAILABLE_VEHICLES": "Vehicule disponibile",
"VEHICLE_SELECTION_SELECTED_VEHICLES": "Vehicule selectate",
"VEHICLE_SELECTION_ANY_VEHICLE": "Orice vehicul",
"VEHICLE_BUTTON_TOOLTIP": "{0}\n\nClic pentru a sări la acest vehicul.\nȚine Shift la clic pentru a mări și imaginea.\nȚine Alt la clic pentru a preveni deschiderea panoului de info vehicul.",
"TRANSPORT_LINE_VEHICLECOUNT": "Număr vehicule: {0}",
"FLIGHT_TRACKER_NAME": "Urmărire zboruri",
"FLIGHT_STATUS_NONE": "Niciunul",
"FLIGHT_STATUS_INCOMING": "Sosire",
"FLIGHT_STATUS_LANDED": "Aterizat",
"FLIGHT_STATUS_AT_GATE": "La poartă",
"FLIGHT_STATUS_DEPARTED": "Plecat",
"TICKET_PRICE_TAXI_KILOMETER": "Preț taxi pe kilometru: ",
"TICKET_PRICE_TAXI_MILE": "Preț taxi pe milă: ",
"TICKET_PRICE_BUS": "Preț bilet autobuz: ",
"TICKET_PRICE_INTERCITY_BUS": "Preț bilet autobuz interurban: ",
"TICKET_PRICE_METRO": "Preț bilet metrou: ",
"TICKET_PRICE_TRAIN": "Preț bilet tren: ",
"TICKET_PRICE_TRAM": "Preț bilet tramvai: ",
"TICKET_PRICE_MONORAIL": "Preț bilet monorail: ",
"TICKET_PRICE_SHIP": "Preț bilet navă: ",
"TICKET_PRICE_FERRY": "Preț bilet feribot: ",
"TICKET_PRICE_PLANE": "Preț bilet avion: ",
"TICKET_PRICE_CABLECAR": "Preț bilet telecabină: ",
"TICKET_PRICE_SIGHTSEEING_BUS": "Preț bilet autobuz turistic: ",
"TICKET_PRICE_TROLLEYBUS": "Preț bilet troleibuz: ",
"TICKET_PRICE_BLIMP": "Preț bilet dirijabil: ",
"TICKET_PRICE_HELICOPTER": "Preț bilet elicopter: ",
"ECONOMY_TAB_TICKET_PRICES": "Prețuri bilete",
"ECONOMY_TAB_TICKET_PRICES_TOOLTIP_PASSENGER_COUNT": "Numărul total actual de pasageri pentru acest tip de transport.",
"WHATSNEW_3_0_0_1": "Actualizat pentru Race Day; acum compatibil cu More Vehicles Renewed.",
"WHATSNEW_3_0_0_2": "Următoarele moduri au fost integrate în IPT3:\n • Advanced Stop Selection Revisited\n • Auto Line Color Redux\n • Better Bus Stop Position\n • Better Train Boarding\n • Elevated Stops Enabler Revisited  \n • Express Bus Services\n • Flight Tracker\n • Intercity Bus Control\n • Mileage Taxi Services\n • Public Transport Unstucker\n • Realistic Walking Speed\n • Stops and Stations\n • Ticket Price Customizer",
"WHATSNEW_3_0_1": "Public Transport Unstucker este acum integrat în IPT3.\nVezi versiunea 3.0 pentru toate celelalte moduri integrate. Dezabonează-te de la originale pentru a evita conflictele.",
"SETTINGS_TAB_TRAINDISPLAY": "Afișaj tren",
"SETTINGS_TAB_INTEGRATIONS": "Integrări",
"SETTINGS_TRAINDISPLAY_GROUP": "Suprapunere afișaj tren",
"SETTINGS_TRAINDISPLAY_GROUP_DESCRIPTION": "Configurează suprapunerea integrată afișată când urmărești vehicule de transport suportate.",
"SETTINGS_TRAINDISPLAY_ENABLE": "Activează afișajul trenului",
"SETTINGS_TRAINDISPLAY_ENABLE_TOOLTIP": "Pornește sau oprește suprapunerea integrată de afișaj tren.",
"SETTINGS_TRAINDISPLAY_MODE_DISABLED": "Dezactivat",
"SETTINGS_TRAINDISPLAY_MODE_ENABLED": "Activat",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION": "Poziție suprapunere:",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION_TOOLTIP": "Alege unde apare suprapunerea pe ecran.",
"SETTINGS_TRAINDISPLAY_POS_TOPLEFT": "Stânga sus",
"SETTINGS_TRAINDISPLAY_POS_TOPRIGHT": "Dreapta sus",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMLEFT": "Stânga jos",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMRIGHT": "Dreapta jos",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE": "Scală suprapunere:",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE_TOOLTIP": "Scalează dimensiunea suprapunerii.",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY": "Opacitate suprapunere:",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY_TOOLTIP": "Ajustează cât de transparentă este suprapunerea.",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL": "Interval de actualizare:",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL_TOOLTIP": "Cât de des se reîmprospătează suprapunerea când urmărești un vehicul.",
"SETTINGS_TRAINDISPLAY_SHOW_LINE": "Arată numele liniei",
"SETTINGS_TRAINDISPLAY_SHOW_LINE_TOOLTIP": "Include numele liniei în suprapunere.",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION": "Arată destinația",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION_TOOLTIP": "Include destinația în suprapunere.",
"SETTINGS_TRAINDISPLAY_SHOW_STATE": "Arată starea",
"SETTINGS_TRAINDISPLAY_SHOW_STATE_TOOLTIP": "Include starea vehiculului în suprapunere.",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING": "Doar la urmărire",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING_TOOLTIP": "Ascunde suprapunerea dacă camera nu urmărește efectiv un vehicul suportat.",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY": "Doar în camera first-person",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY_TOOLTIP": "Arată suprapunerea doar cu un mod de cameră first-person (ex. First Person Camera - Continued). Dacă e oprit, apare când urmărești un vehicul suportat în orice mod de cameră.",
"SETTINGS_TRAINDISPLAY_THEME": "Temă de culoare:",
"SETTINGS_TRAINDISPLAY_THEME_TOOLTIP": "Alege culorile de fundal/text ale suprapunerii.",
"SETTINGS_TRAINDISPLAY_THEME_SIMPLE": "Simplu",
"SETTINGS_TRAINDISPLAY_THEME_DARK": "Întunecat",
"SETTINGS_TRAINDISPLAY_THEME_LIGHT": "Luminos",
"SETTINGS_TRAINDISPLAY_THEME_ORIGINAL": "Original",
"SETTINGS_TRAINDISPLAY_THEME_BLUE": "Albastru",
"SETTINGS_TRAINDISPLAY_THEME_GREEN": "Verde",
"SETTINGS_TRAINDISPLAY_THEME_AMBER": "Chihlimbar",
"COPY_TIP": "Copiază setările acestei linii.",
"PASTE_TIP": "Lipește setările de linie copiate.",
"COPY_BUILDING_TIP": "Copiază aceste setări pe toate liniile care deservesc această clădire.",
"COPY_DISTRICT_TIP": "Copiază aceste setări pe toate liniile din acest district.",
"SETTINGS_INTEGRATIONS_GROUP": "Suplimente integrate",
"SETTINGS_INTERCITY_BUS_ENABLE": "Activează controlul autobuzelor interurbane",
"SETTINGS_INTERCITY_BUS_ENABLE_TOOLTIP": "Activează stratul de compatibilitate integrat pentru controlul autobuzelor interurbane și patch-urile de stații.",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE": "Activează selecția avansată a stațiilor",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE_TOOLTIP": "Permite plasarea stațiilor pe peroane/linii alternative ale gărilor multi-linie (ține tasta de mod alternativ la plasare). Intră în vigoare la următoarea încărcare a nivelului.",
"SETTINGS_BETTERBOARDING_ENABLE": "Activează urcare mai bună",
"SETTINGS_BETTERBOARDING_ENABLE_TOOLTIP": "Îmbunătățește deciziile de urcare astfel încât pasagerii preferă vehiculul care le servește destinația. Intră în vigoare la următoarea încărcare a nivelului.",
"SETTINGS_MILEAGETAXI_ENABLE": "Activează taxi pe kilometraj",
"SETTINGS_MILEAGETAXI_ENABLE_TOOLTIP": "Taxează taxiul după distanța parcursă în loc de tarif fix, astfel că drumurile mai lungi aduc mai mult. Necesită DLC After Dark. Intră în vigoare la următoarea încărcare a nivelului.",
"SETTINGS_ELEVATEDSTOPS_ENABLE": "Activează stații ridicate",
"SETTINGS_ELEVATEDSTOPS_ENABLE_TOOLTIP": "Permite stații de transport public pe drumuri/poduri ridicate și păstrează iluminatul stradal pe acele segmente. Intră în vigoare la următoarea încărcare a nivelului.",
"SETTINGS_INTERCITY_BUS_CAPACITY": "Capacitate terminal interurban",
"SETTINGS_INTERCITY_BUS_CAPACITY_TOOLTIP": "Câte vehicule poate ține odată un terminal de autobuz interurban.",
"SETTINGS_TRAM_DEPOT_CAPACITY": "Capacitate depou tramvai",
"SETTINGS_TRAM_DEPOT_CAPACITY_TOOLTIP": "Vanilla setează fiecare depou de tramvai la un plafon practic nelimitat de 100.000 de vehicule. Realist și Intermediar aplică un plafon fix moderat; Dezactivat păstrează comportamentul existent.",
"SETTINGS_TAXI_DEPOT_CAPACITY": "Capacitate depou taxi",
"SETTINGS_TAXI_DEPOT_CAPACITY_TOOLTIP": "Vanilla setează fiecare depou de taxi la un plafon practic nelimitat de 100.000 de vehicule. Realist și Intermediar aplică un plafon fix moderat; Dezactivat păstrează comportamentul existent.",
"SETTINGS_BUS_DEPOT_CAPACITY": "Capacitate depou autobuz",
"SETTINGS_BUS_DEPOT_CAPACITY_TOOLTIP": "Vanilla setează fiecare depou de autobuz (obișnuit, biocombustibil și garaje turistice) la un plafon practic nelimitat de 100.000 de vehicule. Realist și Intermediar aplică un plafon fix moderat; Dezactivat păstrează comportamentul existent.",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY": "Capacitate depou troleibuz",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY_TOOLTIP": "Vanilla setează fiecare depou de troleibuz la un plafon practic nelimitat de 100.000 de vehicule. Realist și Intermediar aplică un plafon fix moderat; Dezactivat păstrează comportamentul existent.",
"SETTINGS_FERRY_DEPOT_CAPACITY": "Capacitate depou feribot",
"SETTINGS_FERRY_DEPOT_CAPACITY_TOOLTIP": "Vanilla setează fiecare depou de feribot la un plafon practic nelimitat de 100.000 de vehicule. Realist și Intermediar aplică un plafon fix moderat; Dezactivat păstrează comportamentul existent.",
"SETTINGS_DEPOT_CAPACITY_DISABLED": "Dezactivat (fără plafon)",
"SETTINGS_DEPOT_CAPACITY_INTERMEDIATE": "Intermediar",
"SETTINGS_DEPOT_CAPACITY_REALISTIC": "Realist",
"SETTINGS_FLIGHTTRACKER_ENABLE": "Activează urmărirea zborurilor",
"SETTINGS_FLIGHTTRACKER_ENABLE_TOOLTIP": "Activează patch-urile integrate de urmărire a zborurilor și suportul UI.",
"SETTINGS_SUBBUILDINGSTABS_ENABLE": "Activează filele sub-clădiri",
"SETTINGS_SUBBUILDINGSTABS_ENABLE_TOOLTIP": "Afișează o bandă de file pe panoul info al unei clădiri când are sub-clădiri (ex. un aeroport cu stație de metrou încorporată), permițând comutarea între ele.",
"SETTINGS_TAXISTANDFIX_ENABLE": "Activează corecția stațiilor de taxi",
"SETTINGS_TAXISTANDFIX_ENABLE_TOOLTIP": "Trimite taxiurile inactive spre cea mai apropiată stație de taxi în loc să le lase să umble la întâmplare. Necesită DLC After Dark.",
"SETTINGS_SHAREDSTOPENABLER_ENABLE": "Activează stațiile partajate",
"SETTINGS_SHAREDSTOPENABLER_ENABLE_TOOLTIP": "Permite mai mult de un tip de transport (autobuz, tramvai, troleibuz) să oprească pe același segment de drum. Oprit implicit - vezi GitHub-ul modului pentru ce lasă afară această versiune redusă.",
"SETTINGS_COMMUTERDESTINATION_ENABLE": "Activează destinația navetiștilor (redesign în așteptare)",
"SETTINGS_COMMUTERDESTINATION_ENABLE_TOOLTIP": "Temporar indisponibil: panoul anterior duplica UI-ul de info stație și este forțat oprit până la un redesign. Caseta nu îl poate reactiva.",
"SETTINGS_OOC_ENABLE": "Conexiuni exterioare optimizate",
"SETTINGS_OOC_ENABLE_TOOLTIP": "Trenurile, avioanele și navele de marfă așteaptă mai mult o încărcătură mai plină înainte de a pleca la conexiunile exterioare.",
"SETTINGS_OOC_WAIT_MULTIPLIER": "Multiplicator de așteptare",
"SETTINGS_OOC_WAIT_MULTIPLIER_TOOLTIP": "Cât de mult mai mult decât vanilla se așteaptă o încărcătură mai plină. Valori mai mari înseamnă mai puține, dar mai pline curse.",
"SETTINGS_OOC_PASSENGER_SCOPE": "Domeniul așteptării pasagerilor",
"SETTINGS_OOC_PASSENGER_SCOPE_TOOLTIP": "Unde se aplică multiplicatorul de mai sus cetățenilor care așteaptă transportul public. Doar conexiuni exterioare afectează doar pe cei de la o conexiune exterioară; la nivel de oraș încetinește și așteptarea internă obișnuită pentru fiecare cetățean (potrivește comportamentul real al modului sursă).",
"SETTINGS_OOC_PASSENGER_SCOPE_OUTSIDE": "Doar conexiuni exterioare",
"SETTINGS_OOC_PASSENGER_SCOPE_CITYWIDE": "La nivel de oraș",
"SETTINGS_OOC_PASSENGER_SCOPE_DISABLED": "Dezactivat (vanilla)",
"SETTINGS_OOC_DISABLE_DUMMY": "Dezactivează traficul decorativ de tranzit",
"SETTINGS_OOC_DISABLE_DUMMY_ROAD": "Dezactivează traficul rutier decorativ",
"SETTINGS_OOC_DISABLE_DUMMY_TRAIN": "Dezactivează traficul feroviar decorativ",
"SETTINGS_OOC_DISABLE_DUMMY_PLANE": "Dezactivează traficul aerian decorativ",
"SETTINGS_OOC_DISABLE_DUMMY_SHIP": "Dezactivează traficul naval decorativ",
"SETTINGS_OOC_DISABLE_DUMMY_TOOLTIP": "Conexiunile exterioare genereză în mod normal trafic decorativ extra care nu intră sau iese cu adevărat din oraș, doar pentru atmosferă. Dezactivarea îl elimină fără a afecta fluxul real de import/export/pasageri.",
"SETTINGS_UOC_ENABLE": "Conexiuni exterioare nelimitate",
"SETTINGS_UOC_ENABLE_TOOLTIP": "Elimină limita vanilla de 4 conexiuni pentru drumuri, căi ferate, rute navale și aeriene, și leagă retrospectiv liniile de transport când se construiește o conexiune nouă lângă o stație existentă. Intră în vigoare la următoarea încărcare a nivelului.",
"SETTINGS_STTAI_ENABLE": "Evitarea coliziunilor pe cale ferată simplă",
"SETTINGS_STTAI_ENABLE_TOOLTIP": "Rezervă un segment pe o singură cale pentru un tren pe rând, ținând trenul opus la intrare până ce segmentul e liber. Funcție originală IPT4, nu există în vanilla sau vreun mod absorbit.",
"SETTINGS_STOPSTACKER_ENABLE": "Stivuire locuri la stația de autobuz",
"SETTINGS_STOPSTACKER_ENABLE_TOOLTIP": "Permite unui al doilea/treilea autobuz care se apropie de aceeași stație să folosească propriul loc mai în spate pe banda stației în loc să stea la coadă în spatele primului, astfel că mai multe autobuze pot încărca/descărca odată. Funcție originală IPT4 (reimplementare clean-room simplificată), nu există în vanilla sau vreun mod absorbit.",
"TRAINDISPLAY_LABEL_NAME": "Nume",
"TRAINDISPLAY_LABEL_STATUS": "Stare",
"TRAINDISPLAY_NO_LINE": "Nicio linie",
"TRAINDISPLAY_NO_DESTINATION": "Nicio destinație",
"TRAINDISPLAY_HIDDEN": "Ascuns",
"TRAINDISPLAY_VEHICLE": "Vehicul",
"TRAINDISPLAY_STATE_RETURNING": "Revine",
"TRAINDISPLAY_STATE_STOPPED": "La stație",
"TRAINDISPLAY_STATE_EN_ROUTE": "În traseu",
"TRAINDISPLAY_STATE_ON_LINE": "Pe linie",
"TRAINDISPLAY_STATE_IDLE": "Inactiv",
"AUTOLINECOLOR_REFRESH_BUTTON": "Reîmprospătează nume/culoare",
"AUTOLINECOLOR_REFRESH_BUTTON_TOOLTIP": "Realocă numele și culoarea curente ale liniei conform setărilor AutoLineColor active.",
"AUTOLINECOLOR_REFRESH_DISABLED_TOOLTIP": "Activează o strategie de culoare sau denumire în Setări înainte de a reîmprospăta această linie.",
"TICKET_PRICE_LABEL_TOOLTIP": "Tarif curent: {0}\nTarif original: {1}\nPasageri acum: {2}",
}


if __name__ == "__main__":
    from lang_packs_all import emit

    emit("ro", RO)
