# -*- coding: utf-8 -*-
"""Hungarian complete UI pack. Run: python lang_packs_hu_ro.py"""
from __future__ import print_function

HU = {
"MOD_DESCRIPTION": "Továbbfejlesztett tömegközlekedés: vonalvezérlés, flotta, integrációk és egyebek.",
"CURRENT_WEEK": "Aktuális hét",
"LAST_WEEK": "Előző hét",
"AVERAGE": "Átlag",
"AVERAGE_TOOLTIP": "Az utolsó {0} hét átlaga.",
"CITY_SERVICE_PANEL_TITLE_STATION_STOPS": "Állomási megállók",
"CITY_SERVICE_PANEL_TITLE_DEPOT_VEHICLES": "Telephelyi járművek",
"CITYSERVICE_ACCEPTINTERCITYBUSES": "Távolsági buszok engedélyezése",
"CITYSERVICE_ACCEPTINTERCITYBUSES_TOOLTIP": "Engedélyezi a távolsági buszoknak az állomás használatát. Kapcsolja ki csak helyi buszokhoz.",
"EXPLANATION_BUDGET_CONTROL": "Költségvetés-vezérlés: A járművek számát a költségvetés szabályozza.",
"EXPLANATION_UNBUNCHING": "Csoportosulásgátlás: A játék megpróbál rést tartani a járművek között.",
"LINE_PANEL_STOPS": "Megállók: {0}",
"LINE_PANEL_SPAWNTIMER": "Következő jármű {0} másodperc múlva.",
"LINE_PANEL_DEPOT_WARNING": "<color #FF0000>A kiválasztott telephelyen nincs több jármű.</color>",
"LINE_PANEL_BUDGET_CONTROL": "Költségvetés-vezérlés",
"LINE_PANEL_BUDGET_CONTROL_TOOLTIP": "Bekapcsolja vagy kikapcsolja a költségvetés-vezérlést ezen a vonalon.",
"LINE_PANEL_UNBUNCHING_TOOLTIP": "Bekapcsolja vagy kikapcsolja a csoportosulásgátlást ezen a vonalon.\nA gátlás ki van kapcsolva, ha az agresszivitás 0.",
"LINE_PANEL_DEPOT": "Telephely:",
"LINE_PANEL_NO_DEPOT_FOUND": "Nem található telephely.",
"LINE_PANEL_DEPOT_MARKER_TOOLTIP": "Ugrás a kiválasztott telephelyre.\nShift nyomva tartása kattintáskor ráközelít is.",
"LINE_PANEL_SELECT_TYPES": "Típusok kiválasztása",
"LINE_PANEL_SELECT_TYPES_TOOLTIP": "Váltja a „Típusok kiválasztása” panelt.\nHa a gomb inaktív, előbb válasszon telephelyet.",
"LINE_PANEL_LINE_STOPS": "Vonalmegállók",
"LINE_PANEL_LINE_VEHICLES": "Járművek ezen a vonalon",
"LINE_PANEL_ENQUEUED": "Sorban álló járművek",
"LINE_PANEL_TOTAL_WAITING_PEOPLE_TOOLTIP": "{0} utas vár ezen a vonalon.",
"LINE_PANEL_ADD_VEHICLE": "Jármű hozzáadása",
"LINE_PANEL_ADD_VEHICLE_TOOLTIP": "Új járművet ad a vonalhoz.\nHa a gomb inaktív, a kiválasztott telephelyen nincs több jármű.",
"LINE_PANEL_REMOVE_VEHICLE": "Jármű eltávolítása",
"STOP_LIST_BOX_ROW_STOP": "Megálló #{0}",
"STOP_LIST_BOX_ROW_TOOLTIP": "{0}\nVáró utasok: {1}\n\nJobb kattintás a megállóra ugráshoz.\nShift nyomva tartása kattintáskor ráközelít is.",
"STOP_PANEL_SUGGESTED_NAMES_TOOLTIP": "Javasolt megállónevek listája.",
"STOP_PANEL_REUSE_NAME_TOOLTIP": "Állítsa be ezt a nevet az összes többi megállóra ezen az állomáson / pozíción.",
"STOP_PANEL_WAITING_PEOPLE": "Váró utasok: {0}",
"COMMUTER_DESTINATION_PANEL_TITLE": "Utas célállomása",
"COMMUTER_DESTINATION_HEADER": "Legnépszerűbb célok:",
"COMMUTER_DESTINATION_NONE": "Jelenleg senki sem vár itt.",
"COMMUTER_DESTINATION_LOADING": "Számítás...",
"COMMUTER_DESTINATION_BUTTON": "Célok",
"COMMUTER_DESTINATION_BUTTON_TOOLTIP": "Mutatja, hová tartanak a megállónál várakozó utasok.",
"STOP_PANEL_BORED_TIMER": "Idő a türelmetlenségig: <color #{0}>{1}</color>",
"STOP_PANEL_BORED_TIMER_TOOLTIP": "Az utasok elhagyják a megállót, ha a visszaszámlálás nullára ér.",
"STOP_PANEL_PASSENGERS_IN": "Felszállók:",
"STOP_PANEL_PASSENGERS_IN_TOOLTIP": "Itt felszálló utasok.",
"STOP_PANEL_PASSENGERS_OUT": "Leszállók:",
"STOP_PANEL_PASSENGERS_OUT_TOOLTIP": "Itt leszálló utasok.",
"STOP_PANEL_PASSENGERS_TOTAL": "Összesen:",
"STOP_PANEL_PASSENGERS_TOTAL_TOOLTIP": "Itt kiszolgált utasok összesen.",
"STOP_PANEL_UNBUNCHING_TOOLTIP": "Bekapcsolja vagy kikapcsolja a csoportosulásgátlást ennél a megállónál.\nA gátlás ki van kapcsolva, ha az agresszivitás 0.",
"STOP_PANEL_UPDATE_CLOSE_STOPS": "Közeli megállók frissítése",
"STOP_PANEL_UPDATE_CLOSE_STOPS_TOOLTIP": "Állítsa be a csoportosulásgátlás állapotát az összes többi megállóra ezen az állomáson / pozíción.",
"STOP_PANEL_PREVIOUS": "Előző megálló",
"STOP_PANEL_PREVIOUS_TOOLTIP": "Ugrás az előző megállóra.\nShift nyomva tartása kattintáskor ráközelít is.",
"STOP_PANEL_DELETE_STOP": "Megálló törlése",
"STOP_PANEL_DELETE_STOP_TOOLTIP": "Ez a gomb aktív, amíg az Alt billentyűt nyomva tartja.\nSaját felelősségre használja!!!",
"STOP_PANEL_NEXT": "Következő megálló",
"STOP_PANEL_NEXT_TOOLTIP": "Ugrás a következő megállóra.\nShift nyomva tartása kattintáskor ráközelít is.",
"STOP_BUTTON_TOOLTIP": "{0}\n\nKattintson a megállóra ugráshoz.\nShift nyomva tartása kattintáskor ráközelít is.\nAlt nyomva tartása kattintáskor megakadályozza a megállóinfó panel megnyitását.",
"SETTINGS_DELETE": "Törlés",
"SETTINGS_RESET": "Visszaállítás",
"SETTINGS_TAB_GENERAL": "Általános",
"SETTINGS_ADVANCED_LINKS_GROUP": "Hivatkozások",
"SETTINGS_GITHUB_REPO": "Forráskód a GitHubon",
"SETTINGS_TAB_AUTOLINE": "Auto vonal",
"SETTINGS_TAB_STOPS": "Megállók és állomások",
"SETTINGS_TAB_UNBUNCHING": "Csoportosulásgátlás",
"SETTINGS_TAB_DELETE": "Vonalak törlése",
"SETTINGS_TAB_FLEET": "Flotta és ütemezés",
"SETTINGS_TAB_BUDGET": "Költségvetés és árak",
"SETTINGS_TAB_LINECOLORS": "Vonalszínek",
"SETTINGS": "Beállítások",
"SETTINGS_SPEED": "Sebesség megjelenítése: ",
"SETTINGS_SPEED_TOOLTIP": "Válassza ki a sebesség megjelenítési egységét a felületen.",
"SETTINGS_GAMEPLAY_PROFILE": "Játékmenet-profil",
"SETTINGS_GAMEPLAY_PROFILE_TOOLTIP": "Egyszerre alkalmaz egy beállítás-csomagot. Biztonságos (alapértelmezett) mindent kikapcsol a maximális kompatibilitásért. Vanilla a sima játékot követi. Ajánlott csak az IPT magot kapcsolja be (költségvetés flottakezelés, csoportosulásgátlás, távolsági busz, alépítmény-fülek, unstucker, haladó megállóválasztás, emelt megállók). Realisztikus a legtöbb integrációt. Egyéni soha nem kaszkádol - minden kapcsolót te kezelsz.",
"SETTINGS_GAMEPLAY_PROFILE_CUSTOM": "Egyéni",
"SETTINGS_GAMEPLAY_PROFILE_SAFE": "Biztonságos (minden ki)",
"SETTINGS_GAMEPLAY_PROFILE_VANILLA": "Vanilla",
"SETTINGS_GAMEPLAY_PROFILE_RECOMMENDED": "Ajánlott (IPT mag)",
"SETTINGS_GAMEPLAY_PROFILE_REALISTIC": "Realisztikus",
"SETTINGS_SPEED_KPH": "km/h",
"SETTINGS_SPEED_MPH": "mph",
"SETTINGS_WALKING_SPEED": "Gyalogos/kerékpáros sebesség: ",
"SETTINGS_WALKING_SPEED_TOOLTIP": "Alap: az alapjáték sebességei.\nRealisztikus: a gyaloglási sebességet realisztikus, korhoz kötött értékekre csökkenti.\nA Realisztikus az After Dark DLC-vel a kerékpározást is lassítja.",
"SETTINGS_WALKING_SPEED_MODE_VANILLA": "Alap",
"SETTINGS_WALKING_SPEED_MODE_REALISTIC": "Realisztikus",
"SETTINGS_BBSP": "Jobb buszmegálló-pozíció: ",
"SETTINGS_BBSP_TOOLTIP": "Kikapcsolva: nincs pozícióállítás.\nBekapcsolva: a buszok a megálló elején állnak meg középen helyett.",
"SETTINGS_BBSP_MODE_DISABLED": "Kikapcsolva",
"SETTINGS_BBSP_MODE_ORIGINAL": "Bekapcsolva",
"SETTINGS_BBSP_MODE_UPDATED": "Kísérleti logika használata",
"SETTINGS_BUDGET": "Költségvetés",
"SETTINGS_ENABLE_BUDGET_CONTROL": "Vonal költségvetés-vezérlés:",
"SETTINGS_BUDGET_CONTROL_DISABLED": "Kikapcsolva",
"SETTINGS_BUDGET_CONTROL_ENABLED": "Bekapcsolva",
"SETTINGS_BUDGET_CONTROL_TOOLTIP": "Bekapcsolva a közlekedési vonalak járműszámát a költségvetés szabályozza; frissíti az összes meglévő vonalat és üríti a sorban álló járműveket.",
"SETTINGS_BUDGET_TICKET_PRICES": "Jegyár-testreszabó:",
"SETTINGS_BUDGET_TICKET_PRICES_DISABLED": "Kikapcsolva",
"SETTINGS_BUDGET_TICKET_PRICES_ENABLED": "Bekapcsolva",
"SETTINGS_BUDGET_TICKET_PRICES_TOOLTIP": "Bekapcsolva új fület ad a Gazdaság panelhez csúszkákkal minden közlekedési típus jegyárához.",
"SETTINGS_AUTO_LINE_BUDGET": "Automatikus flottaméret:",
"SETTINGS_AUTO_LINE_BUDGET_DISABLED": "Kikapcsolva",
"SETTINGS_AUTO_LINE_BUDGET_ENABLED": "Bekapcsolva",
"SETTINGS_AUTO_LINE_BUDGET_TOOLTIP": "Bekapcsolva a költségvetés módban lévő vonalak automatikusan a valós utasigényhez igazítják a járműszámot a vanilla költségvetés-csúszka helyett. A Kézi vonalakat soha nem érinti.",
"SETTINGS_AUTO_LINE": "Auto vonal",
"SETTINGS_AUTOSHOW_LINE_INFO": "Vonalinfó panel automatikus megnyitása",
"SETTINGS_AUTOSHOW_LINE_INFO_TOOLTIP": "Automatikusan megjeleníti a vonalinfó panelt új vonal létrehozása után.",
"AUTOLINECOLOR_STRATEGY_DISABLED": "Kikapcsolva",
"AUTOLINECOLOR_STRATEGY_RANDOM_HUE": "Véletlen árnyalat",
"AUTOLINECOLOR_STRATEGY_RANDOM_COLOR": "Véletlen szín",
"AUTOLINECOLOR_STRATEGY_CATEGORISED": "Kategorizált",
"AUTOLINECOLOR_STRATEGY_NAMED": "Elnevezett színek",
"AUTOLINECOLOR_NAMING_DISABLED": "Kikapcsolva",
"AUTOLINECOLOR_NAMING_DISTRICTS": "Kerületek",
"AUTOLINECOLOR_NAMING_LONDON": "London",
"AUTOLINECOLOR_NAMING_ROADS": "Utak",
"AUTOLINECOLOR_NAMING_COLORS": "Elnevezett színek",
"AUTOLINECOLOR_COLOR_STRATEGY": "Színstratégia:",
"AUTOLINECOLOR_COLOR_STRATEGY_TOOLTIP": "Hogyan kapnak színeket az új vonalak:\n'Véletlen árnyalat' = azonos telítettség/fényerő, különböző árnyalatok;\n'Véletlen szín' = teljesen véletlen RGB;\n'Kategorizált' = szín a járműtípus szerint;\n'Elnevezett színek' = előre definiált színpaletta.",
"AUTOLINECOLOR_NAMING_STRATEGY": "Névstratégia:",
"AUTOLINECOLOR_NAMING_STRATEGY_TOOLTIP": "Hogyan kapnak neveket az új vonalak:\n'Nincs' = nincs automatikus névadás;\n'Kerületek' = a kiszolgált kerületek alapján;\n'London' = számozott járatok (London Buses stílus);\n'Utak' = utcanevek alapján;\n'Elnevezett színek' = színnevek alapján.",
"AUTOLINECOLOR_MIN_COLOR_DIFF": "Minimális színkülönbség (%):",
"AUTOLINECOLOR_MIN_COLOR_DIFF_TOOLTIP": "Minimális színkülönbség százalék véletlen színek választásakor.",
"AUTOLINECOLOR_MAX_COLOR_PICK": "Maximális próbálkozások:",
"AUTOLINECOLOR_MAX_COLOR_PICK_TOOLTIP": "Maximális próbálkozás megkülönböztethető szín választására.",
"SETTINGS_UI": "Felület beállítások",
"SETTINGS_VEHICLE_EDITOR_POSITION": "Járműszerkesztő pozíció: ",
"SETTINGS_VEHICLE_EDITOR_POSITION_TOOLTIP": "Válassza ki, hogy a járműszerkesztő panel alul vagy jobbra jelenjen meg.",
"SETTINGS_VEHICLE_EDITOR_POSITION_BOTTOM": "Alul",
"SETTINGS_VEHICLE_EDITOR_POSITION_RIGHT": "Jobb",
"SETTINGS_VEHICLE_EDITOR_HIDE": "Járműszerkesztő elrejtése",
"SETTINGS_VEHICLE_EDITOR_HIDE_TOOLTIP": "Elrejti a járműszerkesztőt a járműpanelekről.",
"SETTINGS_STOPS": "Tömegközlekedési megállók",
"SETTINGS_STOPSANDSTATIONS_DESCRIPTION": "Hány utas várakozhat egy megállónál szállítási típusonként, mielőtt tele lenne. Magasabb értékek csökkentik a zsúfoltsági panaszokat forgalmas megállóknál, kevésbé realisztikus sorméret árán.",
"SETTINGS_STOPSANDSTATIONS_RESET_TOOLTIP": "Minden fenti utaskorlát visszaállítása az alapértelmezett értékekre.",
"SETTINGS_ENABLE_STOPS_AND_STATIONS": "Megállók és állomások engedélyezése",
"SETTINGS_ENABLE_STOPS_AND_STATIONS_TOOLTIP": "Állítsa be, hány lakos várakozhat tömegközlekedésre a megállóknál és állomásokon. Konfigurálja a Megállók fülön.",
"SETTINGS_STOPSANDSTATIONS_ENABLE": "Megállók és állomások engedélyezése",
"SETTINGS_STOPSANDSTATIONS_ENABLE_TOOLTIP": "Utaskorlát érvényesítésének be- vagy kikapcsolása a megállóknál.",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HEADER": "Maximális várakozó utasok egy vonali megállónál:",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS": "Helyi busz",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS_TOOLTIP": "Maximális várakozó utasok helyi buszmegállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS": "Trolibusz",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS_TOOLTIP": "Maximális várakozó utasok trolibusz-megállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS": "Evakuációs busz",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS_TOOLTIP": "Maximális várakozó utasok evakuációs buszmegállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS": "Kirándulóbusz",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS_TOOLTIP": "Maximális várakozó utasok kirándulóbusz-megállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM": "Villamos",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM_TOOLTIP": "Maximális várakozó utasok villamosmegállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO": "Metró",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO_TOOLTIP": "Maximális várakozó utasok metróállomáson",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN": "Vonat",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN_TOOLTIP": "Maximális várakozó utasok vasútállomáson",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL": "Egysínű",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL_TOOLTIP": "Maximális várakozó utasok egysínű megállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP": "Hajó",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP_TOOLTIP": "Maximális várakozó utasok teherszállító kikötőben",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY": "Komp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY_TOOLTIP": "Maximális várakozó utasok komp-megállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE": "Repülő",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE_TOOLTIP": "Maximális várakozó utasok repülőterminálon",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR": "Kábelfüggő",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR_TOOLTIP": "Maximális várakozó utasok kábelfüggő-megállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON": "Hőlégballon",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON_TOOLTIP": "Maximális várakozó utasok hőlégballon-megállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER": "Helikopter",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER_TOOLTIP": "Maximális várakozó utasok helikopter-megállónál",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP": "Léghajó",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP_TOOLTIP": "Maximális várakozó utasok léghajó-megállónál",
"SETTINGS_UNBUNCHING": "Csoportosulásgátlás",
"SETTINGS_UNBUNCHING_AGGRESSION": "Csoportosulásgátlás agresszivitása:",
"SETTINGS_UNBUNCHING_AGGRESSION_TOOLTIP": "Mennyire erősen hat a csoportosulásgátlás?\nLehetséges értékek: 0–52. A 0 kikapcsolja.\nMagasabb értékek erősen befolyásolják a forgalmat, és a járművek eltűnhetnek.",
"SETTINGS_VEHICLE_COUNT": "Járművek új vonalakon:",
"SETTINGS_VEHICLE_COUNT_TOOLTIP": "Az új vonalakhoz automatikusan hozzáadott járművek száma, ha a vonal költségvetés-vezérlés ki van kapcsolva.",
"SETTINGS_SPAWN_TIME_INTERVAL": "Megjelenési időköz:",
"SETTINGS_SPAWN_TIME_INTERVAL_TOOLTIP": "Idő másodpercben a járművek megjelenése között.",
"SETTINGS_UNBUNCHING_RESET_BUTTON_TOOLTIP": "Minden csúszkát visszaállít az alapértelmezettre.",
"UNBUNCHING_ENABLED": "Jármű-csoportosulásgátlás",
"UNBUNCHING_DISABLED": "A csoportosulásgátlás ki van kapcsolva.",
"UNBUNCHING_TARGET_GAP": "Célrés: {0}",
"SETTINGS_EBS_GROUP_BUS": "Gyorsbusz-szolgáltatások",
"SETTINGS_EBS_GROUP_TRAM": "Gyorsvillamos-szolgáltatások",
"SETTINGS_EBS_DROPDOWN_UNBUNCHING_MODE": "Gyorsbusz: ",
"SETTINGS_EBS_TOOLTIP_UNBUNCHING_MODE": "'Kikapcsolva' = A buszok a fenti csoportosulásgátlást használják.\n'Óvatos' = Röviden megáll, ellenőrzi az utasokat, üresen is indulhat.\n'Agresszív' = Teljesen kihagyja a megállókat, ha senki sem vár.",
"SETTINGS_EBS_ENABLE_SELFBAL": "Szolgáltatás önkiegyensúlyozásának bekapcsolása",
"SETTINGS_EBS_DESC_SELFBAL": "A gyorsbusz-szolgáltatás újraoszthatja a járműveket a vonalon a forgalmasabb szakaszok javára és a várakozási idők csökkentésére.",
"SETTINGS_EBS_TOOLTIP_SELFBAL": "Elemzi a vonalszakaszokat, és járműveket helyezhet át forgalmasabb szakaszokra vagy végállomásokra az egyenletesebb szolgáltatásért.\nA döntések valószínűségiek, az utasszámoktól és az áthelyezési esélyektől függenek.",
"SETTINGS_EBS_ENABLE_SELFBAL_TARGETMID": "Önkiegyensúlyozás a vonal középső megállóira",
"SETTINGS_EBS_DESC_SELFBAL_TARGETMID": "Az önkiegyensúlyozás forgalmas középső megállót is választhat, nem csak végállomást, járműáthelyezéskor.",
"SETTINGS_EBS_TOOLTIP_SELFBAL_TARGETMID": "Engedélyezi, hogy az önkiegyensúlyozó forgalmas középső megállóra helyezzen járműveket (végállomás helyett).\nCsak akkor jön szóba, ha a legforgalmasabb megállón több mint 30 utas vár, majd ~50% eséllyel választódik, az összes áthelyezési esély mellett.",
"SETTINGS_EBS_ENABLE_MINIBUS": "Minibusz mód bekapcsolása",
"SETTINGS_EBS_DESC_MINIBUS": "A kisebb kapacitású buszok korábban indulnak, ha csak kevés utas száll fel vagy le.",
"SETTINGS_EBS_TOOLTIP_MINIBUS": "A ≤20 kapacitású buszok korábban indulhatnak, ha a felszálló + leszálló utasok ≤5.",
"SETTINGS_EBS_DROPDOWN_TRAM_UNBUNCHING_MODE": "Gyorsvillamos: ",
"SETTINGS_EBS_TOOLTIP_TRAM_UNBUNCHING": "'Kikapcsolva' = A villamosok a fenti csoportosulásgátlást használják.\n'Könnyűvasút' = Minden megállónál megáll, mindig a teljes időt várja (szigorú fegyelem).\n'Igazi villamos' = Csak akkor áll meg, ha utasok szállnak fel/le.",
"SETTINGS_EBS_MODE_NONE": "Kikapcsolva",
"SETTINGS_EBS_MODE_AGGRESSIVE": "Agresszív",
"SETTINGS_EBS_MODE_PRUDENTIAL": "Óvatos",
"SETTINGS_EBS_TRAM_MODE_LIGHT_RAIL": "Könnyűvasút mód",
"SETTINGS_EBS_TRAM_MODE_NONE": "Kikapcsolva",
"SETTINGS_EBS_TRAM_MODE_TRAM": "Igazi villamos mód",
"SETTINGS_PTU_GROUP": "Beragadt utasok felszabadítása",
"SETTINGS_PTU_ENABLE": "Beragadt utasok eltávolítása",
"SETTINGS_PTU_TOOLTIP": "Automatikusan eltávolítja a felszállás közben beragadt utasokat, így a jármű rendesen indulhat, és elkerülhetők a befagyott indulások.",
"SETTINGS_LINE_DELETION_TOOL": "Vonal törlő eszköz",
"SETTINGS_LINE_DELETION_TOOL_DESCRIPTION": "Jelölje be az alábbi közlekedési típusokat, majd nyomja meg a Törlés gombot az összes ilyen típusú vonal eltávolításához a jelenlegi városból. A kiválasztás ideiglenes - mindig üresen indul, és törlés után törlődik; nem mentődik beállításként.",
"SETTINGS_LINE_DELETION_TOOL_BUTTON_TOOLTIP": "Törli a kiválasztott típusok összes vonalát. Csak betöltött városnál működik.",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_TITLE": "VONALTÖRLÉS MEGERŐSÍTÉSE",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_MSG": "Összes vonal törlésére készül.\nFolytatja?",
"SETTINGS_DELETE_BUS_TOOLTIP": "Törli az összes rendes buszjáratot.",
"SETTINGS_DELETE_SIGHTSEEING_BUS_LABEL": "Kirándulóbuszok",
"SETTINGS_DELETE_SIGHTSEEING_BUS_TOOLTIP": "Törli az összes kirándulóbusz-járatot.",
"SETTINGS_DELETE_TRAM_TOOLTIP": "Törli az összes villamosjáratot.",
"SETTINGS_DELETE_TROLLEYBUS_TOOLTIP": "Törli az összes trolibuszjáratot.",
"SETTINGS_DELETE_TRAIN_TOOLTIP": "Törli az összes vonatjáratot.",
"SETTINGS_DELETE_METRO_TOOLTIP": "Törli az összes földalatti metrójáratot.",
"SETTINGS_DELETE_MONORAIL_TOOLTIP": "Törli az összes egysínű járatot.",
"SETTINGS_DELETE_FERRY_LABEL": "Kompok",
"SETTINGS_DELETE_SHIP_TOOLTIP": "Törli az összes kompjáratot.",
"SETTINGS_DELETE_HELICOPTER_LABEL": "Helikopterek",
"SETTINGS_DELETE_HELICOPTER_TOOLTIP": "Törli az összes helikopterjáratot.",
"SETTINGS_DELETE_BLIMP_LABEL": "Léghajók",
"SETTINGS_DELETE_BLIMP_TOOLTIP": "Törli az összes léghajójáratot.",
"VEHICLE_EDITOR_TITLE": "Járműszerkesztő",
"VEHICLE_EDITOR_SUB_TITLE": "{0} jármű",
"VEHICLE_EDITOR_CAPACITY": "Utas kapacitás",
"VEHICLE_EDITOR_CAPACITY_TAXI": "Utazási kapacitás",
"VEHICLE_EDITOR_CAPACITY_TAXI_TOOLTIP": "Utasok száma műszakonként.",
"VEHICLE_EDITOR_MAINTENANCE": "Karbantartási költség",
"VEHICLE_EDITOR_MAX_SPEED": "Max. sebesség",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS": "Vonatmotor mindkét végén",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS_TOOLTIP": "Bekapcsolja vagy kikapcsolja a vonatmotorokat a vonat mindkét végén.",
"VEHICLE_EDITOR_APPLY": "Alkalmaz",
"VEHICLE_EDITOR_DEFAULT": "Alapértelmezett",
"VEHICLE_LIST_BOX_ROW_TOOLTIP1": "Jobb kattintás a jármű követéséhez.\nShift nyomva tartása kattintáskor ráközelít is.",
"VEHICLE_LIST_BOX_ROW_TOOLTIP2": "Shift + kattintás a jármű sorba állításához.",
"VEHICLE_PANEL_EDIT_TYPE": "Járműtípus szerkesztése",
"VEHICLE_PANEL_EDIT_TYPE_TOOLTIP": "Szerkessze ezt a járműtípust a Járműszerkesztővel.",
"VEHICLE_PANEL_STATUS_NEXT_STOP": "Következő megálló:",
"VEHICLE_PANEL_STATUS_UNBUNCHING": "Csoportosulásgátlás folyamatban",
"VEHICLE_PANEL_LAST_STOP_EXCHANGE": "Utaskereskedelem az utolsó megállón: <color #FF0000>-{0}</color> | <color #00FF00>+{1}</color>",
"VEHICLE_PANEL_PASSENGERS": "Utasok:",
"VEHICLE_PANEL_EARNINGS": "Bevétel:",
"VEHICLE_PANEL_EARNINGS_TOOLTIP": "A jegyeladás eredménye mínusz a jármű karbantartási költsége.",
"VEHICLE_PANEL_PREVIOUS": "Előző jármű",
"VEHICLE_PANEL_PREVIOUS_TOOLTIP": "Ugrás az előző járműre.\nShift nyomva tartása kattintáskor ráközelít is.",
"VEHICLE_PANEL_REMOVE_VEHICLE": "Jármű eltávolítása",
"VEHICLE_PANEL_NEXT": "Következő jármű",
"VEHICLE_PANEL_NEXT_TOOLTIP": "Ugrás a következő járműre.\nShift nyomva tartása kattintáskor ráközelít is.",
"VEHICLE_SELECTION_CAPACITY": "Kapacitás",
"VEHICLE_SELECTION_ADD_VEHICLE": "Adja hozzá ezt a járművet az engedélyezett járművek listájához",
"VEHICLE_SELECTION_ADD_ALL": "Adja hozzá az összes alkalmas járművet az engedélyezett járművek listájához",
"VEHICLE_SELECTION_REMOVE_VEHICLE": "Távolítsa el ezt a járművet az engedélyezett járművek listájáról",
"VEHICLE_SELECTION_REMOVE_ALL": "Távolítsa el az összes járművet az engedélyezett járművek listájáról",
"VEHICLE_SELECTION_AVAILABLE_VEHICLES": "Elérhető járművek",
"VEHICLE_SELECTION_SELECTED_VEHICLES": "Kiválasztott járművek",
"VEHICLE_SELECTION_ANY_VEHICLE": "Bármely jármű",
"VEHICLE_BUTTON_TOOLTIP": "{0}\n\nKattintson a járműre ugráshoz.\nShift nyomva tartása kattintáskor ráközelít is.\nAlt nyomva tartása kattintáskor megakadályozza a járműinfó panel megnyitását.",
"TRANSPORT_LINE_VEHICLECOUNT": "Járművek száma: {0}",
"FLIGHT_TRACKER_NAME": "Járatkövető",
"FLIGHT_STATUS_NONE": "Nincs",
"FLIGHT_STATUS_INCOMING": "Érkező",
"FLIGHT_STATUS_LANDED": "Leszállt",
"FLIGHT_STATUS_AT_GATE": "Kapunál",
"FLIGHT_STATUS_DEPARTED": "Elindult",
"TICKET_PRICE_TAXI_KILOMETER": "Taxiár kilométerenként: ",
"TICKET_PRICE_TAXI_MILE": "Taxiár mérföldenként: ",
"TICKET_PRICE_BUS": "Buszjegy ára: ",
"TICKET_PRICE_INTERCITY_BUS": "Távolsági buszjegy ára: ",
"TICKET_PRICE_METRO": "Metrójegy ára: ",
"TICKET_PRICE_TRAIN": "Vonatjegy ára: ",
"TICKET_PRICE_TRAM": "Villamosjegy ára: ",
"TICKET_PRICE_MONORAIL": "Egysínű jegy ára: ",
"TICKET_PRICE_SHIP": "Hajójegy ára: ",
"TICKET_PRICE_FERRY": "Kompjegy ára: ",
"TICKET_PRICE_PLANE": "Repülőjegy ára: ",
"TICKET_PRICE_CABLECAR": "Kábelfüggő jegy ára: ",
"TICKET_PRICE_SIGHTSEEING_BUS": "Kirándulóbusz-jegy ára: ",
"TICKET_PRICE_TROLLEYBUS": "Trolibuszjegy ára: ",
"TICKET_PRICE_BLIMP": "Léghajójegy ára: ",
"TICKET_PRICE_HELICOPTER": "Helikopterjegy ára: ",
"ECONOMY_TAB_TICKET_PRICES": "Jegyárak",
"ECONOMY_TAB_TICKET_PRICES_TOOLTIP_PASSENGER_COUNT": "Jelenlegi összes utasszám ehhez a közlekedési típushoz.",
"WHATSNEW_3_0_0_1": "Frissítve Race Day-re; most kompatibilis a More Vehicles Renewed-del.",
"WHATSNEW_3_0_0_2": "A következő modok integrálva lettek az IPT3-ba:\n • Advanced Stop Selection Revisited\n • Auto Line Color Redux\n • Better Bus Stop Position\n • Better Train Boarding\n • Elevated Stops Enabler Revisited  \n • Express Bus Services\n • Flight Tracker\n • Intercity Bus Control\n • Mileage Taxi Services\n • Public Transport Unstucker\n • Realistic Walking Speed\n • Stops and Stations\n • Ticket Price Customizer",
"WHATSNEW_3_0_1": "A Public Transport Unstucker most integrálva van az IPT3-ba.\nLásd a 3.0-s verziót a többi integrált modhoz. Iratkozzon le az eredetikről a konfliktusok elkerüléséhez.",
"SETTINGS_TAB_TRAINDISPLAY": "Vonatkijelző",
"SETTINGS_TAB_INTEGRATIONS": "Integrációk",
"SETTINGS_TRAINDISPLAY_GROUP": "Vonatkijelző átfedés",
"SETTINGS_TRAINDISPLAY_GROUP_DESCRIPTION": "Állítsa be a támogatott közlekedési járművek követése közben megjelenő integrált átfedést.",
"SETTINGS_TRAINDISPLAY_ENABLE": "Vonatkijelző bekapcsolása",
"SETTINGS_TRAINDISPLAY_ENABLE_TOOLTIP": "Az integrált vonatkijelző átfedés be- vagy kikapcsolása.",
"SETTINGS_TRAINDISPLAY_MODE_DISABLED": "Kikapcsolva",
"SETTINGS_TRAINDISPLAY_MODE_ENABLED": "Bekapcsolva",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION": "Átfedés pozíciója:",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION_TOOLTIP": "Válassza ki, hol jelenjen meg az átfedés a képernyőn.",
"SETTINGS_TRAINDISPLAY_POS_TOPLEFT": "Bal felső",
"SETTINGS_TRAINDISPLAY_POS_TOPRIGHT": "Jobb felső",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMLEFT": "Bal alsó",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMRIGHT": "Jobb alsó",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE": "Átfedés mérete:",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE_TOOLTIP": "Az átfedés méretének skálázása.",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY": "Átfedés átlátszósága:",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY_TOOLTIP": "Állítsa be, mennyire átlátszó az átfedés.",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL": "Frissítési időköz:",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL_TOOLTIP": "Milyen gyakran frissül az átfedés járműkövetés közben.",
"SETTINGS_TRAINDISPLAY_SHOW_LINE": "Vonalnév megjelenítése",
"SETTINGS_TRAINDISPLAY_SHOW_LINE_TOOLTIP": "A vonalnév szerepeljen az átfedésben.",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION": "Cél megjelenítése",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION_TOOLTIP": "A cél szerepeljen az átfedésben.",
"SETTINGS_TRAINDISPLAY_SHOW_STATE": "Állapot megjelenítése",
"SETTINGS_TRAINDISPLAY_SHOW_STATE_TOOLTIP": "A jármű állapota szerepeljen az átfedésben.",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING": "Csak követés közben",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING_TOOLTIP": "Rejtse el az átfedést, hacsak a kamera ténylegesen nem követ támogatott járművet.",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY": "Csak első személyű kamerában",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY_TOOLTIP": "Csak első személyű kamera mod használatakor jelenjen meg (pl. First Person Camera - Continued). Ha ki van kapcsolva, bármely kameramódban megjelenik támogatott jármű követésekor.",
"SETTINGS_TRAINDISPLAY_THEME": "Színtéma:",
"SETTINGS_TRAINDISPLAY_THEME_TOOLTIP": "Válassza ki az átfedés háttér-/szövegszíneit.",
"SETTINGS_TRAINDISPLAY_THEME_SIMPLE": "Egyszerű",
"SETTINGS_TRAINDISPLAY_THEME_DARK": "Sötét",
"SETTINGS_TRAINDISPLAY_THEME_LIGHT": "Világos",
"SETTINGS_TRAINDISPLAY_THEME_ORIGINAL": "Eredeti",
"SETTINGS_TRAINDISPLAY_THEME_BLUE": "Kék",
"SETTINGS_TRAINDISPLAY_THEME_GREEN": "Zöld",
"SETTINGS_TRAINDISPLAY_THEME_AMBER": "Borostyán",
"COPY_TIP": "Másolja a vonal beállításait.",
"PASTE_TIP": "Illessze be a másolt vonalbeállításokat.",
"COPY_BUILDING_TIP": "Másolja ezeket a beállításokat az épületet kiszolgáló összes vonalra.",
"COPY_DISTRICT_TIP": "Másolja ezeket a beállításokat a kerület összes vonalára.",
"SETTINGS_INTEGRATIONS_GROUP": "Beépített kiegészítők",
"SETTINGS_INTERCITY_BUS_ENABLE": "Távolsági buszvezérlés bekapcsolása",
"SETTINGS_INTERCITY_BUS_ENABLE_TOOLTIP": "Bekapcsolja az integrált távolsági busz kompatibilitási réteget és az állomásjavításokat.",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE": "Haladó megállóválasztás bekapcsolása",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE_TOOLTIP": "Megállókat helyezhet el többvágányos állomások alternatív peronjain/vágányain (tartsa az alternatív mód billentyűt elhelyezéskor). A következő szintbetöltéskor lép életbe.",
"SETTINGS_BETTERBOARDING_ENABLE": "Jobb felszállás bekapcsolása",
"SETTINGS_BETTERBOARDING_ENABLE_TOOLTIP": "Javítja a felszállási döntéseket, hogy az utasok a céljukat ténylegesen kiszolgáló járművet válasszák. A következő szintbetöltéskor lép életbe.",
"SETTINGS_MILEAGETAXI_ENABLE": "Kilométeres taxi bekapcsolása",
"SETTINGS_MILEAGETAXI_ENABLE_TOOLTIP": "A taxit a megtett távolság alapján számolja fix díj helyett, így a hosszabb utak többet hoznak. After Dark DLC szükséges. A következő szintbetöltéskor lép életbe.",
"SETTINGS_ELEVATEDSTOPS_ENABLE": "Emelt megállók bekapcsolása",
"SETTINGS_ELEVATEDSTOPS_ENABLE_TOOLTIP": "Engedélyezi a tömegközlekedési megállókat emelt utakon/hidakon, és megtartja a közvilágítást azokon a szakaszokon. A következő szintbetöltéskor lép életbe.",
"SETTINGS_INTERCITY_BUS_CAPACITY": "Távolsági terminál kapacitása",
"SETTINGS_INTERCITY_BUS_CAPACITY_TOOLTIP": "Hány járművet fogadhat egyszerre egy távolsági buszterminál.",
"SETTINGS_TRAM_DEPOT_CAPACITY": "Villamos telephely kapacitása",
"SETTINGS_TRAM_DEPOT_CAPACITY_TOOLTIP": "A vanilla minden villamos telephelyet gyakorlatilag korlátlan 100 000 járműre állít. A Realisztikus és a Közepes mérsékelt fix plafont alkalmaz; a Kikapcsolva megtartja a meglévő viselkedést.",
"SETTINGS_TAXI_DEPOT_CAPACITY": "Taxi telephely kapacitása",
"SETTINGS_TAXI_DEPOT_CAPACITY_TOOLTIP": "A vanilla minden taxi telephelyet gyakorlatilag korlátlan 100 000 járműre állít. A Realisztikus és a Közepes mérsékelt fix plafont alkalmaz; a Kikapcsolva megtartja a meglévő viselkedést.",
"SETTINGS_BUS_DEPOT_CAPACITY": "Busz telephely kapacitása",
"SETTINGS_BUS_DEPOT_CAPACITY_TOOLTIP": "A vanilla minden busz telephelyet (rendes, bioüzemanyag és túrabusz-garázsok) gyakorlatilag korlátlan 100 000 járműre állít. A Realisztikus és a Közepes mérsékelt fix plafont alkalmaz; a Kikapcsolva megtartja a meglévő viselkedést.",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY": "Trolibusz telephely kapacitása",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY_TOOLTIP": "A vanilla minden trolibusz telephelyet gyakorlatilag korlátlan 100 000 járműre állít. A Realisztikus és a Közepes mérsékelt fix plafont alkalmaz; a Kikapcsolva megtartja a meglévő viselkedést.",
"SETTINGS_FERRY_DEPOT_CAPACITY": "Komp telephely kapacitása",
"SETTINGS_FERRY_DEPOT_CAPACITY_TOOLTIP": "A vanilla minden komp telephelyet gyakorlatilag korlátlan 100 000 járműre állít. A Realisztikus és a Közepes mérsékelt fix plafont alkalmaz; a Kikapcsolva megtartja a meglévő viselkedést.",
"SETTINGS_DEPOT_CAPACITY_DISABLED": "Kikapcsolva (korlátlan)",
"SETTINGS_DEPOT_CAPACITY_INTERMEDIATE": "Közepes",
"SETTINGS_DEPOT_CAPACITY_REALISTIC": "Realisztikus",
"SETTINGS_FLIGHTTRACKER_ENABLE": "Járatkövető bekapcsolása",
"SETTINGS_FLIGHTTRACKER_ENABLE_TOOLTIP": "Bekapcsolja az integrált járatkövető javításokat és a felület támogatását.",
"SETTINGS_SUBBUILDINGSTABS_ENABLE": "Alépítmény-fülek bekapcsolása",
"SETTINGS_SUBBUILDINGSTABS_ENABLE_TOOLTIP": "Fülsort jelenít meg egy épület infopaneljén, ha alépítményei vannak (pl. repülőtér beépített metróállomással), így váltani lehet közöttük.",
"SETTINGS_TAXISTANDFIX_ENABLE": "Taxidállás javítás bekapcsolása",
"SETTINGS_TAXISTANDFIX_ENABLE_TOOLTIP": "A tétlen taxikat a legközelebbi taxidálláshoz küldi ahelyett, hogy véletlenszerűen kóborolnának. After Dark DLC szükséges.",
"SETTINGS_SHAREDSTOPENABLER_ENABLE": "Megosztott megállók bekapcsolása",
"SETTINGS_SHAREDSTOPENABLER_ENABLE_TOOLTIP": "Egynél több közlekedési típus (busz, villamos, trolibusz) megállhat ugyanazon az útszakaszon. Alapból ki - a mod GitHubján látható, mit hagy ki ez a csökkentett verzió.",
"SETTINGS_COMMUTERDESTINATION_ENABLE": "Utas célállomás bekapcsolása (újratervezés folyamatban)",
"SETTINGS_COMMUTERDESTINATION_ENABLE_TOOLTIP": "Átmenetileg nem elérhető: a korábbi panel megkettőzte a megállóinfó UI-t, és az újratervezésig kényszerítve ki van kapcsolva. A jelölőnégyzet nem kapcsolja vissza.",
"SETTINGS_OOC_ENABLE": "Optimalizált külső kapcsolatok",
"SETTINGS_OOC_ENABLE_TOOLTIP": "A teher-vonatok, repülők és hajók tovább várnak teltebb rakományra a külső kapcsolatoknál indulás előtt.",
"SETTINGS_OOC_WAIT_MULTIPLIER": "Várakozási szorzó",
"SETTINGS_OOC_WAIT_MULTIPLIER_TOOLTIP": "Mennyivel tovább vár a vanilla-nál a teltebb rakományra. Magasabb értékek kevesebb, de teltebb utat jelentenek.",
"SETTINGS_OOC_PASSENGER_SCOPE": "Utas várakozás hatóköre",
"SETTINGS_OOC_PASSENGER_SCOPE_TOOLTIP": "Hol érvényes a fenti várakozási szorzó a tömegközlekedésre váró lakosokra. Csak külső kapcsolatok csak a külső kapcsolatnál várókat érinti; városi szintű a szokásos belföldi várakozást is lassítja minden lakosnál (a forrásmod tényleges viselkedése szerint).",
"SETTINGS_OOC_PASSENGER_SCOPE_OUTSIDE": "Csak külső kapcsolatok",
"SETTINGS_OOC_PASSENGER_SCOPE_CITYWIDE": "Városi szintű",
"SETTINGS_OOC_PASSENGER_SCOPE_DISABLED": "Kikapcsolva (vanilla)",
"SETTINGS_OOC_DISABLE_DUMMY": "Dekoratív átmenő forgalom kikapcsolása",
"SETTINGS_OOC_DISABLE_DUMMY_ROAD": "Dekoratív közúti forgalom kikapcsolása",
"SETTINGS_OOC_DISABLE_DUMMY_TRAIN": "Dekoratív vonatforgalom kikapcsolása",
"SETTINGS_OOC_DISABLE_DUMMY_PLANE": "Dekoratív légiforgalom kikapcsolása",
"SETTINGS_OOC_DISABLE_DUMMY_SHIP": "Dekoratív hajóforgalom kikapcsolása",
"SETTINGS_OOC_DISABLE_DUMMY_TOOLTIP": "A külső kapcsolatok általában extra dekoratív forgalmat indítanak, amely soha nem lép be ténylegesen a városba, csak a látványért. Kikapcsolása eltávolítja ezt a forgalmat a valós import/export/utasáramlás érintése nélkül.",
"SETTINGS_UOC_ENABLE": "Korlátlan külső kapcsolatok",
"SETTINGS_UOC_ENABLE_TOOLTIP": "Eltávolítja a vanilla 4-kapcsolatos korlátot utakra, vágányokra, hajó- és repülőútvonalakra, és visszamenőleg összeköti a közlekedési vonalakat, ha új kapcsolat épül meglévő állomás közelében. A következő szintbetöltéskor lép életbe.",
"SETTINGS_STTAI_ENABLE": "Egyvágányú vonat ütközéselkerülés",
"SETTINGS_STTAI_ENABLE_TOOLTIP": "Egyvágányú szakaszt egyszerre egy vonatnak tart fenn, a szembejövő vonatot a bejáratnál tartja, amíg a szakasz szabad. Eredeti IPT4 funkció, nincs a vanillában és egyetlen abszorbeált modban sem.",
"SETTINGS_STOPSTACKER_ENABLE": "Buszmegálló-állás egymásra rakása",
"SETTINGS_STOPSTACKER_ENABLE_TOOLTIP": "A második/harmadik, ugyanarra a megállóra érkező busz a saját állását használhatja hátrébb a megállósávon, ahelyett hogy egy sorban állna a vezető busz mögött, így több busz is rakodhat egyszerre. Eredeti IPT4 funkció (egyszerűsített clean-room újraimplementáció), nincs a vanillában és egyetlen abszorbeált modban sem.",
"TRAINDISPLAY_LABEL_NAME": "Név",
"TRAINDISPLAY_LABEL_STATUS": "Állapot",
"TRAINDISPLAY_NO_LINE": "Nincs vonal",
"TRAINDISPLAY_NO_DESTINATION": "Nincs cél",
"TRAINDISPLAY_HIDDEN": "Rejtett",
"TRAINDISPLAY_VEHICLE": "Jármű",
"TRAINDISPLAY_STATE_RETURNING": "Visszatér",
"TRAINDISPLAY_STATE_STOPPED": "Megállónál",
"TRAINDISPLAY_STATE_EN_ROUTE": "Úton",
"TRAINDISPLAY_STATE_ON_LINE": "Vonalon",
"TRAINDISPLAY_STATE_IDLE": "Üresjárat",
"AUTOLINECOLOR_REFRESH_BUTTON": "Név/szín frissítése",
"AUTOLINECOLOR_REFRESH_BUTTON_TOOLTIP": "Újra kiosztja a jelenlegi vonalnevet és színt az aktív AutoLineColor beállítások szerint.",
"AUTOLINECOLOR_REFRESH_DISABLED_TOOLTIP": "Kapcsoljon be szín- vagy névstratégiát a Beállításokban a vonal frissítése előtt.",
"TICKET_PRICE_LABEL_TOOLTIP": "Jelenlegi díj: {0}\nEredeti díj: {1}\nMost utazó utasok: {2}",
}


if __name__ == "__main__":
    from lang_packs_all import emit

    emit("hu", HU)

