# -*- coding: utf-8 -*-
"""Swedish and Finnish complete UI packs. Run: python lang_packs_sv_fi.py"""
from __future__ import print_function

SV = {
"MOD_DESCRIPTION": "Förbättrad kollektivtrafik: linjekontroll, flotta, integrationer och mer.",
"CURRENT_WEEK": "Denna vecka",
"LAST_WEEK": "Förra veckan",
"AVERAGE": "Genomsnitt",
"AVERAGE_TOOLTIP": "Genomsnitt av de senaste {0} veckorna.",
"CITY_SERVICE_PANEL_TITLE_STATION_STOPS": "Stationshållplatser",
"CITY_SERVICE_PANEL_TITLE_DEPOT_VEHICLES": "Depåfordon",
"CITYSERVICE_ACCEPTINTERCITYBUSES": "Tillåt intercitybussar",
"CITYSERVICE_ACCEPTINTERCITYBUSES_TOOLTIP": "Tillåt intercitybussar att använda denna station. Inaktivera för endast lokala bussar.",
"EXPLANATION_BUDGET_CONTROL": "Budgetstyrning: Antalet fordon styrs av budgeten.",
"EXPLANATION_UNBUNCHING": "Avståndsstyrning: Spelet försöker skapa avstånd mellan fordon.",
"LINE_PANEL_STOPS": "Hållplatser: {0}",
"LINE_PANEL_SPAWNTIMER": "Nästa fordon om {0} sekunder.",
"LINE_PANEL_DEPOT_WARNING": "<color #FF0000>Den valda depån har inga fordon kvar.</color>",
"LINE_PANEL_BUDGET_CONTROL": "Budgetstyrning",
"LINE_PANEL_BUDGET_CONTROL_TOOLTIP": "Aktiverar eller inaktiverar budgetstyrning för denna linje.",
"LINE_PANEL_UNBUNCHING_TOOLTIP": "Aktiverar eller inaktiverar avståndsstyrning för denna linje.\nAvståndsstyrning är inaktiverad om aggressiviteten är satt till 0.",
"LINE_PANEL_DEPOT": "Depå:",
"LINE_PANEL_NO_DEPOT_FOUND": "Ingen depå hittades.",
"LINE_PANEL_DEPOT_MARKER_TOOLTIP": "Hoppa till den valda depån.\nHåll Shift nedtryckt vid klick för att även zooma in.",
"LINE_PANEL_SELECT_TYPES": "Välj typer",
"LINE_PANEL_SELECT_TYPES_TOOLTIP": "Växlar paneln \"Välj typer\".\nOm knappen är inaktiverad måste du välja en depå först.",
"LINE_PANEL_LINE_STOPS": "Linjehållplatser",
"LINE_PANEL_LINE_VEHICLES": "Fordon på denna linje",
"LINE_PANEL_ENQUEUED": "Fordon i kö",
"LINE_PANEL_TOTAL_WAITING_PEOPLE_TOOLTIP": "{0} passagerare väntar på denna linje.",
"LINE_PANEL_ADD_VEHICLE": "Lägg till fordon",
"LINE_PANEL_ADD_VEHICLE_TOOLTIP": "Lägger till ett nytt fordon på linjen.\nOm knappen är inaktiverad har den valda depån inga fordon kvar.",
"LINE_PANEL_REMOVE_VEHICLE": "Ta bort fordon",
"STOP_LIST_BOX_ROW_STOP": "Hållplats #{0}",
"STOP_LIST_BOX_ROW_TOOLTIP": "{0}\nVäntande passagerare: {1}\n\nHögerklicka för att hoppa till denna hållplats.\nHåll Shift nedtryckt vid klick för att även zooma in.",
"STOP_PANEL_SUGGESTED_NAMES_TOOLTIP": "Lista över föreslagna hållplatsnamn.",
"STOP_PANEL_REUSE_NAME_TOOLTIP": "Sätt detta namn på alla andra hållplatser vid denna station/position.",
"STOP_PANEL_WAITING_PEOPLE": "Väntande passagerare: {0}",
"COMMUTER_DESTINATION_PANEL_TITLE": "Passagerardestination",
"COMMUTER_DESTINATION_HEADER": "Populäraste destinationer:",
"COMMUTER_DESTINATION_NONE": "Inga passagerare väntar här just nu.",
"COMMUTER_DESTINATION_LOADING": "Beräknar...",
"COMMUTER_DESTINATION_BUTTON": "Destinationer",
"COMMUTER_DESTINATION_BUTTON_TOOLTIP": "Visa vart passagerarna vid denna hållplats är på väg.",
"STOP_PANEL_BORED_TIMER": "Tid till otålighet: <color #{0}>{1}</color>",
"STOP_PANEL_BORED_TIMER_TOOLTIP": "Passagerare lämnar hållplatsen när nedräkningen når noll.",
"STOP_PANEL_PASSENGERS_IN": "Passagerare in:",
"STOP_PANEL_PASSENGERS_IN_TOOLTIP": "Passagerare som stiger på här.",
"STOP_PANEL_PASSENGERS_OUT": "Passagerare ut:",
"STOP_PANEL_PASSENGERS_OUT_TOOLTIP": "Passagerare som stiger av här.",
"STOP_PANEL_PASSENGERS_TOTAL": "Totalt:",
"STOP_PANEL_PASSENGERS_TOTAL_TOOLTIP": "Totalt antal passagerare som betjänats här.",
"STOP_PANEL_UNBUNCHING_TOOLTIP": "Aktiverar eller inaktiverar avståndsstyrning vid denna hållplats.\nAvståndsstyrning är inaktiverad om aggressiviteten är satt till 0.",
"STOP_PANEL_UPDATE_CLOSE_STOPS": "Uppdatera närliggande hållplatser",
"STOP_PANEL_UPDATE_CLOSE_STOPS_TOOLTIP": "Sätt avståndsstyrningsstatus för alla andra hållplatser vid denna station/position.",
"STOP_PANEL_PREVIOUS": "Föregående hållplats",
"STOP_PANEL_PREVIOUS_TOOLTIP": "Hoppa till föregående hållplats.\nHåll Shift nedtryckt vid klick för att även zooma in.",
"STOP_PANEL_DELETE_STOP": "Ta bort hållplats",
"STOP_PANEL_DELETE_STOP_TOOLTIP": "Denna knapp är aktiv medan du håller Alt nedtryckt.\nAnvänd på egen risk!!!",
"STOP_PANEL_NEXT": "Nästa hållplats",
"STOP_PANEL_NEXT_TOOLTIP": "Hoppa till nästa hållplats.\nHåll Shift nedtryckt vid klick för att även zooma in.",
"STOP_BUTTON_TOOLTIP": "{0}\n\nKlicka för att hoppa till denna hållplats.\nHåll Shift nedtryckt vid klick för att även zooma in.\nHåll Alt nedtryckt vid klick för att undvika att öppna hållplatsinfopanelen.",
"SETTINGS_DELETE": "Radera",
"SETTINGS_RESET": "Återställ",
"SETTINGS_TAB_GENERAL": "Allmänt",
"SETTINGS_ADVANCED_LINKS_GROUP": "Länkar",
"SETTINGS_GITHUB_REPO": "Källkod på GitHub",
"SETTINGS_TAB_AUTOLINE": "Autolinje",
"SETTINGS_TAB_STOPS": "Hållplatser och stationer",
"SETTINGS_TAB_UNBUNCHING": "Avståndsstyrning",
"SETTINGS_TAB_DELETE": "Radera linjer",
"SETTINGS_TAB_FLEET": "Flotta och schemaläggning",
"SETTINGS_TAB_BUDGET": "Budget och priser",
"SETTINGS_TAB_LINECOLORS": "Linjefärger",
"SETTINGS": "Inställningar",
"SETTINGS_SPEED": "Visa hastighet i: ",
"SETTINGS_SPEED_TOOLTIP": "Välj enhet för hastighetsvisning i gränssnittet.",
"SETTINGS_GAMEPLAY_PROFILE": "Spelläge-profil",
"SETTINGS_GAMEPLAY_PROFILE_TOOLTIP": "Tillämpar en uppsättning inställningar på en gång. Säker (standard) lämnar allt av för maximal kompatibilitet med andra mods. Vanilla matchar basspelet. Rekommenderad aktiverar bara IPT-kärnan (budget flottstyrning, avståndsstyrning, intercity-brytare, underbyggnadsflikar, unstucker, avancerat hållplatsval, upphöjda hållplatser). Realistisk aktiverar de flesta absorberade integrationer. Anpassad kaskaderar aldrig - du styr varje reglage själv.",
"SETTINGS_GAMEPLAY_PROFILE_CUSTOM": "Anpassad",
"SETTINGS_GAMEPLAY_PROFILE_SAFE": "Säker (allt av)",
"SETTINGS_GAMEPLAY_PROFILE_VANILLA": "Vanilla",
"SETTINGS_GAMEPLAY_PROFILE_RECOMMENDED": "Rekommenderad (IPT-kärna)",
"SETTINGS_GAMEPLAY_PROFILE_REALISTIC": "Realistisk",
"SETTINGS_SPEED_KPH": "km/h",
"SETTINGS_SPEED_MPH": "mph",
"SETTINGS_WALKING_SPEED": "Gång-/cykelhastighet: ",
"SETTINGS_WALKING_SPEED_TOOLTIP": "Standard: basspelets hastigheter.\nRealistisk: sänker gånghastighet till realistiska, åldersbaserade värden.\nRealistisk sänker också cykelhastighet med After Dark DLC.",
"SETTINGS_WALKING_SPEED_MODE_VANILLA": "Standard",
"SETTINGS_WALKING_SPEED_MODE_REALISTIC": "Realistisk",
"SETTINGS_BBSP": "Bättre busshållplatsposition: ",
"SETTINGS_BBSP_TOOLTIP": "Inaktiverad: ingen positionsjustering.\nAktiverad: bussar stannar längst fram på hållplatsen i stället för i mitten.",
"SETTINGS_BBSP_MODE_DISABLED": "Inaktiverad",
"SETTINGS_BBSP_MODE_ORIGINAL": "Aktiverad",
"SETTINGS_BBSP_MODE_UPDATED": "Använd experimentell logik",
"SETTINGS_BUDGET": "Budget",
"SETTINGS_ENABLE_BUDGET_CONTROL": "Linjebudgetstyrning:",
"SETTINGS_BUDGET_CONTROL_DISABLED": "Inaktiverad",
"SETTINGS_BUDGET_CONTROL_ENABLED": "Aktiverad",
"SETTINGS_BUDGET_CONTROL_TOOLTIP": "När aktiverad styrs antalet fordon på transportlinjer av budgeten; uppdaterar alla befintliga linjer och rensar fordon i kö.",
"SETTINGS_BUDGET_TICKET_PRICES": "Biljettprisanpassning:",
"SETTINGS_BUDGET_TICKET_PRICES_DISABLED": "Inaktiverad",
"SETTINGS_BUDGET_TICKET_PRICES_ENABLED": "Aktiverad",
"SETTINGS_BUDGET_TICKET_PRICES_TOOLTIP": "När aktiverad läggs en ny flik till i Ekonomi-panelen med reglage för biljettpriser per transporttyp.",
"SETTINGS_AUTO_LINE_BUDGET": "Automatisk flottstorlek:",
"SETTINGS_AUTO_LINE_BUDGET_DISABLED": "Inaktiverad",
"SETTINGS_AUTO_LINE_BUDGET_ENABLED": "Aktiverad",
"SETTINGS_AUTO_LINE_BUDGET_TOOLTIP": "När aktiverad justerar linjer i budgetläge automatiskt fordonsantalet efter verklig passagerarefterfrågan i stället för vanilla-budgetreglaget. Linjer satta till Manuell påverkas aldrig.",
"SETTINGS_AUTO_LINE": "Autolinje",
"SETTINGS_AUTOSHOW_LINE_INFO": "Öppna linjeinfopanel automatiskt",
"SETTINGS_AUTOSHOW_LINE_INFO_TOOLTIP": "Visa linjeinfopanelen automatiskt efter att en ny linje skapats.",
"AUTOLINECOLOR_STRATEGY_DISABLED": "Inaktiverad",
"AUTOLINECOLOR_STRATEGY_RANDOM_HUE": "Slumpmässig nyans",
"AUTOLINECOLOR_STRATEGY_RANDOM_COLOR": "Slumpmässig färg",
"AUTOLINECOLOR_STRATEGY_CATEGORISED": "Kategoriserad",
"AUTOLINECOLOR_STRATEGY_NAMED": "Namngivna färger",
"AUTOLINECOLOR_NAMING_DISABLED": "Inaktiverad",
"AUTOLINECOLOR_NAMING_DISTRICTS": "Distrikt",
"AUTOLINECOLOR_NAMING_LONDON": "London",
"AUTOLINECOLOR_NAMING_ROADS": "Vägar",
"AUTOLINECOLOR_NAMING_COLORS": "Namngivna färger",
"AUTOLINECOLOR_COLOR_STRATEGY": "Färgstrategi:",
"AUTOLINECOLOR_COLOR_STRATEGY_TOOLTIP": "Hur färger tilldelas nya linjer:\n'Slumpmässig nyans' = samma mättnad/ljusstyrka, olika nyanser;\n'Slumpmässig färg' = helt slumpmässig RGB;\n'Kategoriserad' = färger efter fordonstyp;\n'Namngivna färger' = fördefinierad färgpalett.",
"AUTOLINECOLOR_NAMING_STRATEGY": "Namnstrategi:",
"AUTOLINECOLOR_NAMING_STRATEGY_TOOLTIP": "Hur namn tilldelas nya linjer:\n'Ingen' = ingen auto-namngivning;\n'Distrikt' = baserat på betjänade distrikt;\n'London' = numrerade rutter (London Buses-stil);\n'Vägar' = baserat på gatunamn;\n'Namngivna färger' = baserat på färgnamn.",
"AUTOLINECOLOR_MIN_COLOR_DIFF": "Minsta färgskillnad (%):",
"AUTOLINECOLOR_MIN_COLOR_DIFF_TOOLTIP": "Minsta färgskillnad i procent vid val av slumpmässiga färger.",
"AUTOLINECOLOR_MAX_COLOR_PICK": "Maximalt antal försök:",
"AUTOLINECOLOR_MAX_COLOR_PICK_TOOLTIP": "Maximalt antal försök att välja en urskiljbar färg.",
"SETTINGS_UI": "UI-inställningar",
"SETTINGS_VEHICLE_EDITOR_POSITION": "Fordonsredigerarens position: ",
"SETTINGS_VEHICLE_EDITOR_POSITION_TOOLTIP": "Välj om fordonsredigeraren visas längst ned eller till höger på skärmen.",
"SETTINGS_VEHICLE_EDITOR_POSITION_BOTTOM": "Nederst",
"SETTINGS_VEHICLE_EDITOR_POSITION_RIGHT": "Höger",
"SETTINGS_VEHICLE_EDITOR_HIDE": "Dölj fordonsredigerare",
"SETTINGS_VEHICLE_EDITOR_HIDE_TOOLTIP": "Dölj fordonsredigeraren från fordonspaneler.",
"SETTINGS_STOPS": "Kollektivhållplatser",
"SETTINGS_STOPSANDSTATIONS_DESCRIPTION": "Hur många passagerare av varje transporttyp som kan vänta vid en hållplats innan den räknas som full. Högre värden minskar trängselklagomål vid trafikerade hållplatser till priset av en mindre realistisk köstorlek.",
"SETTINGS_STOPSANDSTATIONS_RESET_TOOLTIP": "Återställ alla passagerartak ovan till standardvärden.",
"SETTINGS_ENABLE_STOPS_AND_STATIONS": "Aktivera hållplatser och stationer",
"SETTINGS_ENABLE_STOPS_AND_STATIONS_TOOLTIP": "Justera maximalt antal medborgare som kan vänta på kollektivtrafik vid hållplatser och stationer. Konfigurera under fliken Hållplatser.",
"SETTINGS_STOPSANDSTATIONS_ENABLE": "Aktivera hållplatser och stationer",
"SETTINGS_STOPSANDSTATIONS_ENABLE_TOOLTIP": "Aktivera eller inaktivera tillämpning av passagerargränser vid hållplatser.",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HEADER": "Maximala väntande passagerare vid en linjehållplats:",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS": "Linjebuss",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS_TOOLTIP": "Maximala väntande passagerare vid en linjebusshållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS": "Trådbuss",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS_TOOLTIP": "Maximala väntande passagerare vid en trådbusshållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS": "Evakueringsbuss",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS_TOOLTIP": "Maximala väntande passagerare vid en evakueringsbusshållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS": "Turistbuss",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS_TOOLTIP": "Maximala väntande passagerare vid en turistbusshållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM": "Spårvagn",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM_TOOLTIP": "Maximala väntande passagerare vid en spårvagnshållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO": "Tunnelbana",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO_TOOLTIP": "Maximala väntande passagerare vid en tunnelbanestation",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN": "Tåg",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN_TOOLTIP": "Maximala väntande passagerare vid en tågstation",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL": "Monorail",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL_TOOLTIP": "Maximala väntande passagerare vid en monorailhållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP": "Fartyg",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP_TOOLTIP": "Maximala väntande passagerare vid en godsham",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY": "Färja",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY_TOOLTIP": "Maximala väntande passagerare vid en färjehållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE": "Flyg",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE_TOOLTIP": "Maximala väntande passagerare vid en flygterminal",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR": "Linbana",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR_TOOLTIP": "Maximala väntande passagerare vid en linbanehållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON": "Luftballong",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON_TOOLTIP": "Maximala väntande passagerare vid en ballonghållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER": "Helikopter",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER_TOOLTIP": "Maximala väntande passagerare vid en helikopterhållplats",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP": "Luftskepp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP_TOOLTIP": "Maximala väntande passagerare vid en luftskeppshållplats",
"SETTINGS_UNBUNCHING": "Avståndsstyrning",
"SETTINGS_UNBUNCHING_AGGRESSION": "Avståndsstyrningsaggressivitet:",
"SETTINGS_UNBUNCHING_AGGRESSION_TOOLTIP": "Hur starkt ska avståndsstyrning verka?\nMöjliga värden: 0–52. Värde 0 inaktiverar avståndsstyrning.\nHögre värden påverkar trafiken kraftigt och kan få fordon att försvinna.",
"SETTINGS_VEHICLE_COUNT": "Fordon på nya linjer:",
"SETTINGS_VEHICLE_COUNT_TOOLTIP": "Antal fordon som automatiskt läggs till nya linjer när linjebudgetstyrning är av.",
"SETTINGS_SPAWN_TIME_INTERVAL": "Spawn-tidsintervall:",
"SETTINGS_SPAWN_TIME_INTERVAL_TOOLTIP": "Tid i sekunder mellan fordonsspawns.",
"SETTINGS_UNBUNCHING_RESET_BUTTON_TOOLTIP": "Återställer alla reglage till standard.",
"UNBUNCHING_ENABLED": "Avståndsstyrning för fordon",
"UNBUNCHING_DISABLED": "Avståndsstyrning är inaktiverad.",
"UNBUNCHING_TARGET_GAP": "Målavstånd: {0}",
"SETTINGS_EBS_GROUP_BUS": "Expressbusstjänster",
"SETTINGS_EBS_GROUP_TRAM": "Expressspårvagnstjänster",
"SETTINGS_EBS_DROPDOWN_UNBUNCHING_MODE": "Expressbuss: ",
"SETTINGS_EBS_TOOLTIP_UNBUNCHING_MODE": "'Inaktiverad' = Bussar använder avståndsstyrning ovan.\n'Försiktig' = Stannar kort, kontrollerar passagerare, kan avgå tom.\n'Aggressiv' = Hoppar över hållplatser om ingen väntar.",
"SETTINGS_EBS_ENABLE_SELFBAL": "Aktivera självbalansering av tjänst",
"SETTINGS_EBS_DESC_SELFBAL": "Låter expressbusstjänsten omfördela fordon längs linjen för att prioritera trafikerade segment och minska väntetid.",
"SETTINGS_EBS_TOOLTIP_SELFBAL": "Analyserar linjesegment och kan omplacera fordon till trafikerade segment eller ändhållplatser för jämnare trafik och kortare väntetid.\nBeslut är probabilistiska och beror på passagerarantal och omplaceringsodds.",
"SETTINGS_EBS_ENABLE_SELFBAL_TARGETMID": "Aktivera självbalansering till mittlinjehållplatser",
"SETTINGS_EBS_DESC_SELFBAL_TARGETMID": "Tillåter självbalansering att välja en trafikerad hållplats mitt på linjen i stället för bara en ändhållplats vid omplacering.",
"SETTINGS_EBS_TOOLTIP_SELFBAL_TARGETMID": "Tillåt självbalansering att omplacera fordon till en trafikerad mittlinjehållplats (i stället för ändhållplats).\nÖvervägs bara när den mest trafikerade hållplatsen har över 30 väntande passagerare, sedan vald med ~50 % sannolikhet och underställd totala omplaceringsodds.",
"SETTINGS_EBS_ENABLE_MINIBUS": "Aktivera minibuss-läge",
"SETTINGS_EBS_DESC_MINIBUS": "Får mindre bussar att avgå tidigare när bara få passagerare stiger på eller av.",
"SETTINGS_EBS_TOOLTIP_MINIBUS": "Bussar med kapacitet ≤20 kan avgå tidigare från en hållplats när påstigande + avstigande passagerare ≤5.",
"SETTINGS_EBS_DROPDOWN_TRAM_UNBUNCHING_MODE": "Expressspårvagn: ",
"SETTINGS_EBS_TOOLTIP_TRAM_UNBUNCHING": "'Inaktiverad' = Spårvagnar använder avståndsstyrning ovan.\n'Lättbana' = Stannar vid varje hållplats, väntar alltid full tid (strikt disciplin).\n'Äkta spårvagn' = Stannar bara när passagerare stiger på/av.",
"SETTINGS_EBS_MODE_NONE": "Inaktiverad",
"SETTINGS_EBS_MODE_AGGRESSIVE": "Aggressiv",
"SETTINGS_EBS_MODE_PRUDENTIAL": "Försiktig",
"SETTINGS_EBS_TRAM_MODE_LIGHT_RAIL": "Lättbana-läge",
"SETTINGS_EBS_TRAM_MODE_NONE": "Inaktiverad",
"SETTINGS_EBS_TRAM_MODE_TRAM": "Äkta spårvagns-läge",
"SETTINGS_PTU_GROUP": "Frigör fastnade passagerare",
"SETTINGS_PTU_ENABLE": "Ta bort fastnade passagerare",
"SETTINGS_PTU_TOOLTIP": "Tar automatiskt bort passagerare som fastnar vid ombordstigning så att fordonet kan avgå normalt och undvika frusna avgångar.",
"SETTINGS_LINE_DELETION_TOOL": "Verktyg för borttagning av linjer",
"SETTINGS_LINE_DELETION_TOOL_DESCRIPTION": "Markera transporttyperna nedan och tryck Radera för att ta bort alla linjer av de typerna från den aktuella staden. Urvalet är tillfälligt - det börjar alltid omarkerat och rensas efter borttagning; det sparas inte som inställning.",
"SETTINGS_LINE_DELETION_TOOL_BUTTON_TOOLTIP": "Tar bort alla linjer av de valda typerna. Fungerar bara medan staden är laddad.",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_TITLE": "BEKRÄFTA BORTTAGNING AV LINJER",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_MSG": "Du håller på att ta bort alla linjer.\nVill du fortsätta?",
"SETTINGS_DELETE_BUS_TOOLTIP": "Tar bort alla vanliga busslinjer.",
"SETTINGS_DELETE_SIGHTSEEING_BUS_LABEL": "Turistbussar",
"SETTINGS_DELETE_SIGHTSEEING_BUS_TOOLTIP": "Tar bort alla turistbusslinjer.",
"SETTINGS_DELETE_TRAM_TOOLTIP": "Tar bort alla spårvagnslinjer.",
"SETTINGS_DELETE_TROLLEYBUS_TOOLTIP": "Tar bort alla trådbusslinjer.",
"SETTINGS_DELETE_TRAIN_TOOLTIP": "Tar bort alla tåglinjer.",
"SETTINGS_DELETE_METRO_TOOLTIP": "Tar bort alla underjordiska tunnelbanelinjer.",
"SETTINGS_DELETE_MONORAIL_TOOLTIP": "Tar bort alla monoraillinjer.",
"SETTINGS_DELETE_FERRY_LABEL": "Färjor",
"SETTINGS_DELETE_SHIP_TOOLTIP": "Tar bort alla färjelinjer.",
"SETTINGS_DELETE_HELICOPTER_LABEL": "Helikoptrar",
"SETTINGS_DELETE_HELICOPTER_TOOLTIP": "Tar bort alla helikopterlinjer.",
"SETTINGS_DELETE_BLIMP_LABEL": "Luftskepp",
"SETTINGS_DELETE_BLIMP_TOOLTIP": "Tar bort alla luftskeppslinjer.",
"VEHICLE_EDITOR_TITLE": "Fordonsredigerare",
"VEHICLE_EDITOR_SUB_TITLE": "{0} fordon",
"VEHICLE_EDITOR_CAPACITY": "Passagerarkapacitet",
"VEHICLE_EDITOR_CAPACITY_TAXI": "Resekapacitet",
"VEHICLE_EDITOR_CAPACITY_TAXI_TOOLTIP": "Antal passagerare per arbetsskift.",
"VEHICLE_EDITOR_MAINTENANCE": "Underhållskostnad",
"VEHICLE_EDITOR_MAX_SPEED": "Maxhastighet",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS": "Tågmotor i båda ändar",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS_TOOLTIP": "Aktiverar eller inaktiverar tågmotorer i båda ändar av tåget.",
"VEHICLE_EDITOR_APPLY": "Tillämpa",
"VEHICLE_EDITOR_DEFAULT": "Standard",
"VEHICLE_LIST_BOX_ROW_TOOLTIP1": "Högerklicka för att följa detta fordon.\nHåll Shift nedtryckt vid klick för att även zooma in.",
"VEHICLE_LIST_BOX_ROW_TOOLTIP2": "Shift + klick för att ställa detta fordon i kö.",
"VEHICLE_PANEL_EDIT_TYPE": "Redigera fordonstyp",
"VEHICLE_PANEL_EDIT_TYPE_TOOLTIP": "Redigera denna fordonstyp med fordonsredigeraren.",
"VEHICLE_PANEL_STATUS_NEXT_STOP": "Nästa hållplats:",
"VEHICLE_PANEL_STATUS_UNBUNCHING": "Avståndsstyrning pågår",
"VEHICLE_PANEL_LAST_STOP_EXCHANGE": "Passagerarutbyte vid senaste hållplats: <color #FF0000>-{0}</color> | <color #00FF00>+{1}</color>",
"VEHICLE_PANEL_PASSENGERS": "Passagerare:",
"VEHICLE_PANEL_EARNINGS": "Intäkter:",
"VEHICLE_PANEL_EARNINGS_TOOLTIP": "Resultat av biljettförsäljning minus underhållskostnad för fordonet.",
"VEHICLE_PANEL_PREVIOUS": "Föregående fordon",
"VEHICLE_PANEL_PREVIOUS_TOOLTIP": "Hoppa till föregående fordon.\nHåll Shift nedtryckt vid klick för att även zooma in.",
"VEHICLE_PANEL_REMOVE_VEHICLE": "Ta bort fordon",
"VEHICLE_PANEL_NEXT": "Nästa fordon",
"VEHICLE_PANEL_NEXT_TOOLTIP": "Hoppa till nästa fordon.\nHåll Shift nedtryckt vid klick för att även zooma in.",
"VEHICLE_SELECTION_CAPACITY": "Kapacitet",
"VEHICLE_SELECTION_ADD_VEHICLE": "Lägg till detta fordon i listan över tillåtna fordon",
"VEHICLE_SELECTION_ADD_ALL": "Lägg till alla lämpliga fordon i listan över tillåtna fordon",
"VEHICLE_SELECTION_REMOVE_VEHICLE": "Ta bort detta fordon från listan över tillåtna fordon",
"VEHICLE_SELECTION_REMOVE_ALL": "Ta bort alla fordon från listan över tillåtna fordon",
"VEHICLE_SELECTION_AVAILABLE_VEHICLES": "Tillgängliga fordon",
"VEHICLE_SELECTION_SELECTED_VEHICLES": "Valda fordon",
"VEHICLE_SELECTION_ANY_VEHICLE": "Vilket fordon som helst",
"VEHICLE_BUTTON_TOOLTIP": "{0}\n\nKlicka för att hoppa till detta fordon.\nHåll Shift nedtryckt vid klick för att även zooma in.\nHåll Alt nedtryckt vid klick för att undvika att öppna fordonsinfopanelen.",
"TRANSPORT_LINE_VEHICLECOUNT": "Antal fordon: {0}",
"FLIGHT_TRACKER_NAME": "Flygtracker",
"FLIGHT_STATUS_NONE": "Ingen",
"FLIGHT_STATUS_INCOMING": "Ankommande",
"FLIGHT_STATUS_LANDED": "Landat",
"FLIGHT_STATUS_AT_GATE": "Vid gate",
"FLIGHT_STATUS_DEPARTED": "Avgått",
"TICKET_PRICE_TAXI_KILOMETER": "Taxipris per kilometer: ",
"TICKET_PRICE_TAXI_MILE": "Taxipris per mile: ",
"TICKET_PRICE_BUS": "Bussbiljettpris: ",
"TICKET_PRICE_INTERCITY_BUS": "Intercitybussbiljettpris: ",
"TICKET_PRICE_METRO": "Tunnelbanebiljettpris: ",
"TICKET_PRICE_TRAIN": "Tågbiljettpris: ",
"TICKET_PRICE_TRAM": "Spårvagnsbiljettpris: ",
"TICKET_PRICE_MONORAIL": "Monorailbiljettpris: ",
"TICKET_PRICE_SHIP": "Fartygsbiljettpris: ",
"TICKET_PRICE_FERRY": "Färjebiljettpris: ",
"TICKET_PRICE_PLANE": "Flygbiljettpris: ",
"TICKET_PRICE_CABLECAR": "Linbanebiljettpris: ",
"TICKET_PRICE_SIGHTSEEING_BUS": "Turistbussbiljettpris: ",
"TICKET_PRICE_TROLLEYBUS": "Trådbussbiljettpris: ",
"TICKET_PRICE_BLIMP": "Luftskeppsbiljettpris: ",
"TICKET_PRICE_HELICOPTER": "Helikopterbiljettpris: ",
"ECONOMY_TAB_TICKET_PRICES": "Biljettpriser",
"ECONOMY_TAB_TICKET_PRICES_TOOLTIP_PASSENGER_COUNT": "Totalt aktuellt passagerarantal för denna transporttyp.",
"WHATSNEW_3_0_0_1": "Uppdaterad för Race Day; nu kompatibel med More Vehicles Renewed.",
"WHATSNEW_3_0_0_2": "Följande mods har integrerats i IPT3:\n • Advanced Stop Selection Revisited\n • Auto Line Color Redux\n • Better Bus Stop Position\n • Better Train Boarding\n • Elevated Stops Enabler Revisited  \n • Express Bus Services\n • Flight Tracker\n • Intercity Bus Control\n • Mileage Taxi Services\n • Public Transport Unstucker\n • Realistic Walking Speed\n • Stops and Stations\n • Ticket Price Customizer",
"WHATSNEW_3_0_1": "Public Transport Unstucker är nu integrerad i IPT3.\nSe version 3.0 för alla andra integrerade mods. Avprenumerera från originalen för att undvika konflikter.",
"SETTINGS_TAB_TRAINDISPLAY": "Tågvisning",
"SETTINGS_TAB_INTEGRATIONS": "Integrationer",
"SETTINGS_TRAINDISPLAY_GROUP": "Tågvisningsöverlägg",
"SETTINGS_TRAINDISPLAY_GROUP_DESCRIPTION": "Konfigurera det integrerade överlägget som visas medan du följer stödda transportfordon.",
"SETTINGS_TRAINDISPLAY_ENABLE": "Aktivera tågvisning",
"SETTINGS_TRAINDISPLAY_ENABLE_TOOLTIP": "Slå på eller av det integrerade tågvisningsöverlägget.",
"SETTINGS_TRAINDISPLAY_MODE_DISABLED": "Inaktiverad",
"SETTINGS_TRAINDISPLAY_MODE_ENABLED": "Aktiverad",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION": "Överläggsposition:",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION_TOOLTIP": "Välj var överlägget visas på skärmen.",
"SETTINGS_TRAINDISPLAY_POS_TOPLEFT": "Övre vänster",
"SETTINGS_TRAINDISPLAY_POS_TOPRIGHT": "Övre höger",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMLEFT": "Nedre vänster",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMRIGHT": "Nedre höger",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE": "Överläggsskala:",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE_TOOLTIP": "Skala överläggets storlek.",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY": "Överläggstransparens:",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY_TOOLTIP": "Justera hur transparent överlägget är.",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL": "Uppdateringsintervall:",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL_TOOLTIP": "Hur ofta överlägget uppdateras medan du följer ett fordon.",
"SETTINGS_TRAINDISPLAY_SHOW_LINE": "Visa linjenamn",
"SETTINGS_TRAINDISPLAY_SHOW_LINE_TOOLTIP": "Inkludera linjenamnet i överlägget.",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION": "Visa destination",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION_TOOLTIP": "Inkludera destinationen i överlägget.",
"SETTINGS_TRAINDISPLAY_SHOW_STATE": "Visa tillstånd",
"SETTINGS_TRAINDISPLAY_SHOW_STATE_TOOLTIP": "Inkludera fordonets tillstånd i överlägget.",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING": "Endast under följning",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING_TOOLTIP": "Dölj överlägget om inte kameran faktiskt följer ett stött fordon.",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY": "Endast i förstapersonskamera",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY_TOOLTIP": "Visa endast överlägget vid användning av en förstapersonskameramod (t.ex. First Person Camera - Continued). Om av visas det när du följer ett stött fordon i valfritt kameraläge.",
"SETTINGS_TRAINDISPLAY_THEME": "Färgtema:",
"SETTINGS_TRAINDISPLAY_THEME_TOOLTIP": "Välj överläggets bakgrunds-/textfärger.",
"SETTINGS_TRAINDISPLAY_THEME_SIMPLE": "Enkel",
"SETTINGS_TRAINDISPLAY_THEME_DARK": "Mörk",
"SETTINGS_TRAINDISPLAY_THEME_LIGHT": "Ljus",
"SETTINGS_TRAINDISPLAY_THEME_ORIGINAL": "Original",
"SETTINGS_TRAINDISPLAY_THEME_BLUE": "Blå",
"SETTINGS_TRAINDISPLAY_THEME_GREEN": "Grön",
"SETTINGS_TRAINDISPLAY_THEME_AMBER": "Bärnsten",
"COPY_TIP": "Kopiera denna linjes inställningar.",
"PASTE_TIP": "Klistra in de kopierade linjeinställningarna.",
"COPY_BUILDING_TIP": "Kopiera dessa inställningar till alla linjer som betjänar denna byggnad.",
"COPY_DISTRICT_TIP": "Kopiera dessa inställningar till alla linjer i detta distrikt.",
"SETTINGS_INTEGRATIONS_GROUP": "Integrerade tillägg",
"SETTINGS_INTERCITY_BUS_ENABLE": "Aktivera intercitybusskontroll",
"SETTINGS_INTERCITY_BUS_ENABLE_TOOLTIP": "Aktiverar det integrerade intercitybuss-kompatibilitetslagret och stationspatchning.",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE": "Aktivera avancerat hållplatsval",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE_TOOLTIP": "Låter dig placera hållplatser på alternativa plattformar/spår vid flerspåriga stationer (håll alternativläge-tangenten vid placering). Gäller vid nästa nivåinläsning.",
"SETTINGS_BETTERBOARDING_ENABLE": "Aktivera bättre ombordstigning",
"SETTINGS_BETTERBOARDING_ENABLE_TOOLTIP": "Förbättrar ombordstigningsval så att passagerare föredrar fordonet som faktiskt betjänar deras destination. Gäller vid nästa nivåinläsning.",
"SETTINGS_MILEAGETAXI_ENABLE": "Aktivera kilometertaxi",
"SETTINGS_MILEAGETAXI_ENABLE_TOOLTIP": "Tar betalt för taxi efter körd distans i stället för fast pris så att längre resor ger mer. Kräver After Dark DLC. Gäller vid nästa nivåinläsning.",
"SETTINGS_ELEVATEDSTOPS_ENABLE": "Aktivera upphöjda hållplatser",
"SETTINGS_ELEVATEDSTOPS_ENABLE_TOOLTIP": "Tillåter kollektivhållplatser på upphöjda vägar/broar och behåller gatubelysning på de segmenten. Gäller vid nästa nivåinläsning.",
"SETTINGS_INTERCITY_BUS_CAPACITY": "Kapacitet för intercityterminal",
"SETTINGS_INTERCITY_BUS_CAPACITY_TOOLTIP": "Hur många fordon en intercitybussterminal kan rymma samtidigt.",
"SETTINGS_TRAM_DEPOT_CAPACITY": "Spårvagnsdepåkapacitet",
"SETTINGS_TRAM_DEPOT_CAPACITY_TOOLTIP": "Vanilla ger varje spårvagnsdepå en praktiskt obegränsad gräns på 100 000 fordon. Realistisk och Mellan använder i stället ett måttligt fast tak; Inaktiverad behåller befintligt beteende.",
"SETTINGS_TAXI_DEPOT_CAPACITY": "Taxidepåkapacitet",
"SETTINGS_TAXI_DEPOT_CAPACITY_TOOLTIP": "Vanilla ger varje taxidepå en praktiskt obegränsad gräns på 100 000 fordon. Realistisk och Mellan använder i stället ett måttligt fast tak; Inaktiverad behåller befintligt beteende.",
"SETTINGS_BUS_DEPOT_CAPACITY": "Bussdepåkapacitet",
"SETTINGS_BUS_DEPOT_CAPACITY_TOOLTIP": "Vanilla ger varje bussdepå (vanliga, biobränsle och turistbussgarage) en praktiskt obegränsad gräns på 100 000 fordon. Realistisk och Mellan använder i stället ett måttligt fast tak; Inaktiverad behåller befintligt beteende.",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY": "Trådbussdepåkapacitet",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY_TOOLTIP": "Vanilla ger varje trådbussdepå en praktiskt obegränsad gräns på 100 000 fordon. Realistisk och Mellan använder i stället ett måttligt fast tak; Inaktiverad behåller befintligt beteende.",
"SETTINGS_FERRY_DEPOT_CAPACITY": "Färjedepåkapacitet",
"SETTINGS_FERRY_DEPOT_CAPACITY_TOOLTIP": "Vanilla ger varje färjedepå en praktiskt obegränsad gräns på 100 000 fordon. Realistisk och Mellan använder i stället ett måttligt fast tak; Inaktiverad behåller befintligt beteende.",
"SETTINGS_DEPOT_CAPACITY_DISABLED": "Inaktiverad (obegränsad)",
"SETTINGS_DEPOT_CAPACITY_INTERMEDIATE": "Mellan",
"SETTINGS_DEPOT_CAPACITY_REALISTIC": "Realistisk",
"SETTINGS_FLIGHTTRACKER_ENABLE": "Aktivera flygtracker",
"SETTINGS_FLIGHTTRACKER_ENABLE_TOOLTIP": "Aktiverar de integrerade flygtracker-patcharna och UI-stödet.",
"SETTINGS_SUBBUILDINGSTABS_ENABLE": "Aktivera underbyggnadsflikar",
"SETTINGS_SUBBUILDINGSTABS_ENABLE_TOOLTIP": "Visar en flikremsa på en byggnads infopanel när den har underbyggnader (t.ex. en flygplats med inbyggd tunnelbanestation) så att du kan växla mellan dem.",
"SETTINGS_TAXISTANDFIX_ENABLE": "Aktivera taxihållplatsfix",
"SETTINGS_TAXISTANDFIX_ENABLE_TOOLTIP": "Skickar lediga taxibilar till närmaste hållplats i stället för att låta dem köra slumpmässigt. Kräver After Dark DLC.",
"SETTINGS_SHAREDSTOPENABLER_ENABLE": "Aktivera delade hållplatser",
"SETTINGS_SHAREDSTOPENABLER_ENABLE_TOOLTIP": "Tillåter mer än en transporttyp (buss, spårvagn, trådbuss) att stanna på samma vägsegment. Av som standard - se moddens GitHub för vad denna reducerade version utelämnar.",
"SETTINGS_COMMUTERDESTINATION_ENABLE": "Aktivera passagerardestination (omdesign väntar)",
"SETTINGS_COMMUTERDESTINATION_ENABLE_TOOLTIP": "Tillfälligt otillgänglig: den tidigare panelen duplicerade hållplatsinfo-UI och är tvingad av tills en omdesign. Kryssrutan kan inte återaktivera den.",
"SETTINGS_OOC_ENABLE": "Optimerade externa anslutningar",
"SETTINGS_OOC_ENABLE_TOOLTIP": "Godståg, flyg och fartyg väntar längre på en fylligare last innan de avgår vid externa anslutningar.",
"SETTINGS_OOC_WAIT_MULTIPLIER": "Väntemultiplikator",
"SETTINGS_OOC_WAIT_MULTIPLIER_TOOLTIP": "Hur mycket längre än vanilla det väntas på en fylligare last. Högre värden betyder färre men fylligare resor.",
"SETTINGS_OOC_PASSENGER_SCOPE": "Omfattning för passagerarväntan",
"SETTINGS_OOC_PASSENGER_SCOPE_TOOLTIP": "Var väntemultiplikatorn ovan gäller för medborgare som väntar på kollektivtrafik. Endast externa anslutningar påverkar bara medborgare som väntar vid en extern anslutning; stadsomfattande fördröjer också vanlig inhemsk väntan för alla medborgare (matchar källmoddens faktiska beteende).",
"SETTINGS_OOC_PASSENGER_SCOPE_OUTSIDE": "Endast externa anslutningar",
"SETTINGS_OOC_PASSENGER_SCOPE_CITYWIDE": "Stadsomfattande",
"SETTINGS_OOC_PASSENGER_SCOPE_DISABLED": "Inaktiverad (vanilla)",
"SETTINGS_OOC_DISABLE_DUMMY": "Inaktivera dekorativ genomfartstrafik",
"SETTINGS_OOC_DISABLE_DUMMY_ROAD": "Inaktivera dekorativ vägtrafik",
"SETTINGS_OOC_DISABLE_DUMMY_TRAIN": "Inaktivera dekorativ tågtrafik",
"SETTINGS_OOC_DISABLE_DUMMY_PLANE": "Inaktivera dekorativ flygtrafik",
"SETTINGS_OOC_DISABLE_DUMMY_SHIP": "Inaktivera dekorativ fartygstrafik",
"SETTINGS_OOC_DISABLE_DUMMY_TOOLTIP": "Externa anslutningar spawnar normalt extra dekorativ trafik som aldrig faktiskt kommer in i eller lämnar staden, bara för visuell atmosfär. Inaktivering tar bort den trafiken utan att påverka verklig import/export/passagerarflöde.",
"SETTINGS_UOC_ENABLE": "Obegränsade externa anslutningar",
"SETTINGS_UOC_ENABLE_TOOLTIP": "Tar bort vanillas gräns på 4 anslutningar för vägar, spår, fartygs- och flygrutter, och kopplar retrospektivt transportlinjer när en ny anslutning byggs nära en befintlig station. Gäller vid nästa nivåinläsning.",
"SETTINGS_STTAI_ENABLE": "Kollisionsundvikande på enkelspårig järnväg",
"SETTINGS_STTAI_ENABLE_TOOLTIP": "Reserverar ett enkelspårigt segment för ett tåg i taget och håller ett mötande tåg vid ingången tills segmentet är fritt. Original IPT4-funktion, finns inte i vanilla eller någon absorberad mod.",
"SETTINGS_STOPSTACKER_ENABLE": "Stapling av busshållplatsplatser",
"SETTINGS_STOPSTACKER_ENABLE_TOOLTIP": "Låter en andra/tredje buss som närmar sig samma hållplats använda sin egen plats längre bak längs hållplatsspåret i stället för att stå i enkel fil bakom den främsta bussen, så att flera bussar kan lasta/lossa samtidigt. Original IPT4-funktion (förenklad clean-room-omimplementering), finns inte i vanilla eller någon absorberad mod.",
"TRAINDISPLAY_LABEL_NAME": "Namn",
"TRAINDISPLAY_LABEL_STATUS": "Status",
"TRAINDISPLAY_NO_LINE": "Ingen linje",
"TRAINDISPLAY_NO_DESTINATION": "Ingen destination",
"TRAINDISPLAY_HIDDEN": "Dold",
"TRAINDISPLAY_VEHICLE": "Fordon",
"TRAINDISPLAY_STATE_RETURNING": "Återvänder",
"TRAINDISPLAY_STATE_STOPPED": "Vid hållplats",
"TRAINDISPLAY_STATE_EN_ROUTE": "På väg",
"TRAINDISPLAY_STATE_ON_LINE": "På linjen",
"TRAINDISPLAY_STATE_IDLE": "Inaktiv",
"AUTOLINECOLOR_REFRESH_BUTTON": "Uppdatera namn/färg",
"AUTOLINECOLOR_REFRESH_BUTTON_TOOLTIP": "Tilldela om det aktuella linjenamnet och färgen enligt aktiva AutoLineColor-inställningar.",
"AUTOLINECOLOR_REFRESH_DISABLED_TOOLTIP": "Aktivera en färg- eller namnstrategi under Inställningar innan du uppdaterar denna linje.",
"TICKET_PRICE_LABEL_TOOLTIP": "Aktuellt pris: {0}\nOriginalpris: {1}\nPassagerare på väg nu: {2}",
}

# Finnish - large pack continues in same structure
FI = {
"MOD_DESCRIPTION": "Parannettu joukkoliikenne: linjanhallinta, kalusto, integraatiot ja muuta.",
"CURRENT_WEEK": "Kuluva viikko",
"LAST_WEEK": "Viime viikko",
"AVERAGE": "Keskiarvo",
"AVERAGE_TOOLTIP": "Viimeisten {0} viikon keskiarvo.",
"CITY_SERVICE_PANEL_TITLE_STATION_STOPS": "Asemapysäkit",
"CITY_SERVICE_PANEL_TITLE_DEPOT_VEHICLES": "Varikkoajoneuvot",
"CITYSERVICE_ACCEPTINTERCITYBUSES": "Salli kaukobussit",
"CITYSERVICE_ACCEPTINTERCITYBUSES_TOOLTIP": "Salli kaukobussien käyttää tätä asemaa. Poista käytöstä vain paikallisbusseille.",
"EXPLANATION_BUDGET_CONTROL": "Budjettiohjaus: Ajoneuvojen määrä määräytyy budjetin mukaan.",
"EXPLANATION_UNBUNCHING": "Ruuhkautumisen estäminen: Peli yrittää luoda välin ajoneuvojen välille.",
"LINE_PANEL_STOPS": "Pysäkit: {0}",
"LINE_PANEL_SPAWNTIMER": "Seuraava ajoneuvo {0} sekunnin kuluttua.",
"LINE_PANEL_DEPOT_WARNING": "<color #FF0000>Valitulla varikolla ei ole enää ajoneuvoja.</color>",
"LINE_PANEL_BUDGET_CONTROL": "Budjettiohjaus",
"LINE_PANEL_BUDGET_CONTROL_TOOLTIP": "Ottaa budjettiohjauksen käyttöön tai pois tältä linjalta.",
"LINE_PANEL_UNBUNCHING_TOOLTIP": "Ottaa ruuhkautumisen eston käyttöön tai pois tältä linjalta.\nEsto on pois käytöstä, jos aggressiivisuus on 0.",
"LINE_PANEL_DEPOT": "Varikko:",
"LINE_PANEL_NO_DEPOT_FOUND": "Varikkoa ei löytynyt.",
"LINE_PANEL_DEPOT_MARKER_TOOLTIP": "Siirry valittuun varikkoon.\nPidä Shift pohjassa klikatessa zoomataksesi myös.",
"LINE_PANEL_SELECT_TYPES": "Valitse tyypit",
"LINE_PANEL_SELECT_TYPES_TOOLTIP": "Vaihtaa 'Valitse tyypit' -paneelin.\nJos painike on pois käytöstä, valitse ensin varikko.",
"LINE_PANEL_LINE_STOPS": "Linjan pysäkit",
"LINE_PANEL_LINE_VEHICLES": "Ajoneuvot tällä linjalla",
"LINE_PANEL_ENQUEUED": "Ajoneuvot jonossa",
"LINE_PANEL_TOTAL_WAITING_PEOPLE_TOOLTIP": "{0} matkustajaa odottaa tällä linjalla.",
"LINE_PANEL_ADD_VEHICLE": "Lisää ajoneuvo",
"LINE_PANEL_ADD_VEHICLE_TOOLTIP": "Lisää uuden ajoneuvon linjalle.\nJos painike on pois käytöstä, valitulla varikolla ei ole enää ajoneuvoja.",
"LINE_PANEL_REMOVE_VEHICLE": "Poista ajoneuvo",
"STOP_LIST_BOX_ROW_STOP": "Pysäkki #{0}",
"STOP_LIST_BOX_ROW_TOOLTIP": "{0}\nOdottavat matkustajat: {1}\n\nNapsauta oikealla siirtyäksesi tälle pysäkille.\nPidä Shift pohjassa klikatessa zoomataksesi myös.",
"STOP_PANEL_SUGGESTED_NAMES_TOOLTIP": "Ehdotettujen pysäkkinimien luettelo.",
"STOP_PANEL_REUSE_NAME_TOOLTIP": "Aseta tämä nimi kaikille muille pysäkeille tällä asemalla/sijainnilla.",
"STOP_PANEL_WAITING_PEOPLE": "Odottavat matkustajat: {0}",
"COMMUTER_DESTINATION_PANEL_TITLE": "Matkustajien määränpää",
"COMMUTER_DESTINATION_HEADER": "Suosituimmat määränpäät:",
"COMMUTER_DESTINATION_NONE": "Kukaan ei odota täällä juuri nyt.",
"COMMUTER_DESTINATION_LOADING": "Lasketaan...",
"COMMUTER_DESTINATION_BUTTON": "Määränpäät",
"COMMUTER_DESTINATION_BUTTON_TOOLTIP": "Näytä, minne tällä pysäkillä odottavat matkustajat ovat menossa.",
"STOP_PANEL_BORED_TIMER": "Aikaa kyllästymiseen: <color #{0}>{1}</color>",
"STOP_PANEL_BORED_TIMER_TOOLTIP": "Matkustajat lähtevät pysäkiltä, kun lähtölaskenta saavuttaa nollan.",
"STOP_PANEL_PASSENGERS_IN": "Matkustajat sisään:",
"STOP_PANEL_PASSENGERS_IN_TOOLTIP": "Matkustajat, jotka nousevat täällä.",
"STOP_PANEL_PASSENGERS_OUT": "Matkustajat ulos:",
"STOP_PANEL_PASSENGERS_OUT_TOOLTIP": "Matkustajat, jotka poistuvat täällä.",
"STOP_PANEL_PASSENGERS_TOTAL": "Yhteensä:",
"STOP_PANEL_PASSENGERS_TOTAL_TOOLTIP": "Täällä palveltujen matkustajien kokonaismäärä.",
"STOP_PANEL_UNBUNCHING_TOOLTIP": "Ottaa ruuhkautumisen eston käyttöön tai pois tällä pysäkillä.\nEsto on pois käytöstä, jos aggressiivisuus on 0.",
"STOP_PANEL_UPDATE_CLOSE_STOPS": "Päivitä lähipysäkit",
"STOP_PANEL_UPDATE_CLOSE_STOPS_TOOLTIP": "Aseta ruuhkautumisen eston tila kaikille muille pysäkeille tällä asemalla/sijainnilla.",
"STOP_PANEL_PREVIOUS": "Edellinen pysäkki",
"STOP_PANEL_PREVIOUS_TOOLTIP": "Siirry edelliselle pysäkille.\nPidä Shift pohjassa klikatessa zoomataksesi myös.",
"STOP_PANEL_DELETE_STOP": "Poista pysäkki",
"STOP_PANEL_DELETE_STOP_TOOLTIP": "Tämä painike on aktiivinen, kun pidät Alt-näppäintä pohjassa.\nKäytä omalla vastuulla!!!",
"STOP_PANEL_NEXT": "Seuraava pysäkki",
"STOP_PANEL_NEXT_TOOLTIP": "Siirry seuraavalle pysäkille.\nPidä Shift pohjassa klikatessa zoomataksesi myös.",
"STOP_BUTTON_TOOLTIP": "{0}\n\nNapsauta siirtyäksesi tälle pysäkille.\nPidä Shift pohjassa klikatessa zoomataksesi myös.\nPidä Alt pohjassa klikatessa estääksesi pysäkkitietopaneelin avautumisen.",
"SETTINGS_DELETE": "Poista",
"SETTINGS_RESET": "Nollaa",
"SETTINGS_TAB_GENERAL": "Yleiset",
"SETTINGS_ADVANCED_LINKS_GROUP": "Linkit",
"SETTINGS_GITHUB_REPO": "Lähdekoodi GitHubissa",
"SETTINGS_TAB_AUTOLINE": "Automaattilinja",
"SETTINGS_TAB_STOPS": "Pysäkit ja asemat",
"SETTINGS_TAB_UNBUNCHING": "Ruuhkautumisen estäminen",
"SETTINGS_TAB_DELETE": "Poista linjoja",
"SETTINGS_TAB_FLEET": "Kalusto ja aikataulut",
"SETTINGS_TAB_BUDGET": "Budjetti ja hinnat",
"SETTINGS_TAB_LINECOLORS": "Linjavärit",
"SETTINGS": "Asetukset",
"SETTINGS_SPEED": "Näytä nopeus: ",
"SETTINGS_SPEED_TOOLTIP": "Valitse käyttöliittymän nopeusyksikkö.",
"SETTINGS_GAMEPLAY_PROFILE": "Pelaamisprofiili",
"SETTINGS_GAMEPLAY_PROFILE_TOOLTIP": "Soveltaa asetuserän kerralla. Turvallinen (oletus) jättää kaiken pois maksimaalisen yhteensopivuuden vuoksi. Vanilla vastaa peruspeliä. Suositeltu ottaa käyttöön vain IPT-ytimen (budjettikalusto, ruuhkautumisen esto, kaukobussi, alirakennusvälilehdet, unstucker, edistynyt pysäkkivalinta, korotetut pysäkit). Realistinen ottaa useimmat integraatiot käyttöön. Mukautettu ei kaskadoi - hallitset jokaisen kytkimen itse.",
"SETTINGS_GAMEPLAY_PROFILE_CUSTOM": "Mukautettu",
"SETTINGS_GAMEPLAY_PROFILE_SAFE": "Turvallinen (kaikki pois)",
"SETTINGS_GAMEPLAY_PROFILE_VANILLA": "Vanilla",
"SETTINGS_GAMEPLAY_PROFILE_RECOMMENDED": "Suositeltu (IPT-ydin)",
"SETTINGS_GAMEPLAY_PROFILE_REALISTIC": "Realistinen",
"SETTINGS_SPEED_KPH": "km/h",
"SETTINGS_SPEED_MPH": "mph",
"SETTINGS_WALKING_SPEED": "Kävely-/pyöräilynopeus: ",
"SETTINGS_WALKING_SPEED_TOOLTIP": "Vakio: peruspelin nopeudet.\nRealistinen: laskee kävelynopeuden realistisiin, ikäpohjaisiin arvoihin.\nRealistinen vähentää myös pyöräilynopeutta After Dark -lisäosalla.",
"SETTINGS_WALKING_SPEED_MODE_VANILLA": "Vakio",
"SETTINGS_WALKING_SPEED_MODE_REALISTIC": "Realistinen",
"SETTINGS_BBSP": "Parempi bussipysäkin sijainti: ",
"SETTINGS_BBSP_TOOLTIP": "Pois käytöstä: ei sijaintisäätöä.\nKäytössä: bussit pysähtyvät pysäkin etuosaan keskiosan sijaan.",
"SETTINGS_BBSP_MODE_DISABLED": "Pois käytöstä",
"SETTINGS_BBSP_MODE_ORIGINAL": "Käytössä",
"SETTINGS_BBSP_MODE_UPDATED": "Käytä kokeellista logiikkaa",
"SETTINGS_BUDGET": "Budjetti",
"SETTINGS_ENABLE_BUDGET_CONTROL": "Linjan budjettiohjaus:",
"SETTINGS_BUDGET_CONTROL_DISABLED": "Pois käytöstä",
"SETTINGS_BUDGET_CONTROL_ENABLED": "Käytössä",
"SETTINGS_BUDGET_CONTROL_TOOLTIP": "Kun käytössä, liikennelinjojen ajoneuvomäärää ohjaa budjetti; päivittää kaikki olemassa olevat linjat ja tyhjentää jonossa olevat ajoneuvot.",
"SETTINGS_BUDGET_TICKET_PRICES": "Lipunhinnan muokkaus:",
"SETTINGS_BUDGET_TICKET_PRICES_DISABLED": "Pois käytöstä",
"SETTINGS_BUDGET_TICKET_PRICES_ENABLED": "Käytössä",
"SETTINGS_BUDGET_TICKET_PRICES_TOOLTIP": "Kun käytössä, lisää Talous-paneeliin uuden välilehden liukusäätimillä kunkin liikennemuodon lipunhinnoille.",
"SETTINGS_AUTO_LINE_BUDGET": "Automaattinen kalustomäärä:",
"SETTINGS_AUTO_LINE_BUDGET_DISABLED": "Pois käytöstä",
"SETTINGS_AUTO_LINE_BUDGET_ENABLED": "Käytössä",
"SETTINGS_AUTO_LINE_BUDGET_TOOLTIP": "Kun käytössä, budjettitilan linjat säätävät ajoneuvomäärää automaattisesti todellisen matkustajakysynnän mukaan vanilja-budjettiliuskan sijaan. Manuaaliseen asetettuja linjoja ei koskaan kosketa.",
"SETTINGS_AUTO_LINE": "Automaattilinja",
"SETTINGS_AUTOSHOW_LINE_INFO": "Avaa linjatietopaneeli automaattisesti",
"SETTINGS_AUTOSHOW_LINE_INFO_TOOLTIP": "Näytä linjatietopaneeli automaattisesti uuden linjan luonnin jälkeen.",
"AUTOLINECOLOR_STRATEGY_DISABLED": "Pois käytöstä",
"AUTOLINECOLOR_STRATEGY_RANDOM_HUE": "Satunnainen sävy",
"AUTOLINECOLOR_STRATEGY_RANDOM_COLOR": "Satunnainen väri",
"AUTOLINECOLOR_STRATEGY_CATEGORISED": "Luokiteltu",
"AUTOLINECOLOR_STRATEGY_NAMED": "Nimetyt värit",
"AUTOLINECOLOR_NAMING_DISABLED": "Pois käytöstä",
"AUTOLINECOLOR_NAMING_DISTRICTS": "Kaupunginosat",
"AUTOLINECOLOR_NAMING_LONDON": "Lontoo",
"AUTOLINECOLOR_NAMING_ROADS": "Tiet",
"AUTOLINECOLOR_NAMING_COLORS": "Nimetyt värit",
"AUTOLINECOLOR_COLOR_STRATEGY": "Väristrategia:",
"AUTOLINECOLOR_COLOR_STRATEGY_TOOLTIP": "Miten värit annetaan uusille linjoille:\n'Satunnainen sävy' = sama kylläisyys/kirkkaus, eri sävyt;\n'Satunnainen väri' = täysin satunnainen RGB;\n'Luokiteltu' = värit ajoneuvotyypin mukaan;\n'Nimetyt värit' = ennalta määritetty väripaletti.",
"AUTOLINECOLOR_NAMING_STRATEGY": "Nimeämisstrategia:",
"AUTOLINECOLOR_NAMING_STRATEGY_TOOLTIP": "Miten nimet annetaan uusille linjoille:\n'Ei mitään' = ei automaattista nimeämistä;\n'Kaupunginosat' = palveltujen kaupunginosien mukaan;\n'Lontoo' = numeroidut reitit (London Buses -tyyli);\n'Tiet' = katunimien mukaan;\n'Nimetyt värit' = värinimien mukaan.",
"AUTOLINECOLOR_MIN_COLOR_DIFF": "Vähimmäisväriero (%):",
"AUTOLINECOLOR_MIN_COLOR_DIFF_TOOLTIP": "Vähimmäisväriero prosentteina satunnaisia värejä valittaessa.",
"AUTOLINECOLOR_MAX_COLOR_PICK": "Enimmäisyritykset:",
"AUTOLINECOLOR_MAX_COLOR_PICK_TOOLTIP": "Enimmäismäärä yrityksiä erotettavan värin valitsemiseksi.",
"SETTINGS_UI": "Käyttöliittymäasetukset",
"SETTINGS_VEHICLE_EDITOR_POSITION": "Ajoneuvoeditorin sijainti: ",
"SETTINGS_VEHICLE_EDITOR_POSITION_TOOLTIP": "Valitse, näkyykö ajoneuvoeditori alareunassa vai oikealla.",
"SETTINGS_VEHICLE_EDITOR_POSITION_BOTTOM": "Alhaalla",
"SETTINGS_VEHICLE_EDITOR_POSITION_RIGHT": "Oikealla",
"SETTINGS_VEHICLE_EDITOR_HIDE": "Piilota ajoneuvoeditori",
"SETTINGS_VEHICLE_EDITOR_HIDE_TOOLTIP": "Piilota ajoneuvoeditori ajoneuvopaneeleista.",
"SETTINGS_STOPS": "Joukkoliikennepysäkit",
"SETTINGS_STOPSANDSTATIONS_DESCRIPTION": "Kuinka monta matkustajaa kutakin liikennemuotoa voi odottaa yhdellä pysäkillä ennen kuin se katsotaan täydeksi. Suuremmat arvot vähentävät ruuhkavalituksia vilkkailla pysäkeillä vähemmän realistisen jonokoon kustannuksella.",
"SETTINGS_STOPSANDSTATIONS_RESET_TOOLTIP": "Palauta kaikki matkustajakatot yllä oletusarvoihin.",
"SETTINGS_ENABLE_STOPS_AND_STATIONS": "Ota pysäkit ja asemat käyttöön",
"SETTINGS_ENABLE_STOPS_AND_STATIONS_TOOLTIP": "Säädä enimmäismäärä asukkaita, jotka voivat odottaa joukkoliikennettä pysäkeillä ja asemilla. Määritä Pysäkit-välilehdellä.",
"SETTINGS_STOPSANDSTATIONS_ENABLE": "Ota pysäkit ja asemat käyttöön",
"SETTINGS_STOPSANDSTATIONS_ENABLE_TOOLTIP": "Ota matkustajarajojen valvonta käyttöön tai pois pysäkeillä.",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HEADER": "Enimmäismäärä odottavia matkustajia linjapysäkillä:",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS": "Linja-auto",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS_TOOLTIP": "Enimmäismäärä odottavia matkustajia linja-autopysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS": "Johdinauto",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS_TOOLTIP": "Enimmäismäärä odottavia matkustajia johdinautopysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS": "Evakuointibussi",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS_TOOLTIP": "Enimmäismäärä odottavia matkustajia evakuointibussipysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS": "Turistibussi",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS_TOOLTIP": "Enimmäismäärä odottavia matkustajia turistibussipysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM": "Raitiovaunu",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM_TOOLTIP": "Enimmäismäärä odottavia matkustajia raitiovaunupysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO": "Metro",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO_TOOLTIP": "Enimmäismäärä odottavia matkustajia metroasemalla",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN": "Juna",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN_TOOLTIP": "Enimmäismäärä odottavia matkustajia rautatieasemalla",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL": "Monorail",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL_TOOLTIP": "Enimmäismäärä odottavia matkustajia monorail-pysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP": "Laiva",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP_TOOLTIP": "Enimmäismäärä odottavia matkustajia rahtilaivasatamassa",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY": "Lautta",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY_TOOLTIP": "Enimmäismäärä odottavia matkustajia lautapysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE": "Lentokone",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE_TOOLTIP": "Enimmäismäärä odottavia matkustajia lentoterminaalissa",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR": "Köysirata",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR_TOOLTIP": "Enimmäismäärä odottavia matkustajia köysiratapysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON": "Kuumailmapallo",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON_TOOLTIP": "Enimmäismäärä odottavia matkustajia pallopysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER": "Helikopteri",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER_TOOLTIP": "Enimmäismäärä odottavia matkustajia helikopteripysäkillä",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP": "Ilmalaiva",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP_TOOLTIP": "Enimmäismäärä odottavia matkustajia ilmalaivapysäkillä",
"SETTINGS_UNBUNCHING": "Ruuhkautumisen estäminen",
"SETTINGS_UNBUNCHING_AGGRESSION": "Ruuhkautumisen eston aggressiivisuus:",
"SETTINGS_UNBUNCHING_AGGRESSION_TOOLTIP": "Kuinka voimakkaasti ruuhkautumisen eston tulisi toimia?\nMahdolliset arvot: 0–52. Arvo 0 poistaa eston käytöstä.\nKorkeammat arvot vaikuttavat voimakkaasti liikenteeseen ja voivat aiheuttaa ajoneuvojen katoamisen.",
"SETTINGS_VEHICLE_COUNT": "Ajoneuvot uusilla linjoilla:",
"SETTINGS_VEHICLE_COUNT_TOOLTIP": "Ajoneuvojen määrä, joka lisätään automaattisesti uusille linjoille, kun linjan budjettiohjaus on pois päältä.",
"SETTINGS_SPAWN_TIME_INTERVAL": "Syntymisaikaväli:",
"SETTINGS_SPAWN_TIME_INTERVAL_TOOLTIP": "Aika sekunteina ajoneuvojen syntymien välillä.",
"SETTINGS_UNBUNCHING_RESET_BUTTON_TOOLTIP": "Palauttaa kaikki liukusäätimet oletukseen.",
"UNBUNCHING_ENABLED": "Ajoneuvojen ruuhkautumisen estäminen",
"UNBUNCHING_DISABLED": "Ruuhkautumisen estäminen on pois käytöstä.",
"UNBUNCHING_TARGET_GAP": "Tavoiteväli: {0}",
"SETTINGS_EBS_GROUP_BUS": "Pikabussipalvelut",
"SETTINGS_EBS_GROUP_TRAM": "Pikaraitiovaunupalvelut",
"SETTINGS_EBS_DROPDOWN_UNBUNCHING_MODE": "Pikabussi: ",
"SETTINGS_EBS_TOOLTIP_UNBUNCHING_MODE": "'Pois käytöstä' = Bussit käyttävät yllä olevaa ruuhkautumisen estoa.\n'Varovainen' = Pysähtyy hetkeksi, tarkistaa matkustajat, voi lähteä tyhjänä.\n'Aggressiivinen' = Ohittaa pysäkit kokonaan, jos kukaan ei odota.",
"SETTINGS_EBS_ENABLE_SELFBAL": "Ota palvelun itsebalansointi käyttöön",
"SETTINGS_EBS_DESC_SELFBAL": "Antaa pikabussipalvelun jakaa ajoneuvoja linjalla uudelleen vilkkaampien osien hyväksi ja lyhentää odotusaikoja.",
"SETTINGS_EBS_TOOLTIP_SELFBAL": "Analysoi linjan osia ja voi siirtää ajoneuvoja vilkkaampiin osiin tai päätepysäkeille tasaisemman palvelun ja lyhyemmän odotusajan vuoksi.\nPäätökset ovat todennäköisyyspohjaisia ja riippuvat matkustajamääristä sekä uudelleensijoituksen todennäköisyyksistä.",
"SETTINGS_EBS_ENABLE_SELFBAL_TARGETMID": "Ota itsebalansointi linjan keskipysäkeille käyttöön",
"SETTINGS_EBS_DESC_SELFBAL_TARGETMID": "Sallii itsebalansoinnin valita vilkkaan linjan keskipysäkin vain päätepysäkin sijaan ajoneuvoja uudelleensijoitettaessa.",
"SETTINGS_EBS_TOOLTIP_SELFBAL_TARGETMID": "Salli itsebalansoinnin siirtää ajoneuvoja vilkkaalle linjan keskipysäkille (päätepysäkin sijaan).\nOtetaan huomioon vain, kun vilkkaimmalla pysäkillä on yli 30 odottavaa matkustajaa, sitten valitaan ~50 % todennäköisyydellä ja kokonaisuudelleensijoituksen todennäköisyyksien alaisena.",
"SETTINGS_EBS_ENABLE_MINIBUS": "Ota minibussitila käyttöön",
"SETTINGS_EBS_DESC_MINIBUS": "Saa pienemmät bussit lähtemään aiemmin, kun vain muutama matkustaja nousee tai poistuu.",
"SETTINGS_EBS_TOOLTIP_MINIBUS": "Bussit, joiden kapasiteetti ≤20, voivat lähteä aiemmin pysäkiltä, kun nousevat + poistuvat matkustajat ≤5.",
"SETTINGS_EBS_DROPDOWN_TRAM_UNBUNCHING_MODE": "Pikaraitiovaunu: ",
"SETTINGS_EBS_TOOLTIP_TRAM_UNBUNCHING": "'Pois käytöstä' = Raitiovaunut käyttävät yllä olevaa ruuhkautumisen estoa.\n'Kevytraide' = Pysähtyy jokaisella pysäkillä, odottaa aina täyden ajan (tiukka kuri).\n'Todellinen raitiovaunu' = Pysähtyy vain kun matkustajia nousee/poistuu.",
"SETTINGS_EBS_MODE_NONE": "Pois käytöstä",
"SETTINGS_EBS_MODE_AGGRESSIVE": "Aggressiivinen",
"SETTINGS_EBS_MODE_PRUDENTIAL": "Varovainen",
"SETTINGS_EBS_TRAM_MODE_LIGHT_RAIL": "Kevytraidetila",
"SETTINGS_EBS_TRAM_MODE_NONE": "Pois käytöstä",
"SETTINGS_EBS_TRAM_MODE_TRAM": "Todellinen raitiovaunutila",
"SETTINGS_PTU_GROUP": "Jumissa olevien matkustajien vapautus",
"SETTINGS_PTU_ENABLE": "Poista jumissa olevat matkustajat",
"SETTINGS_PTU_TOOLTIP": "Poistaa automaattisesti matkustajat, jotka juuttuvat yrittäessään nousta ajoneuvoon, jotta ajoneuvo voi lähteä normaalisti ja estää jäätyneet lähdöt.",
"SETTINGS_LINE_DELETION_TOOL": "Linjojen poistotyökalu",
"SETTINGS_LINE_DELETION_TOOL_DESCRIPTION": "Valitse alla olevat liikennemuodot ja paina Poista poistaaksesi kaikki kyseisten tyyppien linjat nykyisestä kaupungista. Valinta on tilapäinen - se alkaa aina tyhjänä ja tyhjenee poiston jälkeen; sitä ei tallenneta asetukseksi.",
"SETTINGS_LINE_DELETION_TOOL_BUTTON_TOOLTIP": "Poistaa kaikki valittujen tyyppien linjat. Toimii vain kun kaupunki on ladattu.",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_TITLE": "VAHVISTA LINJOJEN POISTO",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_MSG": "Olet poistamassa kaikki linjat.\nHaluatko jatkaa?",
"SETTINGS_DELETE_BUS_TOOLTIP": "Poistaa kaikki tavalliset bussilinjat.",
"SETTINGS_DELETE_SIGHTSEEING_BUS_LABEL": "Turistibussit",
"SETTINGS_DELETE_SIGHTSEEING_BUS_TOOLTIP": "Poistaa kaikki turistibussilinjat.",
"SETTINGS_DELETE_TRAM_TOOLTIP": "Poistaa kaikki raitiovaunulinjat.",
"SETTINGS_DELETE_TROLLEYBUS_TOOLTIP": "Poistaa kaikki johdinautolinjat.",
"SETTINGS_DELETE_TRAIN_TOOLTIP": "Poistaa kaikki junalinjat.",
"SETTINGS_DELETE_METRO_TOOLTIP": "Poistaa kaikki maanalaiset metrolinjat.",
"SETTINGS_DELETE_MONORAIL_TOOLTIP": "Poistaa kaikki monorail-linjat.",
"SETTINGS_DELETE_FERRY_LABEL": "Lautat",
"SETTINGS_DELETE_SHIP_TOOLTIP": "Poistaa kaikki lauttareitit.",
"SETTINGS_DELETE_HELICOPTER_LABEL": "Helikopterit",
"SETTINGS_DELETE_HELICOPTER_TOOLTIP": "Poistaa kaikki helikopterilinjat.",
"SETTINGS_DELETE_BLIMP_LABEL": "Ilmalaivat",
"SETTINGS_DELETE_BLIMP_TOOLTIP": "Poistaa kaikki ilmalaivalinjat.",
"VEHICLE_EDITOR_TITLE": "Ajoneuvoeditori",
"VEHICLE_EDITOR_SUB_TITLE": "{0} ajoneuvoa",
"VEHICLE_EDITOR_CAPACITY": "Matkustajakapasiteetti",
"VEHICLE_EDITOR_CAPACITY_TAXI": "Matkakapasiteetti",
"VEHICLE_EDITOR_CAPACITY_TAXI_TOOLTIP": "Matkustajien määrä työvuoroa kohti.",
"VEHICLE_EDITOR_MAINTENANCE": "Ylläpitokustannus",
"VEHICLE_EDITOR_MAX_SPEED": "Enimmäisnopeus",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS": "Junamoottori molemmissa päissä",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS_TOOLTIP": "Ottaa junamoottorit käyttöön tai pois junan molemmissa päissä.",
"VEHICLE_EDITOR_APPLY": "Käytä",
"VEHICLE_EDITOR_DEFAULT": "Oletus",
"VEHICLE_LIST_BOX_ROW_TOOLTIP1": "Napsauta oikealla seurataksesi tätä ajoneuvoa.\nPidä Shift pohjassa klikatessa zoomataksesi myös.",
"VEHICLE_LIST_BOX_ROW_TOOLTIP2": "Shift + napsautus jonottaa tämän ajoneuvon.",
"VEHICLE_PANEL_EDIT_TYPE": "Muokkaa ajoneuvotyyppiä",
"VEHICLE_PANEL_EDIT_TYPE_TOOLTIP": "Muokkaa tätä ajoneuvotyyppiä ajoneuvoeditorilla.",
"VEHICLE_PANEL_STATUS_NEXT_STOP": "Seuraava pysäkki:",
"VEHICLE_PANEL_STATUS_UNBUNCHING": "Ruuhkautumisen esto käynnissä",
"VEHICLE_PANEL_LAST_STOP_EXCHANGE": "Matkustajavaihto viimeisellä pysäkillä: <color #FF0000>-{0}</color> | <color #00FF00>+{1}</color>",
"VEHICLE_PANEL_PASSENGERS": "Matkustajat:",
"VEHICLE_PANEL_EARNINGS": "Tuotot:",
"VEHICLE_PANEL_EARNINGS_TOOLTIP": "Lipunmyynnin tulos miinus ajoneuvon ylläpitokustannus.",
"VEHICLE_PANEL_PREVIOUS": "Edellinen ajoneuvo",
"VEHICLE_PANEL_PREVIOUS_TOOLTIP": "Siirry edelliseen ajoneuvoon.\nPidä Shift pohjassa klikatessa zoomataksesi myös.",
"VEHICLE_PANEL_REMOVE_VEHICLE": "Poista ajoneuvo",
"VEHICLE_PANEL_NEXT": "Seuraava ajoneuvo",
"VEHICLE_PANEL_NEXT_TOOLTIP": "Siirry seuraavaan ajoneuvoon.\nPidä Shift pohjassa klikatessa zoomataksesi myös.",
"VEHICLE_SELECTION_CAPACITY": "Kapasiteetti",
"VEHICLE_SELECTION_ADD_VEHICLE": "Lisää tämä ajoneuvo sallittujen ajoneuvojen luetteloon",
"VEHICLE_SELECTION_ADD_ALL": "Lisää kaikki kelvolliset ajoneuvot sallittujen ajoneuvojen luetteloon",
"VEHICLE_SELECTION_REMOVE_VEHICLE": "Poista tämä ajoneuvo sallittujen ajoneuvojen luettelosta",
"VEHICLE_SELECTION_REMOVE_ALL": "Poista kaikki ajoneuvot sallittujen ajoneuvojen luettelosta",
"VEHICLE_SELECTION_AVAILABLE_VEHICLES": "Saatavilla olevat ajoneuvot",
"VEHICLE_SELECTION_SELECTED_VEHICLES": "Valitut ajoneuvot",
"VEHICLE_SELECTION_ANY_VEHICLE": "Mikä tahansa ajoneuvo",
"VEHICLE_BUTTON_TOOLTIP": "{0}\n\nNapsauta siirtyäksesi tähän ajoneuvoon.\nPidä Shift pohjassa klikatessa zoomataksesi myös.\nPidä Alt pohjassa klikatessa estääksesi ajoneuvotietopaneelin avautumisen.",
"TRANSPORT_LINE_VEHICLECOUNT": "Ajoneuvojen määrä: {0}",
"FLIGHT_TRACKER_NAME": "Lentoseuranta",
"FLIGHT_STATUS_NONE": "Ei mitään",
"FLIGHT_STATUS_INCOMING": "Saapuva",
"FLIGHT_STATUS_LANDED": "Laskeutunut",
"FLIGHT_STATUS_AT_GATE": "Portilla",
"FLIGHT_STATUS_DEPARTED": "Lähtenyt",
"TICKET_PRICE_TAXI_KILOMETER": "Taksin hinta kilometriä kohti: ",
"TICKET_PRICE_TAXI_MILE": "Taksin hinta mailia kohti: ",
"TICKET_PRICE_BUS": "Bussilipun hinta: ",
"TICKET_PRICE_INTERCITY_BUS": "Kaukobussilipun hinta: ",
"TICKET_PRICE_METRO": "Metrolipun hinta: ",
"TICKET_PRICE_TRAIN": "Junalipun hinta: ",
"TICKET_PRICE_TRAM": "Raitiovaunulipun hinta: ",
"TICKET_PRICE_MONORAIL": "Monorail-lipun hinta: ",
"TICKET_PRICE_SHIP": "Laivalipun hinta: ",
"TICKET_PRICE_FERRY": "Lauttalipun hinta: ",
"TICKET_PRICE_PLANE": "Lentolipun hinta: ",
"TICKET_PRICE_CABLECAR": "Köysiratalipun hinta: ",
"TICKET_PRICE_SIGHTSEEING_BUS": "Turistibussilipun hinta: ",
"TICKET_PRICE_TROLLEYBUS": "Johdinautolipun hinta: ",
"TICKET_PRICE_BLIMP": "Ilmalaivalipun hinta: ",
"TICKET_PRICE_HELICOPTER": "Helikopterilipun hinta: ",
"ECONOMY_TAB_TICKET_PRICES": "Lipunhinnat",
"ECONOMY_TAB_TICKET_PRICES_TOOLTIP_PASSENGER_COUNT": "Nykyinen matkustajamäärä tälle liikennemuodolle yhteensä.",
"WHATSNEW_3_0_0_1": "Päivitetty Race Daylle; nyt yhteensopiva More Vehicles Renewed -modin kanssa.",
"WHATSNEW_3_0_0_2": "Seuraavat modit on integroitu IPT3:een:\n • Advanced Stop Selection Revisited\n • Auto Line Color Redux\n • Better Bus Stop Position\n • Better Train Boarding\n • Elevated Stops Enabler Revisited  \n • Express Bus Services\n • Flight Tracker\n • Intercity Bus Control\n • Mileage Taxi Services\n • Public Transport Unstucker\n • Realistic Walking Speed\n • Stops and Stations\n • Ticket Price Customizer",
"WHATSNEW_3_0_1": "Public Transport Unstucker on nyt integroitu IPT3:een.\nKatso versio 3.0 kaikista muista integroiduista modeista. Peruuta alkuperäisten tilaus konfliktien välttämiseksi.",
"SETTINGS_TAB_TRAINDISPLAY": "Junanäyttö",
"SETTINGS_TAB_INTEGRATIONS": "Integraatiot",
"SETTINGS_TRAINDISPLAY_GROUP": "Junanäytön peittokuva",
"SETTINGS_TRAINDISPLAY_GROUP_DESCRIPTION": "Määritä integroitu peittokuva, joka näytetään seurattaessa tuettuja kulkuneuvoja.",
"SETTINGS_TRAINDISPLAY_ENABLE": "Ota junanäyttö käyttöön",
"SETTINGS_TRAINDISPLAY_ENABLE_TOOLTIP": "Kytke integroitu junanäytön peittokuva päälle tai pois.",
"SETTINGS_TRAINDISPLAY_MODE_DISABLED": "Pois käytöstä",
"SETTINGS_TRAINDISPLAY_MODE_ENABLED": "Käytössä",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION": "Peittokuvan sijainti:",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION_TOOLTIP": "Valitse, missä peittokuva näkyy näytöllä.",
"SETTINGS_TRAINDISPLAY_POS_TOPLEFT": "Ylävasen",
"SETTINGS_TRAINDISPLAY_POS_TOPRIGHT": "Yläoikea",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMLEFT": "Alavasen",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMRIGHT": "Alaoikea",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE": "Peittokuvan mittakaava:",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE_TOOLTIP": "Skaalaa peittokuvan kokoa.",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY": "Peittokuvan peittävyys:",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY_TOOLTIP": "Säädä peittokuvan läpinäkyvyyttä.",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL": "Päivitysväli:",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL_TOOLTIP": "Kuinka usein peittokuva päivittyy ajoneuvoa seuratessa.",
"SETTINGS_TRAINDISPLAY_SHOW_LINE": "Näytä linjan nimi",
"SETTINGS_TRAINDISPLAY_SHOW_LINE_TOOLTIP": "Sisällytä linjan nimi peittokuvaan.",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION": "Näytä määränpää",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION_TOOLTIP": "Sisällytä määränpää peittokuvaan.",
"SETTINGS_TRAINDISPLAY_SHOW_STATE": "Näytä tila",
"SETTINGS_TRAINDISPLAY_SHOW_STATE_TOOLTIP": "Sisällytä ajoneuvon tila peittokuvaan.",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING": "Vain seuratessa",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING_TOOLTIP": "Piilota peittokuva, ellei kamera todella seuraa tuettua ajoneuvoa.",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY": "Vain ensimmäisen persoonan kamerassa",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY_TOOLTIP": "Näytä peittokuva vain käytettäessä ensimmäisen persoonan kameramodia (esim. First Person Camera - Continued). Jos pois päältä, se näkyy seuratessa tuettua ajoneuvoa missä tahansa kameratilassa.",
"SETTINGS_TRAINDISPLAY_THEME": "Väriteema:",
"SETTINGS_TRAINDISPLAY_THEME_TOOLTIP": "Valitse peittokuvan tausta-/tekstivärit.",
"SETTINGS_TRAINDISPLAY_THEME_SIMPLE": "Yksinkertainen",
"SETTINGS_TRAINDISPLAY_THEME_DARK": "Tumma",
"SETTINGS_TRAINDISPLAY_THEME_LIGHT": "Vaalea",
"SETTINGS_TRAINDISPLAY_THEME_ORIGINAL": "Alkuperäinen",
"SETTINGS_TRAINDISPLAY_THEME_BLUE": "Sininen",
"SETTINGS_TRAINDISPLAY_THEME_GREEN": "Vihreä",
"SETTINGS_TRAINDISPLAY_THEME_AMBER": "Meripihka",
"COPY_TIP": "Kopioi tämän linjan asetukset.",
"PASTE_TIP": "Liitä kopioidut linja-asetukset.",
"COPY_BUILDING_TIP": "Kopioi nämä asetukset kaikille tätä rakennusta palveleville linjoille.",
"COPY_DISTRICT_TIP": "Kopioi nämä asetukset kaikille linjoille tässä kaupunginosassa.",
"SETTINGS_INTEGRATIONS_GROUP": "Integroidut lisäosat",
"SETTINGS_INTERCITY_BUS_ENABLE": "Ota kaukobussiohjaus käyttöön",
"SETTINGS_INTERCITY_BUS_ENABLE_TOOLTIP": "Ottaa käyttöön integroidun kaukobussiyhteensopivuuskerroksen ja asemapaikkaukset.",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE": "Ota käyttöön edistynyt pysäkkivalinta",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE_TOOLTIP": "Antaa sijoittaa pysäkkejä moniraiteisten asemien vaihtoehtoisille laitureille/raiteille (pidä vaihtoehtotilan näppäintä sijoittaessa). Voimaan seuraavalla tason latauksella.",
"SETTINGS_BETTERBOARDING_ENABLE": "Ota parempi nousu käyttöön",
"SETTINGS_BETTERBOARDING_ENABLE_TOOLTIP": "Parantaa matkustajien nousupäätöksiä niin, että he suosivat ajoneuvoa, joka todella palvelee heidän määränpäätään. Voimaan seuraavalla tason latauksella.",
"SETTINGS_MILEAGETAXI_ENABLE": "Ota kilometritaksi käyttöön",
"SETTINGS_MILEAGETAXI_ENABLE_TOOLTIP": "Veloittaa taksista ajetun matkan mukaan kiinteän hinnan sijaan, joten pidemmät matkat tuottavat enemmän. Vaatii After Dark -lisäosan. Voimaan seuraavalla tason latauksella.",
"SETTINGS_ELEVATEDSTOPS_ENABLE": "Ota korotetut pysäkit käyttöön",
"SETTINGS_ELEVATEDSTOPS_ENABLE_TOOLTIP": "Sallii joukkoliikennepysäkit korotetuilla teillä/silloilla ja säilyttää katuvalot niillä osilla. Voimaan seuraavalla tason latauksella.",
"SETTINGS_INTERCITY_BUS_CAPACITY": "Kaukoterminaalin kapasiteetti",
"SETTINGS_INTERCITY_BUS_CAPACITY_TOOLTIP": "Kuinka monta ajoneuvoa kaukobussiterminaali voi pitää kerralla.",
"SETTINGS_TRAM_DEPOT_CAPACITY": "Raitiovaunuvarikon kapasiteetti",
"SETTINGS_TRAM_DEPOT_CAPACITY_TOOLTIP": "Vanilja antaa jokaiselle raitiovaunuvarikolle käytännössä rajattoman 100 000 ajoneuvon rajan. Realistinen ja Keskitaso käyttävät sen sijaan kohtuullista kiinteää kattoa; Pois käytöstä säilyttää nykyisen käyttäytymisen.",
"SETTINGS_TAXI_DEPOT_CAPACITY": "Taksivarikon kapasiteetti",
"SETTINGS_TAXI_DEPOT_CAPACITY_TOOLTIP": "Vanilja antaa jokaiselle taksivarikolle käytännössä rajattoman 100 000 ajoneuvon rajan. Realistinen ja Keskitaso käyttävät sen sijaan kohtuullista kiinteää kattoa; Pois käytöstä säilyttää nykyisen käyttäytymisen.",
"SETTINGS_BUS_DEPOT_CAPACITY": "Bussivarikon kapasiteetti",
"SETTINGS_BUS_DEPOT_CAPACITY_TOOLTIP": "Vanilja antaa jokaiselle bussivarikolle (tavalliset, biopolttoaine ja turistibussitallit) käytännössä rajattoman 100 000 ajoneuvon rajan. Realistinen ja Keskitaso käyttävät sen sijaan kohtuullista kiinteää kattoa; Pois käytöstä säilyttää nykyisen käyttäytymisen.",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY": "Johdinautovarikon kapasiteetti",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY_TOOLTIP": "Vanilja antaa jokaiselle johdinautovarikolle käytännössä rajattoman 100 000 ajoneuvon rajan. Realistinen ja Keskitaso käyttävät sen sijaan kohtuullista kiinteää kattoa; Pois käytöstä säilyttää nykyisen käyttäytymisen.",
"SETTINGS_FERRY_DEPOT_CAPACITY": "Lauttavarikon kapasiteetti",
"SETTINGS_FERRY_DEPOT_CAPACITY_TOOLTIP": "Vanilja antaa jokaiselle lauttavarikolle käytännössä rajattoman 100 000 ajoneuvon rajan. Realistinen ja Keskitaso käyttävät sen sijaan kohtuullista kiinteää kattoa; Pois käytöstä säilyttää nykyisen käyttäytymisen.",
"SETTINGS_DEPOT_CAPACITY_DISABLED": "Pois käytöstä (rajoittamaton)",
"SETTINGS_DEPOT_CAPACITY_INTERMEDIATE": "Keskitaso",
"SETTINGS_DEPOT_CAPACITY_REALISTIC": "Realistinen",
"SETTINGS_FLIGHTTRACKER_ENABLE": "Ota lentoseuranta käyttöön",
"SETTINGS_FLIGHTTRACKER_ENABLE_TOOLTIP": "Ottaa käyttöön integroidut lentoseurantapaikkaukset ja käyttöliittymätuen.",
"SETTINGS_SUBBUILDINGSTABS_ENABLE": "Ota alirakennusvälilehdet käyttöön",
"SETTINGS_SUBBUILDINGSTABS_ENABLE_TOOLTIP": "Näyttää välilehtinauhan rakennuksen tietopaneelissa, kun sillä on alirakennuksia (esim. lentokenttä sisäänrakennetulla metroasemalla), jotta voit vaihtaa niiden välillä.",
"SETTINGS_TAXISTANDFIX_ENABLE": "Ota taksitolppakorjaus käyttöön",
"SETTINGS_TAXISTANDFIX_ENABLE_TOOLTIP": "Lähettää joutilaat taksit lähimmälle taksitolpalle satunnaisen harhailun sijaan. Vaatii After Dark -lisäosan.",
"SETTINGS_SHAREDSTOPENABLER_ENABLE": "Ota jaetut pysäkit käyttöön",
"SETTINGS_SHAREDSTOPENABLER_ENABLE_TOOLTIP": "Sallii useamman kuin yhden liikennemuodon (bussi, raitiovaunu, johdinauto) pysähtyä samalla tieosuudella. Oletuksena pois - katso modin GitHubista, mitä tämä karsittu versio jättää pois.",
"SETTINGS_COMMUTERDESTINATION_ENABLE": "Ota matkustajien määränpää käyttöön (uudelleensuunnittelu odottaa)",
"SETTINGS_COMMUTERDESTINATION_ENABLE_TOOLTIP": "Tilapäisesti poissa käytöstä: aiempi paneeli monisti pysäkkitieto-UI:n ja on pakotettu pois kunnes uudelleensuunnittelu valmistuu. Valintaruutu ei voi ottaa sitä uudelleen käyttöön.",
"SETTINGS_OOC_ENABLE": "Optimoidut ulkoyhteydet",
"SETTINGS_OOC_ENABLE_TOOLTIP": "Rahtijunat, lentokoneet ja laivat odottavat pidempään täydempää lastia ennen lähtöä ulkoyhteyksillä.",
"SETTINGS_OOC_WAIT_MULTIPLIER": "Odotuskerroin",
"SETTINGS_OOC_WAIT_MULTIPLIER_TOOLTIP": "Kuinka paljon pidempään kuin vaniljassa odotetaan täydempää lastia. Suuremmat arvot tarkoittavat harvempia mutta täydempiä matkoja.",
"SETTINGS_OOC_PASSENGER_SCOPE": "Matkustajien odotuksen laajuus",
"SETTINGS_OOC_PASSENGER_SCOPE_TOOLTIP": "Missä yllä oleva odotuskerroin koskee joukkoliikennettä odottavia asukkaita. Vain ulkoyhteydet vaikuttaa vain ulkoyhteydellä odottaviin; koko kaupunki hidastaa myös tavallista kotimaista odotusta jokaiselle asukkaalle (vastaa lähdemodinin todellista käyttäytymistä).",
"SETTINGS_OOC_PASSENGER_SCOPE_OUTSIDE": "Vain ulkoyhteydet",
"SETTINGS_OOC_PASSENGER_SCOPE_CITYWIDE": "Koko kaupunki",
"SETTINGS_OOC_PASSENGER_SCOPE_DISABLED": "Pois käytöstä (vanilja)",
"SETTINGS_OOC_DISABLE_DUMMY": "Poista koristeellinen läpikulkuliikenne",
"SETTINGS_OOC_DISABLE_DUMMY_ROAD": "Poista koristeellinen tieliikenne",
"SETTINGS_OOC_DISABLE_DUMMY_TRAIN": "Poista koristeellinen junaliikenne",
"SETTINGS_OOC_DISABLE_DUMMY_PLANE": "Poista koristeellinen lentoliikenne",
"SETTINGS_OOC_DISABLE_DUMMY_SHIP": "Poista koristeellinen laivaliikenne",
"SETTINGS_OOC_DISABLE_DUMMY_TOOLTIP": "Ulkoyhteydet synnyttävät normaalisti ylimääräistä koristeellista liikennettä, joka ei koskaan todella tule kaupunkiin tai poistu sieltä, vain visuaalisen tunnelman vuoksi. Poistaminen poistaa sen liikenteen vaikuttamatta todelliseen tuonti/vienti/matkustajavirtaan.",
"SETTINGS_UOC_ENABLE": "Rajoittamattomat ulkoyhteydet",
"SETTINGS_UOC_ENABLE_TOOLTIP": "Poistaa vaniljan 4 yhteyden rajan teille, raiteille, laiva- ja lentoreiteille, ja kytkee liikennelinjoja takautuvasti, kun uusi yhteys rakennetaan lähelle olemassa olevaa asemaa. Voimaan seuraavalla tason latauksella.",
"SETTINGS_STTAI_ENABLE": "Yksiraiteisen junan törmäyksen välttäminen",
"SETTINGS_STTAI_ENABLE_TOOLTIP": "Varaa yksiraiteisen osuuden yhdelle junalle kerrallaan ja pitää vastakkaisen junan sisäänkäynnillä, kunnes osuus on vapaa. Alkuperäinen IPT4-ominaisuus, ei vaniljassa eikä missään absorboidussa modissa.",
"SETTINGS_STOPSTACKER_ENABLE": "Bussipysäkin paikkojen pinoaminen",
"SETTINGS_STOPSTACKER_ENABLE_TOOLTIP": "Antaa toisen/kolmannen samaan pysäkkiin saapuvan bussin käyttää omaa paikkaansa kauempana takana pysäkkikaistalla jonottamisen sijaan etummaisen bussin takana, jotta useampi bussi voi lastata/purkaa samanaikaisesti. Alkuperäinen IPT4-ominaisuus (yksinkertaistettu clean-room-uudelleentoteutus), ei vaniljassa eikä missään absorboidussa modissa.",
"TRAINDISPLAY_LABEL_NAME": "Nimi",
"TRAINDISPLAY_LABEL_STATUS": "Tila",
"TRAINDISPLAY_NO_LINE": "Ei linjaa",
"TRAINDISPLAY_NO_DESTINATION": "Ei määränpäätä",
"TRAINDISPLAY_HIDDEN": "Piilotettu",
"TRAINDISPLAY_VEHICLE": "Ajoneuvo",
"TRAINDISPLAY_STATE_RETURNING": "Palaa",
"TRAINDISPLAY_STATE_STOPPED": "Pysäkillä",
"TRAINDISPLAY_STATE_EN_ROUTE": "Matkalla",
"TRAINDISPLAY_STATE_ON_LINE": "Linjalla",
"TRAINDISPLAY_STATE_IDLE": "Jouten",
"AUTOLINECOLOR_REFRESH_BUTTON": "Päivitä nimi/väri",
"AUTOLINECOLOR_REFRESH_BUTTON_TOOLTIP": "Määritä nykyinen linjan nimi ja väri uudelleen aktiivisten AutoLineColor-asetusten mukaan.",
"AUTOLINECOLOR_REFRESH_DISABLED_TOOLTIP": "Ota väri- tai nimeämisstrategia käyttöön Asetuksissa ennen tämän linjan päivittämistä.",
"TICKET_PRICE_LABEL_TOOLTIP": "Nykyinen hinta: {0}\nAlkuperäinen hinta: {1}\nMatkustajia nyt: {2}",
}


if __name__ == "__main__":
    from lang_packs_all import emit

    emit("sv", SV)
    emit("fi", FI)
