# -*- coding: utf-8 -*-
"""Complete UI translation packs. Run as __main__ to emit .txt files."""
from __future__ import print_function
from pathlib import Path


def _t(d):
    return d


def emit(lang, tr):
    root = Path(__file__).resolve().parents[1] / "Translations"
    en_path = root / "en.txt"
    order, en_keys = [], {}
    for line in en_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            order.append(None)
            continue
        i = line.find(" ")
        if i <= 0:
            order.append(None)
            continue
        k, v = line[:i], line[i + 1 :]
        en_keys[k] = v
        order.append(k)
    lines = []
    missing = []
    for k in order:
        if k is None:
            lines.append("")
            continue
        if k.startswith("CHANGELOG_"):
            lines.append("%s %s" % (k, en_keys[k]))
        else:
            val = tr.get(k)
            if val is None:
                missing.append(k)
                val = en_keys[k]
            lines.append("%s %s" % (k, val))
    (root / ("%s.txt" % lang)).write_text("\n".join(lines) + "\n", encoding="utf-8")
    same = sum(
        1
        for k, v in en_keys.items()
        if not k.startswith("CHANGELOG_") and tr.get(k, v) == v
    )
    print("%s missing=%d non-CL same_as_en=%d" % (lang, len(missing), same))
    if missing:
        print("  ", missing[:10])


NO = _t({
"MOD_DESCRIPTION": "Forbedret kollektivtrafikk: linjekontroll, flåte, integrasjoner og mer.",
"CURRENT_WEEK": "Denne uken",
"LAST_WEEK": "Forrige uke",
"AVERAGE": "Gjennomsnitt",
"AVERAGE_TOOLTIP": "Gjennomsnitt av de siste {0} ukene.",
"CITY_SERVICE_PANEL_TITLE_STATION_STOPS": "Stasjonsstopp",
"CITY_SERVICE_PANEL_TITLE_DEPOT_VEHICLES": "Depotkjøretøy",
"CITYSERVICE_ACCEPTINTERCITYBUSES": "Tillat intercitybusser",
"CITYSERVICE_ACCEPTINTERCITYBUSES_TOOLTIP": "Tillat intercitybusser å bruke denne stasjonen. Deaktiver for kun lokale busser.",
"EXPLANATION_BUDGET_CONTROL": "Budsjettkontroll: Antall kjøretøy styres av budsjettet.",
"EXPLANATION_UNBUNCHING": "Avstandsstyring: Spillet prøver å skape avstand mellom kjøretøy.",
"LINE_PANEL_STOPS": "Stopp: {0}",
"LINE_PANEL_SPAWNTIMER": "Neste kjøretøy om {0} sekunder.",
"LINE_PANEL_DEPOT_WARNING": "<color #FF0000>Det valgte depotet har ingen kjøretøy igjen.</color>",
"LINE_PANEL_BUDGET_CONTROL": "Budsjettkontroll",
"LINE_PANEL_BUDGET_CONTROL_TOOLTIP": "Aktiverer eller deaktiverer budsjettkontroll for denne linjen.",
"LINE_PANEL_UNBUNCHING_TOOLTIP": "Aktiverer eller deaktiverer avstandsstyring for denne linjen.\nAvstandsstyring er deaktivert hvis aggressiviteten er satt til 0.",
"LINE_PANEL_DEPOT": "Depot:",
"LINE_PANEL_NO_DEPOT_FOUND": "Ingen depot funnet.",
"LINE_PANEL_DEPOT_MARKER_TOOLTIP": "Hopp til valgt depot.\nHold Shift nede under klikk for også å zoome inn.",
"LINE_PANEL_SELECT_TYPES": "Velg typer",
"LINE_PANEL_SELECT_TYPES_TOOLTIP": "Bytter panelet «Velg typer».\nHvis knappen er deaktivert, må du velge et depot først.",
"LINE_PANEL_LINE_STOPS": "Linjestopp",
"LINE_PANEL_LINE_VEHICLES": "Kjøretøy på denne linjen",
"LINE_PANEL_ENQUEUED": "Kjøretøy i kø",
"LINE_PANEL_TOTAL_WAITING_PEOPLE_TOOLTIP": "{0} passasjerer venter på denne linjen.",
"LINE_PANEL_ADD_VEHICLE": "Legg til kjøretøy",
"LINE_PANEL_ADD_VEHICLE_TOOLTIP": "Legger til et nytt kjøretøy på linjen.\nHvis knappen er deaktivert, har det valgte depotet ingen kjøretøy igjen.",
"LINE_PANEL_REMOVE_VEHICLE": "Fjern kjøretøy",
"STOP_LIST_BOX_ROW_STOP": "Stopp #{0}",
"STOP_LIST_BOX_ROW_TOOLTIP": "{0}\nVentende passasjerer: {1}\n\nHøyreklikk for å hoppe til dette stoppet.\nHold Shift nede under klikk for også å zoome inn.",
"STOP_PANEL_SUGGESTED_NAMES_TOOLTIP": "Liste over foreslåtte stoppnavn.",
"STOP_PANEL_REUSE_NAME_TOOLTIP": "Sett dette navnet på alle andre stopp på denne stasjonen/posisjonen.",
"STOP_PANEL_WAITING_PEOPLE": "Ventende passasjerer: {0}",
"COMMUTER_DESTINATION_PANEL_TITLE": "Passasjerdestinasjon",
"COMMUTER_DESTINATION_HEADER": "Mest populære destinasjoner:",
"COMMUTER_DESTINATION_NONE": "Ingen passasjerer venter her akkurat nå.",
"COMMUTER_DESTINATION_LOADING": "Beregner...",
"COMMUTER_DESTINATION_BUTTON": "Destinasjoner",
"COMMUTER_DESTINATION_BUTTON_TOOLTIP": "Vis hvor passasjerene ved dette stoppet er på vei.",
"STOP_PANEL_BORED_TIMER": "Tid til utålmodighet: <color #{0}>{1}</color>",
"STOP_PANEL_BORED_TIMER_TOOLTIP": "Passasjerer forlater stoppet når nedtellingen når null.",
"STOP_PANEL_PASSENGERS_IN": "Passasjerer inn:",
"STOP_PANEL_PASSENGERS_IN_TOOLTIP": "Passasjerer som stiger på her.",
"STOP_PANEL_PASSENGERS_OUT": "Passasjerer ut:",
"STOP_PANEL_PASSENGERS_OUT_TOOLTIP": "Passasjerer som stiger av her.",
"STOP_PANEL_PASSENGERS_TOTAL": "Totalt:",
"STOP_PANEL_PASSENGERS_TOTAL_TOOLTIP": "Totalt antall passasjerer betjent her.",
"STOP_PANEL_UNBUNCHING_TOOLTIP": "Aktiverer eller deaktiverer avstandsstyring ved dette stoppet.\nAvstandsstyring er deaktivert hvis aggressiviteten er satt til 0.",
"STOP_PANEL_UPDATE_CLOSE_STOPS": "Oppdater nærliggende stopp",
"STOP_PANEL_UPDATE_CLOSE_STOPS_TOOLTIP": "Sett avstandsstyringsstatus for alle andre stopp på denne stasjonen/posisjonen.",
"STOP_PANEL_PREVIOUS": "Forrige stopp",
"STOP_PANEL_PREVIOUS_TOOLTIP": "Hopp til forrige stopp.\nHold Shift nede under klikk for også å zoome inn.",
"STOP_PANEL_DELETE_STOP": "Slett stopp",
"STOP_PANEL_DELETE_STOP_TOOLTIP": "Denne knappen er aktiv mens du holder Alt nede.\nBruk på eget ansvar!!!",
"STOP_PANEL_NEXT": "Neste stopp",
"STOP_PANEL_NEXT_TOOLTIP": "Hopp til neste stopp.\nHold Shift nede under klikk for også å zoome inn.",
"STOP_BUTTON_TOOLTIP": "{0}\n\nKlikk for å hoppe til dette stoppet.\nHold Shift nede under klikk for også å zoome inn.\nHold Alt nede under klikk for å unngå å åpne stoppinfo-panelet.",
"SETTINGS_DELETE": "Slett",
"SETTINGS_RESET": "Tilbakestill",
"SETTINGS_TAB_GENERAL": "Generelt",
"SETTINGS_ADVANCED_LINKS_GROUP": "Lenker",
"SETTINGS_GITHUB_REPO": "Kildekode på GitHub",
"SETTINGS_TAB_AUTOLINE": "Auto-linje",
"SETTINGS_TAB_STOPS": "Stopp og stasjoner",
"SETTINGS_TAB_UNBUNCHING": "Avstandsstyring",
"SETTINGS_TAB_DELETE": "Slett linjer",
"SETTINGS_TAB_FLEET": "Flåte og planlegging",
"SETTINGS_TAB_BUDGET": "Budsjett og priser",
"SETTINGS_TAB_LINECOLORS": "Linjefarger",
"SETTINGS": "Innstillinger",
"SETTINGS_SPEED": "Vis hastighet i: ",
"SETTINGS_SPEED_TOOLTIP": "Velg enheten for hastighetsvisning i grensesnittet.",
"SETTINGS_GAMEPLAY_PROFILE": "Spillprofil",
"SETTINGS_GAMEPLAY_PROFILE_TOOLTIP": "Bruker en pakke innstillinger på én gang. Sikker (standard) lar alt være av for maksimal kompatibilitet med andre mods. Vanilla matcher basisspillet. Anbefalt aktiverer bare IPT-kjernen (budsjett flåtestyring, avstandsstyring, intercity-bryter, underbygning-faner, unstucker, avansert stoppvalg, forhøyede stopp). Realistisk aktiverer de fleste absorberte integrasjoner. Egendefinert kaskaderer aldri - du styrer hver bryter selv.",
"SETTINGS_GAMEPLAY_PROFILE_CUSTOM": "Egendefinert",
"SETTINGS_GAMEPLAY_PROFILE_SAFE": "Sikker (alt av)",
"SETTINGS_GAMEPLAY_PROFILE_VANILLA": "Vanilla",
"SETTINGS_GAMEPLAY_PROFILE_RECOMMENDED": "Anbefalt (IPT-kjerne)",
"SETTINGS_GAMEPLAY_PROFILE_REALISTIC": "Realistisk",
"SETTINGS_SPEED_KPH": "km/t",
"SETTINGS_SPEED_MPH": "mph",
"SETTINGS_WALKING_SPEED": "Gå-/sykkelhastighet: ",
"SETTINGS_WALKING_SPEED_TOOLTIP": "Standard: basisspillets hastigheter.\nRealistisk: reduserer gåhastighet til realistiske, aldersbaserte verdier.\nRealistisk reduserer også sykkelhastighet med After Dark DLC.",
"SETTINGS_WALKING_SPEED_MODE_VANILLA": "Standard",
"SETTINGS_WALKING_SPEED_MODE_REALISTIC": "Realistisk",
"SETTINGS_BBSP": "Bedre busstopp-posisjon: ",
"SETTINGS_BBSP_TOOLTIP": "Deaktivert: ingen posisjonsjustering.\nAktivert: busser stopper foran på busstoppet i stedet for midt.",
"SETTINGS_BBSP_MODE_DISABLED": "Deaktivert",
"SETTINGS_BBSP_MODE_ORIGINAL": "Aktivert",
"SETTINGS_BBSP_MODE_UPDATED": "Bruk eksperimentell logikk",
"SETTINGS_BUDGET": "Budsjett",
"SETTINGS_ENABLE_BUDGET_CONTROL": "Linjebudsjettkontroll:",
"SETTINGS_BUDGET_CONTROL_DISABLED": "Deaktivert",
"SETTINGS_BUDGET_CONTROL_ENABLED": "Aktivert",
"SETTINGS_BUDGET_CONTROL_TOOLTIP": "Når aktivert styres antall kjøretøy på transportlinjer av budsjettet; oppdaterer alle eksisterende linjer og tømmer kjøretøy i kø.",
"SETTINGS_BUDGET_TICKET_PRICES": "Billettpris-tilpasning:",
"SETTINGS_BUDGET_TICKET_PRICES_DISABLED": "Deaktivert",
"SETTINGS_BUDGET_TICKET_PRICES_ENABLED": "Aktivert",
"SETTINGS_BUDGET_TICKET_PRICES_TOOLTIP": "Når aktivert legges en ny fane til Økonomi-panelet med glidebrytere for billettpriser for hver transporttype.",
"SETTINGS_AUTO_LINE_BUDGET": "Automatisk flåtestørrelse:",
"SETTINGS_AUTO_LINE_BUDGET_DISABLED": "Deaktivert",
"SETTINGS_AUTO_LINE_BUDGET_ENABLED": "Aktivert",
"SETTINGS_AUTO_LINE_BUDGET_TOOLTIP": "Når aktivert tilpasser linjer i budsjettmodus automatisk kjøretøyantallet etter reell passasjerefterspørsel i stedet for vanilla-budsjettglidebryteren. Linjer satt til Manuell berøres aldri.",
"SETTINGS_AUTO_LINE": "Auto-linje",
"SETTINGS_AUTOSHOW_LINE_INFO": "Åpne linjeinfo-panel automatisk",
"SETTINGS_AUTOSHOW_LINE_INFO_TOOLTIP": "Vis linjeinfo-panelet automatisk etter at en ny linje er opprettet.",
"AUTOLINECOLOR_STRATEGY_DISABLED": "Deaktivert",
"AUTOLINECOLOR_STRATEGY_RANDOM_HUE": "Tilfeldig nyanse",
"AUTOLINECOLOR_STRATEGY_RANDOM_COLOR": "Tilfeldig farge",
"AUTOLINECOLOR_STRATEGY_CATEGORISED": "Kategorisert",
"AUTOLINECOLOR_STRATEGY_NAMED": "Navngitte farger",
"AUTOLINECOLOR_NAMING_DISABLED": "Deaktivert",
"AUTOLINECOLOR_NAMING_DISTRICTS": "Distrikter",
"AUTOLINECOLOR_NAMING_LONDON": "London",
"AUTOLINECOLOR_NAMING_ROADS": "Veier",
"AUTOLINECOLOR_NAMING_COLORS": "Navngitte farger",
"AUTOLINECOLOR_COLOR_STRATEGY": "Fargestrategi:",
"AUTOLINECOLOR_COLOR_STRATEGY_TOOLTIP": "Hvordan farger tildeles nye linjer:\n'Tilfeldig nyanse' = samme metning/lysstyrke, ulike nyanser;\n'Tilfeldig farge' = fullstendig tilfeldig RGB;\n'Kategorisert' = farger etter kjøretøytype;\n'Navngitte farger' = forhåndsdefinert fargepalett.",
"AUTOLINECOLOR_NAMING_STRATEGY": "Navnestrategi:",
"AUTOLINECOLOR_NAMING_STRATEGY_TOOLTIP": "Hvordan navn tildeles nye linjer:\n'Ingen' = ingen auto-navngiving;\n'Distrikter' = basert på betjente distrikter;\n'London' = nummererte ruter (London Buses-stil);\n'Veier' = basert på gatenavn;\n'Navngitte farger' = basert på fargenavn.",
"AUTOLINECOLOR_MIN_COLOR_DIFF": "Minimum fargeforskjell (%):",
"AUTOLINECOLOR_MIN_COLOR_DIFF_TOOLTIP": "Minimum fargeforskjell i prosent ved valg av tilfeldige farger.",
"AUTOLINECOLOR_MAX_COLOR_PICK": "Maksimale forsøk:",
"AUTOLINECOLOR_MAX_COLOR_PICK_TOOLTIP": "Maksimalt antall forsøk på å velge en skillelig farge.",
"SETTINGS_UI": "UI-innstillinger",
"SETTINGS_VEHICLE_EDITOR_POSITION": "Kjøretøyeditor-posisjon: ",
"SETTINGS_VEHICLE_EDITOR_POSITION_TOOLTIP": "Velg om kjøretøyeditoren vises nederst eller til høyre på skjermen.",
"SETTINGS_VEHICLE_EDITOR_POSITION_BOTTOM": "Nederst",
"SETTINGS_VEHICLE_EDITOR_POSITION_RIGHT": "Høyre",
"SETTINGS_VEHICLE_EDITOR_HIDE": "Skjul kjøretøyeditor",
"SETTINGS_VEHICLE_EDITOR_HIDE_TOOLTIP": "Skjul kjøretøyeditoren fra kjøretøypaneler.",
"SETTINGS_STOPS": "Kollektivstopp",
"SETTINGS_STOPSANDSTATIONS_DESCRIPTION": "Hvor mange passasjerer av hver transporttype som kan vente ved ett stopp før det regnes som fullt. Høyere verdier reduserer overfyllingsklager ved travle stopp på bekostning av en mindre realistisk køstørrelse.",
"SETTINGS_STOPSANDSTATIONS_RESET_TOOLTIP": "Tilbakestill alle passasjergrenser ovenfor til standardverdier.",
"SETTINGS_ENABLE_STOPS_AND_STATIONS": "Aktiver stopp og stasjoner",
"SETTINGS_ENABLE_STOPS_AND_STATIONS_TOOLTIP": "Juster maksimalt antall borgere som kan vente på kollektivtrafikk ved stopp og stasjoner. Konfigurer under fanen Stopp.",
"SETTINGS_STOPSANDSTATIONS_ENABLE": "Aktiver stopp og stasjoner",
"SETTINGS_STOPSANDSTATIONS_ENABLE_TOOLTIP": "Aktiver eller deaktiver håndheving av passasjergrenser ved stopp.",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HEADER": "Maksimalt ventende passasjerer ved et linjestopp:",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS": "Linjebuss",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BUS_TOOLTIP": "Maksimalt ventende passasjerer ved et linjebusstopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS": "Trolleybuss",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TROLLEYBUS_TOOLTIP": "Maksimalt ventende passasjerer ved et trolleybusstopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS": "Evakueringsbuss",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_EVACUATION_BUS_TOOLTIP": "Maksimalt ventende passasjerer ved et evakueringsbusstopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS": "Turistbuss",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TOURIST_BUS_TOOLTIP": "Maksimalt ventende passasjerer ved et turistbusstopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM": "Trikk",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAM_TOOLTIP": "Maksimalt ventende passasjerer ved et trikkestopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO": "T-bane",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_METRO_TOOLTIP": "Maksimalt ventende passasjerer ved en T-banestasjon",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN": "Tog",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_TRAIN_TOOLTIP": "Maksimalt ventende passasjerer ved en togstasjon",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL": "Monorail",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_MONORAIL_TOOLTIP": "Maksimalt ventende passasjerer ved et monorailstopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP": "Skip",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_SHIP_TOOLTIP": "Maksimalt ventende passasjerer ved en godsskiphavn",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY": "Ferge",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_FERRY_TOOLTIP": "Maksimalt ventende passasjerer ved et fergestopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE": "Fly",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_AIRPLANE_TOOLTIP": "Maksimalt ventende passasjerer ved en flyterminal",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR": "Taubane",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_CABLECAR_TOOLTIP": "Maksimalt ventende passasjerer ved et taubanestopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON": "Varmluftsballong",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HOTAIRBALLOON_TOOLTIP": "Maksimalt ventende passasjerer ved et ballongstopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER": "Helikopter",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_HELICOPTER_TOOLTIP": "Maksimalt ventende passasjerer ved et helikopterstopp",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP": "Luftskip",
"SETTINGS_STOPSANDSTATIONS_MAX_PASSENGERS_BLIMP_TOOLTIP": "Maksimalt ventende passasjerer ved et luftskipstopp",
"SETTINGS_UNBUNCHING": "Avstandsstyring",
"SETTINGS_UNBUNCHING_AGGRESSION": "Avstandsstyrings-aggressivitet:",
"SETTINGS_UNBUNCHING_AGGRESSION_TOOLTIP": "Hvor sterkt skal avstandsstyring virke?\nMulige verdier: 0–52. Verdi 0 deaktiverer avstandsstyring.\nHøyere verdier påvirker trafikken sterkt og kan få kjøretøy til å forsvinne.",
"SETTINGS_VEHICLE_COUNT": "Kjøretøy på nye linjer:",
"SETTINGS_VEHICLE_COUNT_TOOLTIP": "Antall kjøretøy som automatisk legges til nye linjer når linjebudsjettkontroll er av.",
"SETTINGS_SPAWN_TIME_INTERVAL": "Spawn-tidsintervall:",
"SETTINGS_SPAWN_TIME_INTERVAL_TOOLTIP": "Tid i sekunder mellom kjøretøyspawns.",
"SETTINGS_UNBUNCHING_RESET_BUTTON_TOOLTIP": "Tilbakestiller alle glidebrytere til standard.",
"UNBUNCHING_ENABLED": "Avstandsstyring for kjøretøy",
"UNBUNCHING_DISABLED": "Avstandsstyring er deaktivert.",
"UNBUNCHING_TARGET_GAP": "Målavstand: {0}",
"SETTINGS_EBS_GROUP_BUS": "Ekspressbusstjenester",
"SETTINGS_EBS_GROUP_TRAM": "Ekspresstrikketjenester",
"SETTINGS_EBS_DROPDOWN_UNBUNCHING_MODE": "Ekspressbuss: ",
"SETTINGS_EBS_TOOLTIP_UNBUNCHING_MODE": "'Deaktivert' = Busser bruker avstandsstyring ovenfor.\n'Forsiktig' = Stopper kort, sjekker passasjerer, kan kjøre tomt.\n'Aggressiv' = Hopper over stopp hvis ingen passasjerer venter.",
"SETTINGS_EBS_ENABLE_SELFBAL": "Aktiver selvbalansering av tjeneste",
"SETTINGS_EBS_DESC_SELFBAL": "Lar ekspressbusstjenesten omfordele kjøretøy langs linjen for å prioritere travle segmenter og redusere ventetid.",
"SETTINGS_EBS_TOOLTIP_SELFBAL": "Analyserer linjesegmenter og kan omplassere kjøretøy til travlere segmenter eller endestasjoner for jevnere tjeneste og kortere ventetid.\nBeslutninger er probabilistiske og avhenger av passasjertall og omplasseringsodds.",
"SETTINGS_EBS_ENABLE_SELFBAL_TARGETMID": "Aktiver selvbalansering til midtlinje-stopp",
"SETTINGS_EBS_DESC_SELFBAL_TARGETMID": "Tillater selvbalansering å velge et travelt stopp midt på linjen i stedet for bare en endestasjon ved omplassering.",
"SETTINGS_EBS_TOOLTIP_SELFBAL_TARGETMID": "Tillat selvbalansering å omplassere kjøretøy til et travelt midtlinje-stopp (i stedet for endestasjon).\nVurderes bare når det travleste stoppet har over 30 ventende passasjerer, deretter valgt med ~50 % sannsynlighet og underlagt totale omplasseringsodds.",
"SETTINGS_EBS_ENABLE_MINIBUS": "Aktiver minibus-modus",
"SETTINGS_EBS_DESC_MINIBUS": "Får mindre busser til å kjøre tidligere når bare få passasjerer stiger på eller av.",
"SETTINGS_EBS_TOOLTIP_MINIBUS": "Busser med kapasitet ≤20 kan kjøre tidligere fra et stopp når påstigende + avstigende passasjerer ≤5.",
"SETTINGS_EBS_DROPDOWN_TRAM_UNBUNCHING_MODE": "Ekspresstrikk: ",
"SETTINGS_EBS_TOOLTIP_TRAM_UNBUNCHING": "'Deaktivert' = Trikker bruker avstandsstyring ovenfor.\n'Bybane' = Stopper ved hvert stopp, venter alltid full tid (streng disiplin).\n'Ekte trikk' = Stopper bare når passasjerer stiger på/av.",
"SETTINGS_EBS_MODE_NONE": "Deaktivert",
"SETTINGS_EBS_MODE_AGGRESSIVE": "Aggressiv",
"SETTINGS_EBS_MODE_PRUDENTIAL": "Forsiktig",
"SETTINGS_EBS_TRAM_MODE_LIGHT_RAIL": "Bybane-modus",
"SETTINGS_EBS_TRAM_MODE_NONE": "Deaktivert",
"SETTINGS_EBS_TRAM_MODE_TRAM": "Ekte trikk-modus",
"SETTINGS_PTU_GROUP": "Frigjør fastsittende passasjerer",
"SETTINGS_PTU_ENABLE": "Fjern fastsittende passasjerer",
"SETTINGS_PTU_TOOLTIP": "Fjerner automatisk passasjerer som sitter fast under ombordstigning, slik at kjøretøyet kan kjøre normalt og unngå frosne avganger.",
"SETTINGS_LINE_DELETION_TOOL": "Verktøy for sletting av linjer",
"SETTINGS_LINE_DELETION_TOOL_DESCRIPTION": "Merk transporttypene nedenfor, og trykk Slett for å fjerne alle linjer av de typene fra gjeldende by. Valget er midlertidig - det starter alltid umerket og tømmes etter sletting; det lagres ikke som innstilling.",
"SETTINGS_LINE_DELETION_TOOL_BUTTON_TOOLTIP": "Sletter alle linjer av de valgte typene. Fungerer bare mens byen er lastet.",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_TITLE": "BEKREFT SLETTING AV LINJER",
"SETTINGS_LINE_DELETION_TOOL_CONFIRM_MSG": "Du er i ferd med å slette alle linjer.\nVil du fortsette?",
"SETTINGS_DELETE_BUS_TOOLTIP": "Sletter alle vanlige bussruter.",
"SETTINGS_DELETE_SIGHTSEEING_BUS_LABEL": "Turistbusser",
"SETTINGS_DELETE_SIGHTSEEING_BUS_TOOLTIP": "Sletter alle turistbussruter.",
"SETTINGS_DELETE_TRAM_TOOLTIP": "Sletter alle trikkeruter.",
"SETTINGS_DELETE_TROLLEYBUS_TOOLTIP": "Sletter alle trolleybussruter.",
"SETTINGS_DELETE_TRAIN_TOOLTIP": "Sletter alle togruter.",
"SETTINGS_DELETE_METRO_TOOLTIP": "Sletter alle underjordiske T-baneruter.",
"SETTINGS_DELETE_MONORAIL_TOOLTIP": "Sletter alle monorailruter.",
"SETTINGS_DELETE_FERRY_LABEL": "Ferger",
"SETTINGS_DELETE_SHIP_TOOLTIP": "Sletter alle fergeruter.",
"SETTINGS_DELETE_HELICOPTER_LABEL": "Helikoptre",
"SETTINGS_DELETE_HELICOPTER_TOOLTIP": "Sletter alle helikopterruter.",
"SETTINGS_DELETE_BLIMP_LABEL": "Luftskip",
"SETTINGS_DELETE_BLIMP_TOOLTIP": "Sletter alle luftskipruter.",
"VEHICLE_EDITOR_TITLE": "Kjøretøyeditor",
"VEHICLE_EDITOR_SUB_TITLE": "{0} kjøretøy",
"VEHICLE_EDITOR_CAPACITY": "Passasjerkapasitet",
"VEHICLE_EDITOR_CAPACITY_TAXI": "Reisekapasitet",
"VEHICLE_EDITOR_CAPACITY_TAXI_TOOLTIP": "Antall passasjerer per arbeidsskift.",
"VEHICLE_EDITOR_MAINTENANCE": "Vedlikeholdskostnad",
"VEHICLE_EDITOR_MAX_SPEED": "Maks. hastighet",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS": "Togmotor i begge ender",
"VEHICLE_EDITOR_ENGINE_ON_BOTH_ENDS_TOOLTIP": "Aktiverer eller deaktiverer togmotorer i begge ender av toget.",
"VEHICLE_EDITOR_APPLY": "Bruk",
"VEHICLE_EDITOR_DEFAULT": "Standard",
"VEHICLE_LIST_BOX_ROW_TOOLTIP1": "Høyreklikk for å følge dette kjøretøyet.\nHold Shift nede under klikk for også å zoome inn.",
"VEHICLE_LIST_BOX_ROW_TOOLTIP2": "Shift + klikk for å sette dette kjøretøyet i kø.",
"VEHICLE_PANEL_EDIT_TYPE": "Rediger kjøretøytype",
"VEHICLE_PANEL_EDIT_TYPE_TOOLTIP": "Rediger denne kjøretøytypen med kjøretøyeditoren.",
"VEHICLE_PANEL_STATUS_NEXT_STOP": "Neste stopp:",
"VEHICLE_PANEL_STATUS_UNBUNCHING": "Avstandsstyring pågår",
"VEHICLE_PANEL_LAST_STOP_EXCHANGE": "Passasjerutveksling ved siste stopp: <color #FF0000>-{0}</color> | <color #00FF00>+{1}</color>",
"VEHICLE_PANEL_PASSENGERS": "Passasjerer:",
"VEHICLE_PANEL_EARNINGS": "Inntjening:",
"VEHICLE_PANEL_EARNINGS_TOOLTIP": "Resultat av billettsalg minus vedlikeholdskostnad for kjøretøyet.",
"VEHICLE_PANEL_PREVIOUS": "Forrige kjøretøy",
"VEHICLE_PANEL_PREVIOUS_TOOLTIP": "Hopp til forrige kjøretøy.\nHold Shift nede under klikk for også å zoome inn.",
"VEHICLE_PANEL_REMOVE_VEHICLE": "Fjern kjøretøy",
"VEHICLE_PANEL_NEXT": "Neste kjøretøy",
"VEHICLE_PANEL_NEXT_TOOLTIP": "Hopp til neste kjøretøy.\nHold Shift nede under klikk for også å zoome inn.",
"VEHICLE_SELECTION_CAPACITY": "Kapasitet",
"VEHICLE_SELECTION_ADD_VEHICLE": "Legg dette kjøretøyet til listen over tillatte kjøretøy",
"VEHICLE_SELECTION_ADD_ALL": "Legg alle egnede kjøretøy til listen over tillatte kjøretøy",
"VEHICLE_SELECTION_REMOVE_VEHICLE": "Fjern dette kjøretøyet fra listen over tillatte kjøretøy",
"VEHICLE_SELECTION_REMOVE_ALL": "Fjern alle kjøretøy fra listen over tillatte kjøretøy",
"VEHICLE_SELECTION_AVAILABLE_VEHICLES": "Tilgjengelige kjøretøy",
"VEHICLE_SELECTION_SELECTED_VEHICLES": "Valgte kjøretøy",
"VEHICLE_SELECTION_ANY_VEHICLE": "Ethvert kjøretøy",
"VEHICLE_BUTTON_TOOLTIP": "{0}\n\nKlikk for å hoppe til dette kjøretøyet.\nHold Shift nede under klikk for også å zoome inn.\nHold Alt nede under klikk for å unngå å åpne kjøretøyinfo-panelet.",
"TRANSPORT_LINE_VEHICLECOUNT": "Antall kjøretøy: {0}",
"FLIGHT_TRACKER_NAME": "Flytracker",
"FLIGHT_STATUS_NONE": "Ingen",
"FLIGHT_STATUS_INCOMING": "Innkommende",
"FLIGHT_STATUS_LANDED": "Landet",
"FLIGHT_STATUS_AT_GATE": "Ved gate",
"FLIGHT_STATUS_DEPARTED": "Avgått",
"TICKET_PRICE_TAXI_KILOMETER": "Taxipris per kilometer: ",
"TICKET_PRICE_TAXI_MILE": "Taxipris per mile: ",
"TICKET_PRICE_BUS": "Bussbillettpris: ",
"TICKET_PRICE_INTERCITY_BUS": "Intercitybuss-billettpris: ",
"TICKET_PRICE_METRO": "T-banebillettpris: ",
"TICKET_PRICE_TRAIN": "Togbillettpris: ",
"TICKET_PRICE_TRAM": "Trikkebillettpris: ",
"TICKET_PRICE_MONORAIL": "Monorail-billettpris: ",
"TICKET_PRICE_SHIP": "Skipbillettpris: ",
"TICKET_PRICE_FERRY": "Fergebillettpris: ",
"TICKET_PRICE_PLANE": "Flybillettpris: ",
"TICKET_PRICE_CABLECAR": "Taubanebillettpris: ",
"TICKET_PRICE_SIGHTSEEING_BUS": "Turistbussbillettpris: ",
"TICKET_PRICE_TROLLEYBUS": "Trolleybussbillettpris: ",
"TICKET_PRICE_BLIMP": "Luftskipbillettpris: ",
"TICKET_PRICE_HELICOPTER": "Helikopterbillettpris: ",
"ECONOMY_TAB_TICKET_PRICES": "Billettpriser",
"ECONOMY_TAB_TICKET_PRICES_TOOLTIP_PASSENGER_COUNT": "Totalt aktuelt passasjertall for denne transporttypen.",
"WHATSNEW_3_0_0_1": "Oppdatert for Race Day; nå kompatibel med More Vehicles Renewed.",
"WHATSNEW_3_0_0_2": "Følgende mods er integrert i IPT3:\n • Advanced Stop Selection Revisited\n • Auto Line Color Redux\n • Better Bus Stop Position\n • Better Train Boarding\n • Elevated Stops Enabler Revisited  \n • Express Bus Services\n • Flight Tracker\n • Intercity Bus Control\n • Mileage Taxi Services\n • Public Transport Unstucker\n • Realistic Walking Speed\n • Stops and Stations\n • Ticket Price Customizer",
"WHATSNEW_3_0_1": "Public Transport Unstucker er nå integrert i IPT3.\nSe versjon 3.0 for alle andre integrerte mods. Avmeld originalene for å unngå konflikter.",
"SETTINGS_TAB_TRAINDISPLAY": "Togvisning",
"SETTINGS_TAB_INTEGRATIONS": "Integrasjoner",
"SETTINGS_TRAINDISPLAY_GROUP": "Togvisning-overlay",
"SETTINGS_TRAINDISPLAY_GROUP_DESCRIPTION": "Konfigurer det integrerte overlayet som vises mens du følger støttede transportkjøretøy.",
"SETTINGS_TRAINDISPLAY_ENABLE": "Aktiver togvisning",
"SETTINGS_TRAINDISPLAY_ENABLE_TOOLTIP": "Slå det integrerte togvisning-overlayet av eller på.",
"SETTINGS_TRAINDISPLAY_MODE_DISABLED": "Deaktivert",
"SETTINGS_TRAINDISPLAY_MODE_ENABLED": "Aktivert",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION": "Overlay-posisjon:",
"SETTINGS_TRAINDISPLAY_OVERLAY_POSITION_TOOLTIP": "Velg hvor overlayet vises på skjermen.",
"SETTINGS_TRAINDISPLAY_POS_TOPLEFT": "Øverst til venstre",
"SETTINGS_TRAINDISPLAY_POS_TOPRIGHT": "Øverst til høyre",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMLEFT": "Nederst til venstre",
"SETTINGS_TRAINDISPLAY_POS_BOTTOMRIGHT": "Nederst til høyre",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE": "Overlay-skala:",
"SETTINGS_TRAINDISPLAY_OVERLAY_SCALE_TOOLTIP": "Skaler overlayets størrelse.",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY": "Overlay-gjennomsiktighet:",
"SETTINGS_TRAINDISPLAY_OVERLAY_OPACITY_TOOLTIP": "Juster hvor gjennomsiktig overlayet er.",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL": "Oppdateringsintervall:",
"SETTINGS_TRAINDISPLAY_UPDATE_INTERVAL_TOOLTIP": "Hvor ofte overlayet oppdateres mens du følger et kjøretøy.",
"SETTINGS_TRAINDISPLAY_SHOW_LINE": "Vis linjenavn",
"SETTINGS_TRAINDISPLAY_SHOW_LINE_TOOLTIP": "Inkluder linjenavnet i overlayet.",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION": "Vis destinasjon",
"SETTINGS_TRAINDISPLAY_SHOW_DESTINATION_TOOLTIP": "Inkluder destinasjonen i overlayet.",
"SETTINGS_TRAINDISPLAY_SHOW_STATE": "Vis tilstand",
"SETTINGS_TRAINDISPLAY_SHOW_STATE_TOOLTIP": "Inkluder kjøretøyets tilstand i overlayet.",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING": "Bare under følging",
"SETTINGS_TRAINDISPLAY_ONLY_WHILE_FOLLOWING_TOOLTIP": "Skjul overlayet med mindre kameraet faktisk følger et støttet kjøretøy.",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY": "Bare i førstepersonskamera",
"SETTINGS_TRAINDISPLAY_FIRST_PERSON_ONLY_TOOLTIP": "Vis bare overlayet ved bruk av en førstepersonskameramod (f.eks. First Person Camera - Continued). Hvis av, vises det når du følger et støttet kjøretøy i en hvilken som helst kameramodus.",
"SETTINGS_TRAINDISPLAY_THEME": "Fargetema:",
"SETTINGS_TRAINDISPLAY_THEME_TOOLTIP": "Velg overlayets bakgrunns-/tekstfarger.",
"SETTINGS_TRAINDISPLAY_THEME_SIMPLE": "Enkel",
"SETTINGS_TRAINDISPLAY_THEME_DARK": "Mørk",
"SETTINGS_TRAINDISPLAY_THEME_LIGHT": "Lys",
"SETTINGS_TRAINDISPLAY_THEME_ORIGINAL": "Original",
"SETTINGS_TRAINDISPLAY_THEME_BLUE": "Blå",
"SETTINGS_TRAINDISPLAY_THEME_GREEN": "Grønn",
"SETTINGS_TRAINDISPLAY_THEME_AMBER": "Rav",
"COPY_TIP": "Kopier denne linjens innstillinger.",
"PASTE_TIP": "Lim inn de kopierte linjeinnstillingene.",
"COPY_BUILDING_TIP": "Kopier disse innstillingene til alle linjer som betjener denne bygningen.",
"COPY_DISTRICT_TIP": "Kopier disse innstillingene til alle linjer i dette distriktet.",
"SETTINGS_INTEGRATIONS_GROUP": "Integrerte tillegg",
"SETTINGS_INTERCITY_BUS_ENABLE": "Aktiver intercitybuss-kontroll",
"SETTINGS_INTERCITY_BUS_ENABLE_TOOLTIP": "Aktiverer det integrerte intercitybuss-kompatibilitetslaget og stasjonspatching.",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE": "Aktiver avansert stoppvalg",
"SETTINGS_ADVANCEDSTOPSELECTION_ENABLE_TOOLTIP": "Lar deg plassere stopp på alternative plattformer/spor på flersporede stasjoner (hold alternativ-modus-tasten under plassering). Trer i kraft ved neste nivålasting.",
"SETTINGS_BETTERBOARDING_ENABLE": "Aktiver bedre ombordstigning",
"SETTINGS_BETTERBOARDING_ENABLE_TOOLTIP": "Forbedrer ombordstigningsvalg slik at passasjerer foretrekker kjøretøyet som faktisk betjener destinasjonen deres. Trer i kraft ved neste nivålasting.",
"SETTINGS_MILEAGETAXI_ENABLE": "Aktiver kilometertaxi",
"SETTINGS_MILEAGETAXI_ENABLE_TOOLTIP": "Tar betalt for taxi etter kjørt distanse i stedet for fast pris, slik at lengre turer gir mer. Krever After Dark DLC. Trer i kraft ved neste nivålasting.",
"SETTINGS_ELEVATEDSTOPS_ENABLE": "Aktiver forhøyede stopp",
"SETTINGS_ELEVATEDSTOPS_ENABLE_TOOLTIP": "Tillater kollektivstopp på forhøyede veier/broer og beholder gatebelysning på de segmentene. Trer i kraft ved neste nivålasting.",
"SETTINGS_INTERCITY_BUS_CAPACITY": "Kapasitet for intercityterminal",
"SETTINGS_INTERCITY_BUS_CAPACITY_TOOLTIP": "Hvor mange kjøretøy en intercitybussterminal kan romme samtidig.",
"SETTINGS_TRAM_DEPOT_CAPACITY": "Trikkedepot-kapasitet",
"SETTINGS_TRAM_DEPOT_CAPACITY_TOOLTIP": "Vanilla gir hvert trikkedepot en praktisk ubegrenset grense på 100 000 kjøretøy. Realistisk og Middels bruker i stedet et moderat fast tak; Deaktivert bevarer eksisterende oppførsel.",
"SETTINGS_TAXI_DEPOT_CAPACITY": "Taxidepot-kapasitet",
"SETTINGS_TAXI_DEPOT_CAPACITY_TOOLTIP": "Vanilla gir hvert taxidepot en praktisk ubegrenset grense på 100 000 kjøretøy. Realistisk og Middels bruker i stedet et moderat fast tak; Deaktivert bevarer eksisterende oppførsel.",
"SETTINGS_BUS_DEPOT_CAPACITY": "Bussdepot-kapasitet",
"SETTINGS_BUS_DEPOT_CAPACITY_TOOLTIP": "Vanilla gir hvert bussdepot (vanlige, biodrivstoff og turistbussgarasjer) en praktisk ubegrenset grense på 100 000 kjøretøy. Realistisk og Middels bruker i stedet et moderat fast tak; Deaktivert bevarer eksisterende oppførsel.",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY": "Trolleybussdepot-kapasitet",
"SETTINGS_TROLLEYBUS_DEPOT_CAPACITY_TOOLTIP": "Vanilla gir hvert trolleybussdepot en praktisk ubegrenset grense på 100 000 kjøretøy. Realistisk og Middels bruker i stedet et moderat fast tak; Deaktivert bevarer eksisterende oppførsel.",
"SETTINGS_FERRY_DEPOT_CAPACITY": "Fergedepot-kapasitet",
"SETTINGS_FERRY_DEPOT_CAPACITY_TOOLTIP": "Vanilla gir hvert fergedepot en praktisk ubegrenset grense på 100 000 kjøretøy. Realistisk og Middels bruker i stedet et moderat fast tak; Deaktivert bevarer eksisterende oppførsel.",
"SETTINGS_DEPOT_CAPACITY_DISABLED": "Deaktivert (ubegrenset)",
"SETTINGS_DEPOT_CAPACITY_INTERMEDIATE": "Middels",
"SETTINGS_DEPOT_CAPACITY_REALISTIC": "Realistisk",
"SETTINGS_FLIGHTTRACKER_ENABLE": "Aktiver flytracker",
"SETTINGS_FLIGHTTRACKER_ENABLE_TOOLTIP": "Aktiverer de integrerte flytracker-patchene og UI-støtten.",
"SETTINGS_SUBBUILDINGSTABS_ENABLE": "Aktiver underbygning-faner",
"SETTINGS_SUBBUILDINGSTABS_ENABLE_TOOLTIP": "Viser en fanestripe på en bygnings infopanel når den har underbygninger (f.eks. en lufthavn med innebygd T-banestasjon), slik at du kan bytte mellom dem.",
"SETTINGS_TAXISTANDFIX_ENABLE": "Aktiver taxistandplass-rettelse",
"SETTINGS_TAXISTANDFIX_ENABLE_TOOLTIP": "Sender ledige taxier til nærmeste holdeplass i stedet for å la dem kjøre tilfeldig. Krever After Dark DLC.",
"SETTINGS_SHAREDSTOPENABLER_ENABLE": "Aktiver delte stopp",
"SETTINGS_SHAREDSTOPENABLER_ENABLE_TOOLTIP": "Tillater mer enn én transporttype (buss, trikk, trolleybuss) å stoppe på samme veisegment. Av som standard - se moddens GitHub for hva denne reduserte versjonen utelater.",
"SETTINGS_COMMUTERDESTINATION_ENABLE": "Aktiver passasjerdestinasjon (redesign venter)",
"SETTINGS_COMMUTERDESTINATION_ENABLE_TOOLTIP": "Midlertidig utilgjengelig: det tidligere panelet dupliserte stoppinfo-UI og er tvunget av til et redesign. Avkrysningsboksen kan ikke reaktivere det.",
"SETTINGS_OOC_ENABLE": "Optimaliserte eksterne forbindelser",
"SETTINGS_OOC_ENABLE_TOOLTIP": "Godstog, fly og skip venter lenger på en fyldigere last før de drar ved eksterne forbindelser.",
"SETTINGS_OOC_WAIT_MULTIPLIER": "Ventemultiplikator",
"SETTINGS_OOC_WAIT_MULTIPLIER_TOOLTIP": "Hvor mye lenger enn vanilla det ventes på en fyldigere last. Høyere verdier betyr færre, men fyldigere turer.",
"SETTINGS_OOC_PASSENGER_SCOPE": "Omfang for passasjerventetid",
"SETTINGS_OOC_PASSENGER_SCOPE_TOOLTIP": "Hvor ventemultiplikatoren ovenfor gjelder for borgere som venter på kollektivtrafikk. Bare eksterne forbindelser påvirker bare borgere som venter ved en ekstern forbindelse; byomfattende forsinker også vanlig innenlandsk venting for alle borgere (matcher kildemodens faktiske oppførsel).",
"SETTINGS_OOC_PASSENGER_SCOPE_OUTSIDE": "Bare eksterne forbindelser",
"SETTINGS_OOC_PASSENGER_SCOPE_CITYWIDE": "Byomfattende",
"SETTINGS_OOC_PASSENGER_SCOPE_DISABLED": "Deaktivert (vanilla)",
"SETTINGS_OOC_DISABLE_DUMMY": "Deaktiver dekorativ gjennomkjøringstrafikk",
"SETTINGS_OOC_DISABLE_DUMMY_ROAD": "Deaktiver dekorativ veitrafikk",
"SETTINGS_OOC_DISABLE_DUMMY_TRAIN": "Deaktiver dekorativ togtrafikk",
"SETTINGS_OOC_DISABLE_DUMMY_PLANE": "Deaktiver dekorativ flytrafikk",
"SETTINGS_OOC_DISABLE_DUMMY_SHIP": "Deaktiver dekorativ skipstrafikk",
"SETTINGS_OOC_DISABLE_DUMMY_TOOLTIP": "Eksterne forbindelser spawner normalt ekstra dekorativ trafikk som aldri reelt kommer inn i eller forlater byen, bare for visuell atmosfære. Deaktivering fjerner den trafikken uten å påvirke reell import/eksport/passasjerflyt.",
"SETTINGS_UOC_ENABLE": "Ubegrensede eksterne forbindelser",
"SETTINGS_UOC_ENABLE_TOOLTIP": "Fjerner vanillas grense på 4 forbindelser for veier, skinner, skips- og flyruter, og kobler retrospektivt transportlinjer når en ny forbindelse bygges nær en eksisterende stasjon. Trer i kraft ved neste nivålasting.",
"SETTINGS_STTAI_ENABLE": "Kollisjonsunngåelse på enkeltsporet jernbane",
"SETTINGS_STTAI_ENABLE_TOOLTIP": "Reserverer et enkeltsporet segment for ett tog om gangen og holder et motsatt tog ved inngangen til segmentet er fritt. Original IPT4-funksjon, finnes ikke i vanilla eller noen absorbert mod.",
"SETTINGS_STOPSTACKER_ENABLE": "Stabling av busstopp-plasser",
"SETTINGS_STOPSTACKER_ENABLE_TOOLTIP": "Lar en andre/tredje buss som nærmer seg samme stopp bruke sin egen plass lenger bak langs stoppsporet i stedet for å stå i enkeltfil bak den fremste bussen, slik at flere busser kan laste/losse samtidig. Original IPT4-funksjon (forenklet clean-room-reimplementering), finnes ikke i vanilla eller noen absorbert mod.",
"TRAINDISPLAY_LABEL_NAME": "Navn",
"TRAINDISPLAY_LABEL_STATUS": "Status",
"TRAINDISPLAY_NO_LINE": "Ingen linje",
"TRAINDISPLAY_NO_DESTINATION": "Ingen destinasjon",
"TRAINDISPLAY_HIDDEN": "Skjult",
"TRAINDISPLAY_VEHICLE": "Kjøretøy",
"TRAINDISPLAY_STATE_RETURNING": "Returnerer",
"TRAINDISPLAY_STATE_STOPPED": "Ved stopp",
"TRAINDISPLAY_STATE_EN_ROUTE": "Underveis",
"TRAINDISPLAY_STATE_ON_LINE": "På linjen",
"TRAINDISPLAY_STATE_IDLE": "Inaktiv",
"AUTOLINECOLOR_REFRESH_BUTTON": "Oppdater navn/farge",
"AUTOLINECOLOR_REFRESH_BUTTON_TOOLTIP": "Tildel på nytt det aktuelle linjenavnet og fargen etter de aktive AutoLineColor-innstillingene.",
"AUTOLINECOLOR_REFRESH_DISABLED_TOOLTIP": "Aktiver en farge- eller navnestrategi under Innstillinger før du oppdaterer denne linjen.",
"TICKET_PRICE_LABEL_TOOLTIP": "Aktuell pris: {0}\nOriginal pris: {1}\nPassasjerer underveis nå: {2}",
})


if __name__ == "__main__":
    emit("no", NO)
    try:
        from lang_packs_sv_fi import SV, FI

        emit("sv", SV)
        emit("fi", FI)
    except Exception as e:
        print("sv/fi:", e)
    try:
        from lang_packs_hu_ro import HU

        emit("hu", HU)
    except Exception as e:
        print("hu:", e)

